;;;; test/api.lisp — Lisp-side API tests (things the SQLite oracle can't
;;;; exercise: user-defined functions, aggregates and collations).

(in-package #:sqlite-pure.test)

(defvar *api-fails* 0)

(defmacro is (name form expected)
  `(let ((got (handler-case ,form (error (e) (list :error (princ-to-string e))))))
     (if (equalp got ,expected)
         (format t "  ok   ~a~%" ,name)
         (progn (incf *api-fails*)
                (format t "  FAIL ~a~%       want ~s~%       got  ~s~%" ,name ,expected got)))))

(defun run-api ()
  (setf *api-fails* 0)
  (s:with-database (db ":memory:")
    ;; scalar functions
    (s:define-function db "double" (lambda (x) (if (eq x :null) nil (* 2 x))) :arity 1)
    (s:define-function db "join3" (lambda (&rest xs) (format nil "~{~a~^-~}" xs)))
    (is "scalar" (s:query-value db "SELECT double(21)") 42)
    (is "scalar NULL" (s:query-value db "SELECT double(NULL)") :null)
    (is "variadic" (s:query-value db "SELECT join3(1, 'b', 'c')") "1-b-c")
    (is "arity checked" (s:query-value db "SELECT double(1, 2)")
        '(:error "SQLite error: wrong number of arguments to function double()"))
    (is "unknown function" (s:query-value db "SELECT truth()") (quote (:error "SQLite error: no such function: truth")))
    (s:define-function db "half" (lambda (x) (/ x 2)) :arity 1)
    (is "ratio -> double" (s:query-value db "SELECT half(3)") 1.5d0)
    (s:define-function db "upper" (lambda (x) (format nil "<~a>" x)) :arity 1)
    (is "shadows a built-in" (s:query-value db "SELECT upper('x')") "<x>")
    (s:undefine-function db "upper")
    (is "built-in back" (s:query-value db "SELECT upper('x')") "X")
    (s:execute db "CREATE TABLE t(g, v)")
    (s:execute db "INSERT INTO t VALUES ('a', 1), ('a', 5), ('b', 2), ('b', NULL), ('c', 7)")
    (is "in WHERE and ORDER BY" (s:query db "SELECT v FROM t WHERE double(v) > 3 ORDER BY double(v) DESC")
        '((7) (5) (2)))
    ;; aggregates
    (s:define-aggregate db "product"
                        (lambda (acc x) (if (eq x :null) acc (* acc x)))
                        :initial 1 :arity 1)
    (s:define-aggregate db "collect"
                        (lambda (acc x) (cons x acc))
                        :final (lambda (acc) (format nil "~{~a~^,~}" (reverse acc))) :arity 1)
    (is "aggregate" (s:query-value db "SELECT product(v) FROM t") 70)
    (is "aggregate GROUP BY" (s:query db "SELECT g, product(v), collect(v) FROM t GROUP BY g ORDER BY g")
        '(("a" 5 "1,5") ("b" 2 "2,NULL") ("c" 7 "7")))
    (is "aggregate as window" (s:query db "SELECT v, product(v) OVER (ORDER BY v) FROM t WHERE v IS NOT NULL ORDER BY v")
        '((1 1) (2 2) (5 10) (7 70)))
    (is "aggregate DISTINCT" (s:query-value db "SELECT collect(DISTINCT g) FROM t") "a,b,c")
    (is "fresh state per query" (s:query-value db "SELECT product(v) FROM t") 70)
    ;; collations
    (s:define-collation db "reverse" (lambda (a b) (compare-lisp b a)))
    (s:define-collation db "len" (lambda (a b) (- (length a) (length b))) :key #'length)
    (s:execute db "CREATE TABLE w(s TEXT COLLATE reverse)")
    (s:execute db "INSERT INTO w VALUES ('b'), ('a'), ('c')")
    (is "column collation orders" (s:query db "SELECT s FROM w ORDER BY s") '(("c") ("b") ("a")))
    (s:execute db "CREATE INDEX ws ON w(s)")
    (is "index uses it" (s:query db "SELECT s FROM w WHERE s = 'b'") '(("b")))
    (is "index order" (s:query db "SELECT s FROM w ORDER BY s LIMIT 2") '(("c") ("b")))
    (is "COLLATE clause" (s:query db "SELECT s FROM w ORDER BY s COLLATE binary") '(("a") ("b") ("c")))
    (is "grouping via KEY" (s:query db "SELECT count(*) FROM (SELECT DISTINCT x COLLATE len FROM (SELECT 'ab' x UNION ALL SELECT 'cd' UNION ALL SELECT 'e'))")
        '((2)))
    (is "equality" (s:query-value db "SELECT 'ab' = 'xy' COLLATE len") 1)
    (is "unknown collation, lazily" (s:query-value db "SELECT 'a' < 'b' COLLATE nosuch")
        '(:error "SQLite error: no such collation sequence: NOSUCH"))
    (is "integrity" (s:query db "PRAGMA integrity_check") '(("ok"))))
  ;; a schema may name a collation before it is registered
  (let ((path (format nil "~a/sqlite-pure-api.db" (or (uiop:getenv "TMPDIR") "/tmp"))))
    (when (probe-file path) (delete-file path))
    (s:with-database (db path)
      (s:define-collation db "reverse" (lambda (a b) (compare-lisp b a)))
      (s:execute db "CREATE TABLE w(s TEXT COLLATE reverse)")
      (s:execute db "INSERT INTO w VALUES ('b'), ('a')"))
    (s:with-database (db path)
      (is "opens without the collation" (s:query-value db "SELECT count(*) FROM w") 2)
      (is "errors when it is needed" (s:query db "SELECT s FROM w ORDER BY s")
          '(:error "SQLite error: no such collation sequence: REVERSE"))
      (s:define-collation db "reverse" (lambda (a b) (compare-lisp b a)))
      (is "works once registered" (s:query db "SELECT s FROM w ORDER BY s") '(("b") ("a"))))
    (delete-file path))
  ;; user tokenizers and FTS5 auxiliary functions
  (s:with-database (db ":memory:")
    ;; words split on spaces, lowercased; "ing" stripped; a digit run also
    ;; indexed as its word ("2" -> "two") at the same position
    (s:define-tokenizer db "words"
      (lambda (text args)
        (let ((out '()) (start nil) (pos 0))
          (flet ((word (s e)
                   (let* ((w (string-downcase (subseq text s e)))
                          (w (if (and (member "stem" args :test #'string=) (> (length w) 4)
                                      (string= "ing" w :start2 (- (length w) 3)))
                                 (subseq w 0 (- (length w) 3)) w)))
                     (push (list w s e pos) out)
                     (when (string= w "2") (push (list "two" s e pos) out))
                     (incf pos))))
            (loop for i from 0 to (length text)
                  do (if (and (< i (length text)) (char/= (char text i) #\Space))
                         (unless start (setf start i))
                         (when start (word start i) (setf start nil))))
            (nreverse out)))))
    (s:execute db "CREATE VIRTUAL TABLE f USING fts5(a, tokenize='words stem')")
    (s:execute db "INSERT INTO f VALUES ('Running Dogs x 2'), ('the dog runs'), ('nothing here')")
    (is "fts5 user tokenizer: stem" (s:query db "SELECT rowid FROM f WHERE f MATCH 'runn'") '((1)))
    (is "fts5 user tokenizer: colocated" (s:query db "SELECT rowid FROM f WHERE f MATCH 'two'") '((1)))
    (is "fts5 user tokenizer: highlight" (s:query db "SELECT highlight(f, 0, '[', ']') FROM f WHERE f MATCH 'dogs'")
        '(("Running [Dogs] x 2")))
    (is "fts5 case-insensitive name" (progn (s:execute db "CREATE VIRTUAL TABLE g USING fts5(a, tokenize='WORDS')")
                                            (s:execute db "INSERT INTO g VALUES ('Hello World')")
                                            (s:query db "SELECT rowid FROM g WHERE g MATCH 'hello'"))
        '((1)))
    (is "fts5 porter wrapping it" (progn (s:execute db "CREATE VIRTUAL TABLE p USING fts5(a, tokenize='porter words')")
                                         (s:execute db "INSERT INTO p VALUES ('Connections connected')")
                                         (s:query db "SELECT rowid FROM p WHERE p MATCH 'connect'"))
        '((1)))
    (is "fts4 user tokenizer" (progn (s:execute db "CREATE VIRTUAL TABLE t USING fts4(a, tokenize=words stem)")
                                     (s:execute db "INSERT INTO t VALUES ('Running Dogs x 2'), ('the dog runs')")
                                     (list (s:query db "SELECT docid, offsets(t) FROM t WHERE t MATCH 'runn OR two'")
                                           (s:query db "SELECT snippet(t) FROM t WHERE t MATCH 'dogs'")))
        ;; (a token sharing its position and offsets repeats in snippets, as in SQLite)
        '(((1 "0 0 0 7 0 1 15 1")) (("Running <b>Dogs</b> x 22"))))
    (is "fts4 names are case-sensitive" (s:query db "CREATE VIRTUAL TABLE t2 USING fts4(a, tokenize=Words)")
        '(:error "SQLite error: unknown tokenizer: Words"))
    (is "fts5 unknown" (s:query db "CREATE VIRTUAL TABLE t3 USING fts5(a, tokenize='nope')")
        '(:error "SQLite error: no such tokenizer: nope"))
    (is "fts3tokenize" (progn (s:execute db "CREATE VIRTUAL TABLE tk USING fts3tokenize(words, stem)")
                              (s:query db "SELECT token, start, \"end\", position FROM tk WHERE input = 'Singing 2'"))
        '(("sing" 0 7 0) ("2" 8 9 1) ("two" 8 9 1)))
    (is "integrity" (s:query db "INSERT INTO t(t) VALUES ('integrity-check')") '())
    ;; an auxiliary function: phrase hits per row, and what the API reports
    (s:define-fts5-function db "hits"
      (lambda (api &optional (scale 1))
        (* scale (length (s:fts5-api-instances api)))))
    (s:define-fts5-function db "describe"
      (lambda (api)
        (format nil "~a|~a|~a|~a|~a|~a|~a|~{~a~^,~}"
                (s:fts5-api-rowid api) (s:fts5-api-column-count api) (s:fts5-api-column-text api 0)
                (s:fts5-api-column-size api 0) (s:fts5-api-row-count api)
                (s:fts5-api-column-total-size api 0) (s:fts5-api-phrase-count api)
                (mapcar #'first (s:fts5-api-tokenize api "Big Dog")))))
    (s:execute db "CREATE VIRTUAL TABLE h USING fts5(a, b)")
    (s:execute db "INSERT INTO h VALUES ('a b a', 'c a'), ('b', 'b b'), ('c', 'd')")
    (is "aux function" (s:query db "SELECT rowid, hits(h), hits(h, 10) FROM h WHERE h MATCH 'a OR b' ORDER BY hits(h) DESC")
        '((1 4 40) (2 3 30)))
    (is "aux API" (s:query db "SELECT describe(h) FROM h WHERE h MATCH 'c d'")
        '(("3|2|c|1|3|5|2|big,dog"))))
  (format t "api: ~d failed~%" *api-fails*)
  (zerop *api-fails*))

(defun compare-lisp (a b) (cond ((string< a b) -1) ((string> a b) 1) (t 0)))
