#!/usr/bin/env python3
"""Run every case in test/cases/*.test through the real SQLite (Python's
sqlite3) and write the answers as s-expressions for test/differential.lisp.

Case file format:   == case-name
                    SQL statements, one or more per case, ';'-terminated.
Each case runs on a fresh in-memory database."""
import sqlite3, sys, os, glob, math

here = os.path.dirname(os.path.abspath(__file__))

def lisp_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

def lisp_val(v):
    if v is None: return ':null'
    if isinstance(v, bool): return str(int(v))
    if isinstance(v, int): return str(v)
    if isinstance(v, float):
        if math.isinf(v): return ':inf' if v > 0 else ':-inf'
        if math.isnan(v): return ':null'
        return '(:f ' + lisp_str(repr(v)) + ')'
    if isinstance(v, str):
        try:
            v.encode('utf-8')
            return lisp_str(v)
        except UnicodeEncodeError:   # invalid UTF-8 from SQLite: send the bytes
            return '(:sx ' + lisp_str(v.encode('utf-8', 'surrogateescape').hex()) + ')'
    if isinstance(v, str): return lisp_str(v)
    if isinstance(v, (bytes, bytearray)): return '(:blob ' + lisp_str(v.hex()) + ')'
    raise TypeError(v)

def split_statements(text):
    out, cur = [], ''
    for line in text.splitlines(keepends=True):
        cur += line
        if sqlite3.complete_statement(cur):
            if cur.strip(): out.append(cur.strip())
            cur = ''
    if cur.strip(): out.append(cur.strip())
    return out

def parse_cases(path):
    cases, name, body = [], None, []
    for line in open(path, encoding='utf-8'):
        if line.startswith('== '):
            if name: cases.append((name, ''.join(body)))
            name, body = line[3:].strip(), []
        else:
            body.append(line)
    if name: cases.append((name, ''.join(body)))
    return cases

def run_case(sql):
    con = sqlite3.connect(':memory:', isolation_level=None)
    # invalid UTF-8 in TEXT values reads as U+FFFD, as sqlite-pure decodes it
    con.text_factory = lambda b: b.decode('utf-8', 'surrogateescape')
    results = []
    for st in split_statements(sql):
        try:
            cur = con.execute(st)
            rows = cur.fetchall()
            if cur.description is not None:
                cols = [d[0] for d in cur.description]
                results.append((st, 'rows', cols, rows))
            else:
                results.append((st, 'ok', None, None))
        except Exception as e:
            results.append((st, 'error', str(e), None))
    con.close()
    return results

def main():
    # gen-expected.py [CASE-GLOB OUTPUT]
    pattern = sys.argv[1] if len(sys.argv) > 2 else os.path.join(here, 'cases', '*.test')
    outpath = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, 'expected.sexp')
    out = open(outpath, 'w', encoding='utf-8')
    out.write(';; generated by gen-expected.py from SQLite %s -- do not edit\n' % sqlite3.sqlite_version)
    n = 0
    for path in sorted(glob.glob(pattern)):
        fname = os.path.basename(path)
        for name, sql in parse_cases(path):
            out.write('(%s\n' % lisp_str(fname + ':' + name))
            for st, kind, a, rows in run_case(sql):
                if kind == 'rows':
                    out.write(' (%s :rows (%s)\n  (%s))\n' % (
                        lisp_str(st), ' '.join(lisp_str(c) for c in a),
                        '\n   '.join('(' + ' '.join(lisp_val(v) for v in r) + ')' for r in rows)))
                elif kind == 'ok':
                    out.write(' (%s :ok)\n' % lisp_str(st))
                else:
                    out.write(' (%s :error %s)\n' % (lisp_str(st), lisp_str(a)))
            out.write(')\n')
            n += 1
    print('wrote %d cases' % n)

main()
