;;;; test/slt.lisp — a sqllogictest runner (https://sqlite.org/sqllogictest),
;;;; SQLite's engine-independent correctness suite, driving this library
;;;; directly.  Every expected result in the corpus came from SQLite; the
;;;; values are rendered exactly as the corpus's own SQLite driver
;;;; (slt_sqlite.c) renders them, and results are compared, sorted and
;;;; hashed exactly as sqllogictest.c does.

(defpackage #:sqlite-pure.slt
  (:use #:cl)
  (:export #:run-file #:run-files))

(in-package #:sqlite-pure.slt)

(defparameter *engine* "sqlite" "What skipif / onlyif lines are matched against.")

(defun md5-hex (strings)
  "MD5 of STRINGS each followed by a newline, as lowercase hex."
  (let ((st (make-string-output-stream)))
    (dolist (s strings) (write-string s st) (write-char #\Newline st))
    (format nil "~(~{~2,'0x~}~)"
            (coerce (sb-md5:md5sum-sequence (sqlite-pure::utf8-encode (get-output-stream-string st))) 'list))))

(defun c-int (v)
  "sqlite3_column_int: the 64-bit integer value, truncated to 32 bits."
  (let ((i (sqlite-pure::value-to-integer v)))
    (let ((low (ldb (byte 32 0) i))) (if (logbitp 31 low) (- low (expt 2 32)) low))))

(defun render (v type)
  "One value, as slt_sqlite.c's sqliteQuery produces it."
  (cond ((eq v :null) "NULL")
        ((char= type #\T)
         (let* ((octs (if (stringp v) (sqlite-pure::utf8-encode v) (sqlite-pure::value-to-blob v)))
                (z (position 0 octs))
                (octs (if z (subseq octs 0 z) octs)))
           (if (zerop (length octs))
               "(empty)"
               (map 'string (lambda (c) (if (or (< c 32) (> c 126)) #\@ (code-char c))) octs))))
        ((char= type #\I) (format nil "~d" (c-int v)))
        ((char= type #\R) (sqlite-pure::sql-printf "%.3f" (list (sqlite-pure::value-to-real v))))
        (t (error "unknown type character ~a" type))))

(defun split-words (line)
  (let ((out '()) (i 0) (n (length line)))
    (loop
      (loop while (and (< i n) (member (char line i) '(#\Space #\Tab))) do (incf i))
      (when (>= i n) (return (nreverse out)))
      (let ((j (or (position-if (lambda (c) (member c '(#\Space #\Tab))) line :start i) n)))
        (push (subseq line i j) out)
        (setf i j)))))

(defun read-records (path)
  "The file's records: lists of lines, comments dropped, blank-separated."
  (with-open-file (in path :external-format '(:utf-8 :replacement #\?))
    (let ((records '()) (cur '()) (lineno 0) (start 0))
      (loop for line = (read-line in nil nil)
            while line
            do (incf lineno)
               (let ((line (string-right-trim '(#\Return) line)))
                 (cond ((zerop (length (string-trim '(#\Space #\Tab) line)))
                        (when cur (push (cons start (nreverse cur)) records) (setf cur '())))
                       ((char= (char line 0) #\#))
                       (t (when (null cur) (setf start lineno)) (push line cur)))))
      (when cur (push (cons start (nreverse cur)) records))
      (nreverse records))))

(defstruct stats (records 0) (skipped 0) (ok 0) (failed 0) (known 0) (errors '()))

(defvar *known* '()
  "(file-suffix line reason): records where the corpus, generated by an
older SQLite, disagrees with SQLite 3.40 itself — test/slt-known.txt.")

(defun load-known (path)
  (when (probe-file path)
    (with-open-file (in path)
      (loop for line = (read-line in nil nil)
            while line
            unless (or (zerop (length line)) (char= (char line 0) #\#))
              collect (let* ((sp (position #\Space line))
                             (loc (subseq line 0 sp))
                             (colon (position #\: loc :from-end t)))
                        (list (subseq loc 0 colon) (parse-integer loc :start (1+ colon))
                              (string-trim " " (subseq line sp))))))))

(defun known-p (file line)
  (find-if (lambda (k) (and (= (second k) line)
                            (let ((s (first k)))
                              (and (>= (length file) (length s))
                                   (string= s file :start2 (- (length file) (length s)))))))
           *known*))

(defun fail (st file line fmt &rest args)
  (if (known-p file line)
      (incf (stats-known st))
      (progn
        (incf (stats-failed st))
        (when (< (length (stats-errors st)) 200)
          (push (format nil "~a:~d: ~?" file line fmt args) (stats-errors st))))))

(defun run-file (path &key (stats (make-stats)) (halt-after nil))
  "Run one .test file on a fresh in-memory database; returns STATS."
  (let ((db (sqlp:open-database ":memory:"))
        (threshold 8)
        (file (enough-namestring path)))
    (unwind-protect
         (dolist (rec (read-records path) stats)
           (destructuring-bind (line . lines) rec
             (let ((skip nil))
               ;; skipif / onlyif ENGINE
               (loop while (and lines (member (first (split-words (first lines))) '("skipif" "onlyif") :test #'string=))
                     do (destructuring-bind (kind eng &rest r) (split-words (pop lines))
                          (declare (ignore r))
                          (let ((match (string-equal eng *engine*)))
                            (when (if (string= kind "skipif") match (not match)) (setf skip t)))))
               (let* ((head (split-words (or (first lines) "")))
                      (kind (first head)))
                 (incf (stats-records stats))
                 (cond
                   ((null kind))
                   (skip (incf (stats-skipped stats)))
                   ((string= kind "halt") (return stats))
                   ((string= kind "hash-threshold") (setf threshold (parse-integer (second head))))
                   ((string= kind "statement")
                    (let ((sql (format nil "~{~a~^~%~}" (rest lines)))
                          (expect-ok (string= (second head) "ok")))
                      (let ((err (handler-case (progn (sqlp:execute-script db sql) nil)
                                   (sqlp:sqlite-error (c) (sqlp:sqlite-error-message c))
                                   (error (c) (format nil "LISP ERROR ~a" c)))))
                        (cond ((and expect-ok err)
                               (fail stats file line "statement failed: ~a~%    ~a" err sql))
                              ((and (not expect-ok) (null err))
                               (fail stats file line "statement succeeded, error expected~%    ~a" sql))
                              ((and err (search "LISP ERROR" err))
                               (fail stats file line "~a~%    ~a" err sql))
                              (t (incf (stats-ok stats)))))))
                   ((string= kind "query")
                    (let* ((types (second head))
                           (sort (or (third head) "nosort"))
                           (sep (position "----" (rest lines) :test #'string=))
                           (sql (format nil "~{~a~^~%~}" (subseq (rest lines) 0 sep)))
                           (expected (if sep (nthcdr (1+ sep) (rest lines)) '())))
                      (block q
                        (multiple-value-bind (rows cols)
                            (handler-case (sqlp:query db sql)
                              (sqlp:sqlite-error (c)
                                ;; slt_sqlite.c steps with while(step==ROW): an
                                ;; error while stepping just ends the result;
                                ;; only a prepare error fails the query
                                (if (sqlite-pure.shell::prepare-error-p (sqlp:sqlite-error-message c))
                                    (progn
                                      (fail stats file line "query failed: ~a~%    ~a" (sqlp:sqlite-error-message c) sql)
                                      (return-from q))
                                    (values '() (make-list (length types)))))
                              (error (c)
                                (fail stats file line "LISP ERROR ~a~%    ~a" c sql)
                                (return-from q)))
                          (unless (= (length cols) (length types))
                            (fail stats file line "wrong number of result columns: expected ~d but got ~d~%    ~a"
                                  (length types) (length cols) sql)
                            (return-from q))
                          (let* ((rendered (mapcar (lambda (r) (loop for v in r for ty across types collect (render v ty)))
                                                   rows))
                                 (values
                                   (cond ((string= sort "rowsort")
                                          (apply #'append
                                                 (sort rendered (lambda (a b)
                                                                  (loop for x in a for y in b
                                                                        do (cond ((string< x y) (return t))
                                                                                 ((string< y x) (return nil)))
                                                                        finally (return nil))))))
                                         ((string= sort "valuesort") (sort (apply #'append rendered) #'string<))
                                         (t (apply #'append rendered))))
                                 (n (length values)))
                            (if (and (plusp threshold) (> n threshold))
                                (let ((got (format nil "~d values hashing to ~a" n (md5-hex values))))
                                  (if (equal (first expected) got)
                                      (incf (stats-ok stats))
                                      (fail stats file line "wrong result hash: expected [~a] got [~a]~%    ~a"
                                            (first expected) got sql)))
                                (if (equal expected values)
                                    (incf (stats-ok stats))
                                    (fail stats file line "wrong result: expected ~s got ~s~%    ~a"
                                          (if (> (length expected) 12) (subseq expected 0 12) expected)
                                          (if (> (length values) 12) (subseq values 0 12) values) sql))))))))
                   (t (fail stats file line "unknown record type ~a" kind))))))
           (when (and halt-after (>= (stats-failed stats) halt-after)) (return stats)))
      (ignore-errors (sqlp:close-database db)))))

(defun run-files (paths &key (report t))
  "Run each file; print one summary line per file and return total stats."
  (let ((total (make-stats)))
    (dolist (p paths total)
      (let* ((t0 (get-internal-real-time))
             (st (handler-case (run-file p)
                   (error (c) (let ((s (make-stats))) (fail s p 0 "runner crashed: ~a" c) s))))
             (secs (/ (- (get-internal-real-time) t0) internal-time-units-per-second)))
        (when report
          (format t "~a ~a  ok ~d  failed ~d  skipped ~d~[~:;  known ~:*~d~]  (~,1fs)~%"
                  (if (zerop (stats-failed st)) "PASS" "FAIL") (enough-namestring p)
                  (stats-ok st) (stats-failed st) (stats-skipped st) (stats-known st) secs)
          (dolist (e (reverse (stats-errors st))) (format t "   ~a~%" e))
          (finish-output))
        (incf (stats-known total) (stats-known st))
        (incf (stats-ok total) (stats-ok st))
        (incf (stats-failed total) (stats-failed st))
        (incf (stats-skipped total) (stats-skipped st))))))
