;;;; btree-edit.lisp — writing b-trees the way SQLite 3.40's btree.c writes
;;;; them, so the same operations leave the same bytes on every page.
;;;;
;;;; A port, function for function, of the parts of btree.c that change
;;;; pages: cell space allocation within a page (freeblocks, fragments,
;;;; defragmentation), cell insertion and removal, overflow chains, the
;;;; freelist (allocateBtreePage / freePage2, with secure_delete), and the
;;;; balancing routines (balance_quick, balance_deeper, balance_nonroot and
;;;; its editPage / rebuildPage).  Pages are MPAGEs over the pager's own
;;;; page buffers; a cell is addressed as a buffer and an offset, so the
;;;; cells balance_nonroot collects keep pointing where C's pointers point
;;;; (into the old pages, the parent, or scratch space) and are moved with
;;;; the same memmove()s.

(in-package #:sqlite-pure)

(defconstant +ptf-intkey+ 1)
(defconstant +ptf-zerodata+ 2)
(defconstant +ptf-leafdata+ 4)
(defconstant +ptf-leaf+ 8)


(defmacro with-bt ((db) &body body)
  "Run BODY as one b-tree operation on DB (pages are cached for its length)."
  `(flet ((body () ,@body))
     (let ((d ,db))
       (if (and *mps* (eq *bt* d))
           (body)
           (let ((*bt* d) (*mps* (make-hash-table)))
             (body))))))

(defun bt-usable () (db-usable-size *bt*))
(defun bt-secure () (db-secure-delete *bt*))
(defun bt-fast-secure () (and (db-secure-delete *bt*) t))

;;; ------------------------------------------------------------------
;;; Pages

(defstruct (mpage (:conc-name mp-))
  pgno data (hdr 0)
  leaf intkey intkey-leaf (cps 0) (cell-offset 0) (ncell 0) (nfree -1)
  (max-local 0) (min-local 0)
  (ovfl-cells (make-array 4 :initial-element nil))   ; apOvfl: (buffer . offset), 4 bytes of room before
  (ovfl-idx (make-array 4 :initial-element 0))       ; aiOvfl
  (novfl 0))

(defun decode-page-flags (p flags)
  (let ((leaf (logbitp 3 flags)) (f (logandc2 flags +ptf-leaf+)) (u (bt-usable)))
    (setf (mp-leaf p) leaf (mp-cps p) (if leaf 0 4))
    (cond ((= f (logior +ptf-leafdata+ +ptf-intkey+))
           (setf (mp-intkey p) t (mp-intkey-leaf p) leaf
                 (mp-max-local p) (- u 35) (mp-min-local p) (- (floor (* (- u 12) 32) 255) 23)))
          ((= f +ptf-zerodata+)
           (setf (mp-intkey p) nil (mp-intkey-leaf p) nil
                 (mp-max-local p) (- (floor (* (- u 12) 64) 255) 23)
                 (mp-min-local p) (- (floor (* (- u 12) 32) 255) 23)))
          (t (corrupt "page ~d has invalid b-tree page type ~d" (mp-pgno p) flags)))))

(defun mp-init (p)
  "btreeInitPage."
  (let* ((d (mp-data p)) (h (mp-hdr p)))
    (decode-page-flags p (aref d h))
    (setf (mp-novfl p) 0
          (mp-cell-offset p) (+ h 8 (mp-cps p))
          (mp-ncell p) (get-u16 d (+ h 3))
          (mp-nfree p) -1)
    p))

(defun get-mp (pgno)
  "getAndInitPage: the MPAGE for PGNO.  Its buffer is the writable one, but
the page counts as changed only once TOUCHed (sqlite3PagerWrite): a
transaction that only looked at pages commits nothing."
  (or (gethash pgno *mps*)
      (let* ((dirty (db-dirty *bt*)) (was (gethash pgno dirty))
             (p (make-mpage :pgno pgno :data (page-for-write *bt* pgno) :hdr (if (= pgno 1) 100 0))))
        (unless was (remhash pgno dirty))
        (mp-init p)
        (setf (gethash pgno *mps*) p))))

(declaim (inline touch))
(defun touch (p)
  "sqlite3PagerWrite: P is being changed."
  (setf (gethash (mp-pgno p) (db-dirty *bt*)) t))

(defun new-mp (pgno)
  "An MPAGE for a page just allocated (content as it is; zeroPage follows)."
  (let ((p (make-mpage :pgno pgno :data (page-for-write *bt* pgno) :hdr (if (= pgno 1) 100 0))))
    (setf (gethash pgno *mps*) p)))

(defun mp-compute-free (p)
  "btreeComputeFreeSpace."
  (let* ((d (mp-data p)) (h (mp-hdr p)) (usable (bt-usable))
         (top (let ((v (get-u16 d (+ h 5)))) (if (zerop v) 65536 v)))
         (first (+ h 8 (mp-cps p) (* 2 (mp-ncell p))))
         (last (- usable 4))
         (pc (get-u16 d (+ h 1)))
         (nfree (+ (aref d (+ h 7)) top)))
    (when (plusp pc)
      (when (< pc top) (corrupt "free block before content on page ~d" (mp-pgno p)))
      (let (next size)
        (loop
          (when (> pc last) (corrupt "free block past end of page ~d" (mp-pgno p)))
          (setf next (get-u16 d pc) size (get-u16 d (+ pc 2)))
          (incf nfree size)
          (when (<= next (+ pc size 3)) (return))
          (setf pc next))
        (when (plusp next) (corrupt "free block list out of order on page ~d" (mp-pgno p)))
        (when (> (+ pc size) usable) (corrupt "free block past end of page ~d" (mp-pgno p)))))
    (when (or (> nfree usable) (< nfree first)) (corrupt "free space miscounted on page ~d" (mp-pgno p)))
    (setf (mp-nfree p) (- nfree first))))

(defun mp-ensure-free (p)
  (when (< (mp-nfree p) 0) (mp-compute-free p))
  (mp-nfree p))

(defun zero-page (p flags)
  "zeroPage."
  (touch p)
  (let* ((d (mp-data p)) (h (mp-hdr p)) (usable (bt-usable))
         (first (+ h (if (logbitp 3 flags) 8 12))))
    (when (bt-fast-secure) (fill d 0 :start h :end usable))
    (setf (aref d h) flags)
    (fill d 0 :start (1+ h) :end (+ h 5))
    (setf (aref d (+ h 7)) 0)
    (put-u16 d (+ h 5) (if (= usable 65536) 0 usable))
    (setf (mp-nfree p) (- usable first))
    (decode-page-flags p flags)
    (setf (mp-cell-offset p) first (mp-novfl p) 0 (mp-ncell p) 0)
    p))

(declaim (inline find-cell))
(defun find-cell (p i)
  (get-u16 (mp-data p) (+ (mp-cell-offset p) (* 2 i))))

;;; Cells.  A cell is (buffer, offset); these parse one as btree.c does.

(defun varint32-at (b o)
  "getVarint32 as the cell-size functions read it: (values value next-offset)."
  (let ((n (aref b o)))
    (if (< n #x80)
        (values n (1+ o))
        (let ((v (logand n #x7f)) (i o) (end (+ o 8)))
          (loop do (incf i)
                   (setf v (logand #xffffffff (logior (ash v 7) (logand (aref b i) #x7f))))
                while (and (>= (aref b i) #x80) (< i end)))
          (values v (1+ i))))))

(defun payload-to-local (p npayload)
  (if (<= npayload (mp-max-local p))
      npayload
      (let* ((mn (mp-min-local p))
             (surplus (+ mn (mod (- npayload mn) (- (bt-usable) 4)))))
        (if (<= surplus (mp-max-local p)) surplus mn))))

(defun cell-size-at (p b o)
  "xCellSize for P's kind of page."
  (cond ((and (mp-intkey p) (not (mp-leaf p)))          ; cellSizePtrNoPayload
         (let ((i (+ o 4)) (end (+ o 13)))
           (loop do (incf i) while (and (>= (aref b (1- i)) #x80) (< i end)))
           (- i o)))
        (t
         (multiple-value-bind (nsize it) (varint32-at b (+ o (mp-cps p)))
           (when (mp-intkey p)                           ; cellSizePtrTableLeaf: skip the key
             (let ((end (+ it 9)))
               (loop do (incf it) while (and (>= (aref b (1- it)) #x80) (< it end)))))
           (if (<= nsize (mp-max-local p))
               (max 4 (+ nsize (- it o)))
               (let* ((mn (mp-min-local p))
                      (n (+ mn (mod (- nsize mn) (- (bt-usable) 4)))))
                 (when (> n (mp-max-local p)) (setf n mn))
                 (+ n 4 (- it o))))))))

(defun parse-cell (p b o)
  "xParseCell: (values nkey npayload nlocal nsize payload-offset)."
  (cond ((and (mp-intkey p) (not (mp-leaf p)))
         (multiple-value-bind (key n) (get-varint b (+ o 4))
           (values (if (logbitp 63 key) (- key (expt 2 64)) key) 0 0 (+ 4 n) (+ o 4))))
        (t
         (multiple-value-bind (npayload it) (varint32-at b (+ o (mp-cps p)))
           (let ((nkey npayload))
             (when (mp-intkey p)
               (multiple-value-bind (k n) (get-varint b it)
                 (setf nkey (if (logbitp 63 k) (- k (expt 2 64)) k))
                 (incf it n)))
             (let ((local (payload-to-local p npayload)))
               (values nkey npayload local
                       (if (= local npayload) (max 4 (+ npayload (- it o))) (+ local 4 (- it o)))
                       it)))))))

;;; ------------------------------------------------------------------
;;; Space within a page

(defun defragment-page (p max-frag)
  "defragmentPage."
  (touch p)
  (let* ((d (mp-data p)) (h (mp-hdr p)) (co (mp-cell-offset p)) (n (mp-ncell p))
         (first (+ co (* 2 n))) (usable (bt-usable)) (cbrk 0))
    (block quick
      (when (<= (aref d (+ h 7)) max-frag)
        (let ((ifree (get-u16 d (+ h 1))))
          (when (> ifree (- usable 4)) (corrupt "bad free block on page ~d" (mp-pgno p)))
          (when (plusp ifree)
            (let ((ifree2 (get-u16 d ifree)))
              (when (> ifree2 (- usable 4)) (corrupt "bad free block on page ~d" (mp-pgno p)))
              (when (or (zerop ifree2) (and (zerop (aref d ifree2)) (zerop (aref d (1+ ifree2)))))
                (let ((sz (get-u16 d (+ ifree 2))) (sz2 0) (top (get-u16 d (+ h 5))))
                  (when (>= top ifree) (corrupt "bad free block on page ~d" (mp-pgno p)))
                  (if (plusp ifree2)
                      (progn
                        (when (> (+ ifree sz) ifree2) (corrupt "bad free block on page ~d" (mp-pgno p)))
                        (setf sz2 (get-u16 d (+ ifree2 2)))
                        (when (> (+ ifree2 sz2) usable) (corrupt "bad free block on page ~d" (mp-pgno p)))
                        (replace d d :start1 (+ ifree sz sz2) :start2 (+ ifree sz) :end2 ifree2)
                        (incf sz sz2))
                      (when (> (+ ifree sz) usable) (corrupt "bad free block on page ~d" (mp-pgno p))))
                  (setf cbrk (+ top sz))
                  (replace d d :start1 cbrk :start2 top :end2 ifree)
                  (loop for a from co below first by 2
                        do (let ((pc (get-u16 d a)))
                             (cond ((< pc ifree) (put-u16 d a (+ pc sz)))
                                   ((< pc ifree2) (put-u16 d a (+ pc sz2))))))
                  (return-from quick)))))))
      ;; the general case: pack every cell against the end of the page
      (setf cbrk usable)
      (let ((start (get-u16 d (+ h 5))))
        (when (plusp n)
          (let ((tmp (copy-seq d)))
            (dotimes (i n)
              (let* ((a (+ co (* 2 i))) (pc (get-u16 d a)))
                (when (or (< pc start) (> pc (- usable 4))) (corrupt "bad cell pointer on page ~d" (mp-pgno p)))
                (let ((size (cell-size-at p tmp pc)))
                  (decf cbrk size)
                  (when (or (< cbrk start) (> (+ pc size) usable)) (corrupt "bad cell on page ~d" (mp-pgno p)))
                  (put-u16 d a cbrk)
                  (replace d tmp :start1 cbrk :start2 pc :end2 (+ pc size))))))))
      (setf (aref d (+ h 7)) 0))
    (unless (= (+ (aref d (+ h 7)) (- cbrk first)) (mp-nfree p))
      (corrupt "free space miscounted on page ~d" (mp-pgno p)))
    (put-u16 d (+ h 5) cbrk)
    (setf (aref d (+ h 1)) 0 (aref d (+ h 2)) 0)
    (fill d 0 :start first :end cbrk)))

(defun page-find-slot (p nbyte)
  "pageFindSlot: the offset of a slot of NBYTE from the freeblock list, or NIL."
  (let* ((d (mp-data p)) (h (mp-hdr p)) (iaddr (+ h 1)) (pc (get-u16 d iaddr))
         (maxpc (- (bt-usable) nbyte)))
    (loop while (<= pc maxpc)
          do (let* ((size (get-u16 d (+ pc 2))) (x (- size nbyte)))
               (when (>= x 0)
                 (cond ((< x 4)
                        (when (> (aref d (+ h 7)) 57) (return-from page-find-slot nil))
                        (replace d d :start1 iaddr :start2 pc :end2 (+ pc 2))
                        (incf (aref d (+ h 7)) x)
                        (return-from page-find-slot pc))
                       ((> (+ x pc) maxpc) (corrupt "bad free block on page ~d" (mp-pgno p)))
                       (t (put-u16 d (+ pc 2) x)))
                 (return-from page-find-slot (+ pc x)))
               (setf iaddr pc pc (get-u16 d pc))
               (when (<= pc iaddr)
                 (when (plusp pc) (corrupt "free block list out of order on page ~d" (mp-pgno p)))
                 (return-from page-find-slot nil))))
    (when (> pc (+ maxpc nbyte -4)) (corrupt "bad free block on page ~d" (mp-pgno p)))
    nil))

(defun allocate-space (p nbyte)
  "allocateSpace: the offset of NBYTE newly allocated in P's content area."
  (touch p)
  (let* ((d (mp-data p)) (h (mp-hdr p))
         (gap (+ (mp-cell-offset p) (* 2 (mp-ncell p))))
         (top (get-u16 d (+ h 5))))
    (when (> gap top)
      (if (and (zerop top) (= (bt-usable) 65536))
          (setf top 65536)
          (corrupt "cell content area overlaps pointers on page ~d" (mp-pgno p))))
    (when (and (or (plusp (aref d (+ h 2))) (plusp (aref d (+ h 1)))) (<= (+ gap 2) top))
      (let ((slot (page-find-slot p nbyte)))
        (when slot
          (when (<= slot gap) (corrupt "free block overlaps pointers on page ~d" (mp-pgno p)))
          (return-from allocate-space slot))))
    (when (> (+ gap 2 nbyte) top)
      (defragment-page p (min 4 (- (mp-nfree p) (+ 2 nbyte))))
      (setf top (let ((v (get-u16 d (+ h 5)))) (if (zerop v) 65536 v))))
    (decf top nbyte)
    (put-u16 d (+ h 5) top)
    top))

(defun free-space (p start size)
  "freeSpace: return START..START+SIZE to the freeblock list."
  (touch p)
  (let* ((d (mp-data p)) (h (mp-hdr p)) (iptr (+ h 1)) (ifreeblk 0) (nfrag 0)
         (orig size) (end (+ start size)) (usable (bt-usable)))
    (unless (and (zerop (aref d (1+ iptr))) (zerop (aref d iptr)))
      (loop (setf ifreeblk (get-u16 d iptr))
            (unless (< ifreeblk start) (return))
            (when (<= ifreeblk iptr)
              (when (zerop ifreeblk) (return))
              (corrupt "free block list out of order on page ~d" (mp-pgno p)))
            (setf iptr ifreeblk))
      (when (> ifreeblk (- usable 4)) (corrupt "bad free block on page ~d" (mp-pgno p)))
      (when (and (plusp ifreeblk) (>= (+ end 3) ifreeblk))
        (setf nfrag (- ifreeblk end))
        (when (> end ifreeblk) (corrupt "overlapping free blocks on page ~d" (mp-pgno p)))
        (setf end (+ ifreeblk (get-u16 d (+ ifreeblk 2))))
        (when (> end usable) (corrupt "bad free block on page ~d" (mp-pgno p)))
        (setf size (- end start) ifreeblk (get-u16 d ifreeblk)))
      (when (> iptr (+ h 1))
        (let ((ptr-end (+ iptr (get-u16 d (+ iptr 2)))))
          (when (>= (+ ptr-end 3) start)
            (when (> ptr-end start) (corrupt "overlapping free blocks on page ~d" (mp-pgno p)))
            (incf nfrag (- start ptr-end))
            (setf size (- end iptr) start iptr))))
      (when (> nfrag (aref d (+ h 7))) (corrupt "fragment count wrong on page ~d" (mp-pgno p)))
      (decf (aref d (+ h 7)) nfrag))
    (let ((x (get-u16 d (+ h 5))))
      (if (<= start x)
          (progn
            (when (< start x) (corrupt "free block before content on page ~d" (mp-pgno p)))
            (unless (= iptr (+ h 1)) (corrupt "free block list out of order on page ~d" (mp-pgno p)))
            (put-u16 d (+ h 1) ifreeblk)
            (put-u16 d (+ h 5) end))
          (put-u16 d iptr start)))
    (when (bt-fast-secure) (fill d 0 :start start :end (+ start size)))
    (put-u16 d start ifreeblk)
    (put-u16 d (+ start 2) size)
    (incf (mp-nfree p) orig)))

(defun drop-cell (p idx sz)
  "dropCell."
  (touch p)
  (let* ((d (mp-data p)) (h (mp-hdr p)) (ptr (+ (mp-cell-offset p) (* 2 idx)))
         (pc (get-u16 d ptr)))
    (when (> (+ pc sz) (bt-usable)) (corrupt "cell past end of page ~d" (mp-pgno p)))
    (free-space p pc sz)
    (decf (mp-ncell p))
    (if (zerop (mp-ncell p))
        (progn (fill d 0 :start (+ h 1) :end (+ h 5))
               (setf (aref d (+ h 7)) 0)
               (put-u16 d (+ h 5) (if (= (bt-usable) 65536) 0 (bt-usable)))
               (setf (mp-nfree p) (- (bt-usable) h (mp-cps p) 8)))
        (progn (replace d d :start1 ptr :start2 (+ ptr 2) :end2 (+ ptr 2 (* 2 (- (mp-ncell p) idx))))
               (put-u16 d (+ h 3) (mp-ncell p))
               (incf (mp-nfree p) 2)))))

(defun insert-cell (p i cb co sz &optional child)
  "insertCell: the cell at CB[CO..CO+SZ] becomes cell I of P (its first four
bytes replaced by CHILD if given), or an overflow cell if P is full."
  (if (or (plusp (mp-novfl p)) (> (+ sz 2) (mp-ensure-free p)))
      ;; (kept with four bytes before it: balance_nonroot may look at pCell-4)
      (let ((cell (make-octets (+ sz 4))) (j (mp-novfl p)))
        (replace cell cb :start1 4 :start2 co :end2 (+ co sz))
        (when child (put-u32 cell 4 child))
        (setf (aref (mp-ovfl-cells p) j) (cons cell 4) (aref (mp-ovfl-idx p) j) i)
        (incf (mp-novfl p)))
      (let* ((d (mp-data p)) (idx (progn (touch p) (allocate-space p sz))))
        (decf (mp-nfree p) (+ 2 sz))
        (if child
            (progn (replace d cb :start1 (+ idx 4) :start2 (+ co 4) :end2 (+ co sz))
                   (put-u32 d idx child))
            (replace d cb :start1 idx :start2 co :end2 (+ co sz)))
        (let ((ins (+ (mp-cell-offset p) (* 2 i))))
          (replace d d :start1 (+ ins 2) :start2 ins :end2 (+ ins (* 2 (- (mp-ncell p) i))))
          (put-u16 d ins idx))
        (incf (mp-ncell p))
        (let ((h (mp-hdr p)))
          (when (zerop (setf (aref d (+ h 4)) (logand (1+ (aref d (+ h 4))) #xff)))
            (setf (aref d (+ h 3)) (logand (1+ (aref d (+ h 3))) #xff))))
        (when (autovacuum-p *bt*) (ptrmap-put-ovfl-ptr p p d idx)))))

;;; ------------------------------------------------------------------
;;; Pointer maps (auto-vacuum)

(defun ptrmap-put-ovfl-ptr (p src b o)
  "ptrmapPutOvflPtr: the overflow chain of the cell at B[O] belongs to P."
  (declare (ignore src))
  (multiple-value-bind (nkey npayload nlocal nsize) (parse-cell p b o)
    (declare (ignore nkey))
    (when (< nlocal npayload)
      (ptrmap-put *bt* (get-u32 b (+ o nsize -4)) +ptrmap-overflow1+ (mp-pgno p)))))

(defun set-child-ptrmaps (p)
  (when (autovacuum-p *bt*)
    (let ((d (mp-data p)))
      (dotimes (i (mp-ncell p))
        (let ((o (find-cell p i)))
          (ptrmap-put-ovfl-ptr p p d o)
          (unless (mp-leaf p) (ptrmap-put *bt* (get-u32 d o) +ptrmap-btree+ (mp-pgno p)))))
      (unless (mp-leaf p)
        (ptrmap-put *bt* (get-u32 d (+ (mp-hdr p) 8)) +ptrmap-btree+ (mp-pgno p))))))

;;; ------------------------------------------------------------------
;;; The freelist

(defun page-has-content-p (pgno)
  (gethash pgno (db-freed-in-txn *bt*)))

(defun allocate-btree-page (nearby &optional (mode :any))
  "allocateBtreePage: a page number, taken from the freelist (the leaf
nearest NEARBY; :EXACT and :LE for auto-vacuum) or from the end of the file.
The page is writable; its content is what SQLite's would be (a reused trunk
keeps its bytes, anything else is zero)."
  (let* ((db *bt*) (p1 (page-for-write db 1)) (mx (db-page-count db))
         (n (get-u32 p1 36)) (result nil))
    (flet ((unused (pg zero-p)
             (let ((b (page-for-write db pg)))
               (when zero-p (fill b 0))
               (remhash pg *mps*)
               pg)))
      (cond
        ((plusp n)
         (when (>= n mx) (corrupt "freelist count ~d too large" n))
         (let ((search (or (eq mode :le)
                           (and (eq mode :exact) (<= nearby mx)
                                (= (ptrmap-get db nearby) +ptrmap-free+))))
               (nsearch 0) (prev nil) (trunk nil))
           (put-u32 p1 36 (1- n))
           (loop
             (setf prev trunk)
             (let ((itrunk (if prev (get-u32 (page-for-write db prev) 0) (get-u32 p1 32))))
               (when (or (> itrunk mx) (> (incf nsearch) (1+ n)))
                 (corrupt "freelist trunk ~d out of range" itrunk))
               (setf trunk itrunk)
               (let* ((tb (page-for-write db itrunk)) (k (get-u32 tb 4)))
                 (cond
                   ((and (zerop k) (not search))
                    (replace p1 tb :start1 32 :start2 0 :end2 4)
                    (setf result (unused itrunk nil)))
                   ((> k (- (floor (bt-usable) 4) 2)) (corrupt "freelist trunk ~d overfull" itrunk))
                   ((and search (or (= nearby itrunk) (and (< itrunk nearby) (eq mode :le))))
                    (setf result (unused itrunk nil) search nil)
                    (if (zerop k)
                        (if (null prev)
                            (replace p1 tb :start1 32 :start2 0 :end2 4)
                            (replace (page-for-write db prev) tb :start1 0 :start2 0 :end2 4))
                        (let* ((inew (get-u32 tb 8)) (nb (page-for-write db inew)))
                          (when (> inew mx) (corrupt "freelist leaf ~d out of range" inew))
                          (replace nb tb :start1 0 :start2 0 :end2 4)
                          (put-u32 nb 4 (1- k))
                          (replace nb tb :start1 8 :start2 12 :end2 (+ 12 (* 4 (1- k))))
                          (if (null prev)
                              (put-u32 p1 32 inew)
                              (put-u32 (page-for-write db prev) 0 inew)))))
                   ((plusp k)
                    (let ((closest 0))
                      (when (plusp nearby)
                        (if (eq mode :le)
                            (loop for i below k
                                  when (<= (get-u32 tb (+ 8 (* i 4))) nearby) do (setf closest i) (return))
                            (let ((dist (abs (- (get-u32 tb 8) nearby))))
                              (loop for i from 1 below k
                                    do (let ((d2 (abs (- (get-u32 tb (+ 8 (* i 4))) nearby))))
                                         (when (< d2 dist) (setf closest i dist d2)))))))
                      (let ((ipage (get-u32 tb (+ 8 (* closest 4)))))
                        (when (or (> ipage mx) (< ipage 2)) (corrupt "freelist leaf ~d out of range" ipage))
                        (when (or (not search) (= ipage nearby) (and (< ipage nearby) (eq mode :le)))
                          (when (< closest (1- k))
                            (replace tb tb :start1 (+ 8 (* closest 4)) :start2 (+ 4 (* k 4)) :end2 (+ 8 (* k 4))))
                          (put-u32 tb 4 (1- k))
                          (setf result (unused ipage (not (page-has-content-p ipage))) search nil))))))))
             (unless search (return)))))
        (t
         (let ((np (1+ mx)))
           (when (= np (pending-byte-page db)) (incf np))
           (when (and (autovacuum-p db) (ptrmap-page-p db np))
             (setf (db-page-count db) np)
             (fill (page-for-write db np) 0)
             (incf np)
             (when (= np (pending-byte-page db)) (incf np)))
           (setf (db-page-count db) np)
           (put-u32 p1 28 np)
           (setf result (unused np t))))))
    result))

(defun free-btree-page (pgno)
  "freePage2: put PGNO on the freelist (zeroed first under secure_delete)."
  (let* ((db *bt*) (p1 (page-for-write db 1)) (nfree (get-u32 p1 36)))
    (when (or (< pgno 2) (> pgno (db-page-count db))) (corrupt "freeing page ~d out of range" pgno))
    (remhash pgno *mps*)
    (put-u32 p1 36 (1+ nfree))
    (when (eq (db-secure-delete db) t)
      (fill (page-for-write db pgno) 0))
    (ptrmap-put db pgno +ptrmap-free+ 0)
    (block nil
      (when (plusp nfree)
        (let* ((itrunk (get-u32 p1 32)) (tb (page-for-write db itrunk)) (nleaf (get-u32 tb 4)))
          (when (> itrunk (db-page-count db)) (corrupt "freelist trunk ~d out of range" itrunk))
          (when (> nleaf (- (floor (bt-usable) 4) 2)) (corrupt "freelist trunk ~d overfull" itrunk))
          (when (< nleaf (- (floor (bt-usable) 4) 8))
            (put-u32 tb 4 (1+ nleaf))
            (put-u32 tb (+ 8 (* nleaf 4)) pgno)
            (setf (gethash pgno (db-freed-in-txn db)) t)
            (return))))
      (let ((b (page-for-write db pgno)))
        (put-u32 b 0 (if (plusp nfree) (get-u32 p1 32) 0))
        (put-u32 b 4 0)
        (put-u32 p1 32 pgno)))))

(defun clear-cell-overflow (p b o)
  "BTREE_CLEAR_CELL: free the overflow chain of the cell at B[O]."
  (multiple-value-bind (nkey npayload nlocal nsize) (parse-cell p b o)
    (declare (ignore nkey))
    (when (/= nlocal npayload)
      (let* ((ovfl (get-u32 b (+ o nsize -4)))
             (size (- (bt-usable) 4))
             (count (floor (+ (- npayload nlocal) size -1) size)))
        (loop repeat count
              for left downfrom (1- count)
              do (when (or (< ovfl 2) (> ovfl (db-page-count *bt*))) (corrupt "overflow page ~d out of range" ovfl))
                 (let ((next (if (plusp left) (get-u32 (read-page *bt* ovfl) 0) 0)))
                   (free-btree-page ovfl)
                   (setf ovfl next)))))
    (values nsize npayload nlocal)))

(defun fill-in-cell (p key payload)
  "fillInCell: the cell for KEY (a rowid, for a table) and PAYLOAD, with its
overflow chain written; returns the cell octets."
  (let* ((npayload (length payload))
         (hdr (make-octets 20))
         (nheader (mp-cps p)))
    (incf nheader (put-varint hdr nheader npayload))
    (when (mp-intkey p) (incf nheader (put-varint hdr nheader (ldb (byte 64 0) key))))
    (if (<= npayload (mp-max-local p))
        (let ((cell (make-octets (max 4 (+ nheader npayload)))))
          (replace cell hdr :end2 nheader)
          (replace cell payload :start1 nheader)
          cell)
        (let* ((mn (mp-min-local p))
               (n (let ((x (+ mn (mod (- npayload mn) (- (bt-usable) 4))))) (if (> x (mp-max-local p)) mn x)))
               (cell (make-octets (+ n nheader 4)))
               (av (autovacuum-p *bt*))
               (prior-buf cell) (prior-off (+ nheader n))
               (dst cell) (dst-off nheader) (space n) (src 0) (left npayload) (pgno-ovfl 0))
          (replace cell hdr :end2 nheader)
          (loop
            (let ((k (min left space)))
              (replace dst payload :start1 dst-off :start2 src :end2 (+ src k))
              (decf left k)
              (when (<= left 0) (return))
              (incf dst-off k) (incf src k) (decf space k)
              (when (zerop space)
                (let ((ptrmap-parent pgno-ovfl))
                  (when av
                    (loop do (incf pgno-ovfl)
                          while (or (ptrmap-page-p *bt* pgno-ovfl) (= pgno-ovfl (pending-byte-page *bt*)))))
                  (setf pgno-ovfl (allocate-btree-page pgno-ovfl))
                  (when av
                    (ptrmap-put *bt* pgno-ovfl (if (plusp ptrmap-parent) +ptrmap-overflow2+ +ptrmap-overflow1+)
                                ptrmap-parent))
                  (put-u32 prior-buf prior-off pgno-ovfl)
                  (let ((ob (page-for-write *bt* pgno-ovfl)))
                    (setf prior-buf ob prior-off 0)
                    (put-u32 ob 0 0)
                    (setf dst ob dst-off 4 space (- (bt-usable) 4)))))))
          cell))))

;;; ------------------------------------------------------------------
;;; Balancing.  A CELL-REF is (buffer . offset).

(defstruct (cell-array (:conc-name ca-)) (n 0) ref cells sizes)

(defun ca-size (ca i)
  (let ((s (aref (ca-sizes ca) i)))
    (if (plusp s) s
        (let ((c (aref (ca-cells ca) i)))
          (setf (aref (ca-sizes ca) i) (cell-size-at (ca-ref ca) (car c) (cdr c)))))))

(defun populate-cell-cache (ca idx n)
  (loop repeat n for i from idx do (ca-size ca i)))

(defun rebuild-page (ca first n p)
  "rebuildPage."
  (touch p)
  (let* ((d (mp-data p)) (h (mp-hdr p)) (usable (bt-usable))
         (cellptr (mp-cell-offset p))
         (j (let ((v (get-u16 d (+ h 5)))) (if (> v usable) 0 v)))
         (tmp (copy-seq d))
         (pdata usable))
    (loop for i from first below (+ first n)
          do (let* ((c (aref (ca-cells ca) i)) (sz (aref (ca-sizes ca) i))
                    (cb (car c)) (co (cdr c)))
               (when (and (eq cb d) (<= j co) (< co usable))
                 (when (> (+ co sz) usable) (corrupt "cell past end of page ~d" (mp-pgno p)))
                 (setf cb tmp))
               (decf pdata sz)
               (put-u16 d cellptr pdata)
               (incf cellptr 2)
               (when (< pdata cellptr) (corrupt "page ~d overfull in rebuild" (mp-pgno p)))
               (replace d cb :start1 pdata :start2 co :end2 (+ co sz))))
    (setf (mp-ncell p) n (mp-novfl p) 0)
    (put-u16 d (+ h 1) 0)
    (put-u16 d (+ h 3) n)
    (put-u16 d (+ h 5) pdata)
    (setf (aref d (+ h 7)) 0)))

(defun page-insert-array (p begin pdata cellptr first n ca)
  "pageInsertArray: (values new-pdata ok)."
  (let ((d (mp-data p)))
    (loop for i from first below (+ first n)
          do (let* ((sz (aref (ca-sizes ca) i))
                    (slot (and (not (and (zerop (aref d 1)) (zerop (aref d 2))))
                               (page-find-slot p sz))))
               (unless slot
                 (when (< (- pdata begin) sz) (return-from page-insert-array (values pdata nil)))
                 (decf pdata sz)
                 (setf slot pdata))
               (let ((c (aref (ca-cells ca) i)))
                 (replace d (car c) :start1 slot :start2 (cdr c) :end2 (+ (cdr c) sz)))
               (put-u16 d cellptr slot)
               (incf cellptr 2)))
    (values pdata t)))

(defun page-free-array (p first n ca)
  "pageFreeArray: free the cells FIRST..FIRST+N-1 that live on P; their count."
  (let* ((d (mp-data p)) (usable (bt-usable)) (start (+ (mp-hdr p) 8 (mp-cps p)))
         (nret 0) (free-at nil) (free-size 0))
    (loop for i from first below (+ first n)
          do (let ((c (aref (ca-cells ca) i)))
               (when (and (eq (car c) d) (<= start (cdr c)) (< (cdr c) usable))
                 (let ((sz (aref (ca-sizes ca) i)) (at (cdr c)))
                   (if (not (eql free-at (+ at sz)))
                       (progn
                         (when free-at (free-space p free-at free-size))
                         (setf free-at at free-size sz)
                         (when (> (+ at sz) usable) (return-from page-free-array 0)))
                       (setf free-at at free-size (+ free-size sz)))
                   (incf nret)))))
    (when free-at (free-space p free-at free-size))
    nret))

(defun edit-page (p iold inew nnew ca)
  "editPage: make P hold cells INEW..INEW+NNEW-1 of CA, given that it holds
IOLD.. now, moving as few as possible."
  (touch p)
  (let* ((d (mp-data p)) (h (mp-hdr p)) (co (mp-cell-offset p))
         (begin (+ co (* nnew 2)))
         (ncell (mp-ncell p))
         (iold-end (+ iold (mp-ncell p) (mp-novfl p)))
         (inew-end (+ inew nnew)))
    (block edit
      (when (< iold inew)
        (let ((nshift (page-free-array p iold (- inew iold) ca)))
          (when (> nshift ncell) (corrupt "page ~d miscounted in balance" (mp-pgno p)))
          (replace d d :start1 co :start2 (+ co (* nshift 2)) :end2 (+ co (* nshift 2) (* ncell 2)))
          (decf ncell nshift)))
      (when (< inew-end iold-end)
        (decf ncell (page-free-array p inew-end (- iold-end inew-end) ca)))
      (let ((pdata (let ((v (get-u16 d (+ h 5)))) (if (zerop v) 65536 v))))
        (when (or (< pdata begin) (> pdata (db-page-size *bt*))) (return-from edit))
        (when (< inew iold)
          (let ((nadd (min nnew (- iold inew))))
            (replace d d :start1 (+ co (* nadd 2)) :start2 co :end2 (+ co (* ncell 2)))
            (multiple-value-bind (pd ok) (page-insert-array p begin pdata co inew nadd ca)
              (unless ok (return-from edit))
              (setf pdata pd))
            (incf ncell nadd)))
        (dotimes (i (mp-novfl p))
          (let ((icell (- (+ iold (aref (mp-ovfl-idx p) i)) inew)))
            (when (and (>= icell 0) (< icell nnew))
              (let ((cp (+ co (* icell 2))))
                (when (> ncell icell)
                  (replace d d :start1 (+ cp 2) :start2 cp :end2 (+ cp (* 2 (- ncell icell)))))
                (incf ncell)
                (ca-size ca (+ icell inew))
                (multiple-value-bind (pd ok) (page-insert-array p begin pdata cp (+ icell inew) 1 ca)
                  (unless ok (return-from edit))
                  (setf pdata pd))))))
        (multiple-value-bind (pd ok)
            (page-insert-array p begin pdata (+ co (* ncell 2)) (+ inew ncell) (- nnew ncell) ca)
          (unless ok (return-from edit))
          (setf pdata pd))
        (setf (mp-ncell p) nnew (mp-novfl p) 0)
        (put-u16 d (+ h 3) nnew)
        (put-u16 d (+ h 5) pdata)
        (return-from edit-page)))
    ;; editpage_fail
    (populate-cell-cache ca inew nnew)
    (rebuild-page ca inew nnew p)))

(defun balance-quick (parent page)
  "balance_quick: an intkey leaf overflowing with one cell at its end gets
a new right sibling holding just that cell."
  (when (zerop (mp-ncell page)) (corrupt "empty page ~d in balance" (mp-pgno page)))
  (let* ((pgno-new (allocate-btree-page 0))
         (new (new-mp pgno-new))
         (cell (aref (mp-ovfl-cells page) 0))
         (sz (cell-size-at page (car cell) (cdr cell)))
         (ca (make-cell-array :n 1 :ref page :cells (vector cell) :sizes (vector sz))))
    (zero-page new (logior +ptf-intkey+ +ptf-leafdata+ +ptf-leaf+))
    (rebuild-page ca 0 1 new)
    (setf (mp-nfree new) (- (bt-usable) (mp-cell-offset new) 2 sz))
    (when (autovacuum-p *bt*)
      (ptrmap-put *bt* pgno-new +ptrmap-btree+ (mp-pgno parent))
      (when (> sz (mp-min-local new)) (ptrmap-put-ovfl-ptr new new (car cell) (cdr cell))))
    ;; the divider: the largest key left on PAGE
    (let* ((d (mp-data page)) (o (find-cell page (1- (mp-ncell page))))
           (i o))
      (loop repeat 9 do (let ((b (aref d i))) (incf i) (when (< b #x80) (return))))
      (let ((space (make-octets 13)) (n 4))
        (loop repeat 9 do (let ((b (aref d i))) (setf (aref space n) b) (incf n) (incf i) (when (< b #x80) (return))))
        (insert-cell parent (mp-ncell parent) space 0 n (mp-pgno page))))
    (touch parent)
    (put-u32 (mp-data parent) (+ (mp-hdr parent) 8) pgno-new)))

(defun copy-node-content (from to)
  "copyNodeContent."
  (touch to)
  (let* ((af (mp-data from)) (at (mp-data to)) (fh (mp-hdr from))
         (th (if (= (mp-pgno to) 1) 100 0))
         (idata (get-u16 af (+ fh 5))))
    (replace at af :start1 idata :start2 idata :end2 (bt-usable))
    (replace at af :start1 th :start2 fh :end2 (+ fh (mp-cell-offset from) (* 2 (mp-ncell from))))
    (setf (mp-hdr to) th)
    (mp-init to)
    (mp-compute-free to)
    (set-child-ptrmaps to)))

(defun swap-page-numbers (a b)
  "sqlite3PagerRekey both ways: page objects A and B trade numbers (their
buffers go with them)."
  (let* ((pa (mp-pgno a)) (pb (mp-pgno b)) (cache (db-cache *bt*)))
    (rotatef (gethash pa cache) (gethash pb cache))
    (setf (mp-pgno a) pb (mp-pgno b) pa
          (gethash pb *mps*) a (gethash pa *mps*) b)))

(defun balance-nonroot (parent iparent-idx ovfl-space is-root bulk)
  "balance_nonroot: redistribute the cells of up to three siblings (the child
at IPARENT-IDX and its neighbours) over as many pages as they need."
  (let* ((usable (bt-usable)) (bulk (if bulk 1 0))
         (nb 3) (nx-div 0) (nold 0) (i 0) (nmax 0)
         (apold (make-array nb :initial-element nil))
         (apnew (make-array (+ nb 2) :initial-element nil))
         (apdiv (make-array (1- nb) :initial-element nil))   ; (buffer . offset)
         (cnt-new (make-array (+ nb 2) :initial-element 0))
         (cnt-old (make-array (+ nb 2) :initial-element 0))
         (sz-new (make-array (+ nb 2) :initial-element 0))
         (ab-done (make-array (+ nb 2) :initial-element 0))
         (apgno (make-array (+ nb 2) :initial-element 0))
         (right-buf nil) (right-off 0) (pgno 0) (nnew 0))
    ;; which siblings
    (setf i (+ (mp-novfl parent) (mp-ncell parent)))
    (if (< i 2)
        (setf nx-div 0)
        (progn
          (setf nx-div (cond ((zerop iparent-idx) 0)
                             ((= iparent-idx i) (+ (- i 2) bulk))
                             (t (1- iparent-idx))))
          (setf i (- 2 bulk))))
    (setf nold (1+ i))
    (if (= (- (+ i nx-div) (mp-novfl parent)) (mp-ncell parent))
        (setf right-buf (mp-data parent) right-off (+ (mp-hdr parent) 8))
        (setf right-buf (mp-data parent) right-off (find-cell parent (- (+ i nx-div) (mp-novfl parent)))))
    (setf pgno (get-u32 right-buf right-off))
    (touch parent)
    (loop
      (let ((old (get-mp pgno)))
        (setf (aref apold i) old)
        (mp-ensure-free old)
        (incf nmax (+ (mp-ncell old) 4)))
      (when (zerop i) (return))
      (decf i)
      (if (and (plusp (mp-novfl parent)) (= (+ i nx-div) (aref (mp-ovfl-idx parent) 0)))
          (let ((c (aref (mp-ovfl-cells parent) 0)))
            (setf (aref apdiv i) c
                  pgno (get-u32 (car c) (cdr c))
                  (aref sz-new i) (cell-size-at parent (car c) (cdr c))
                  (mp-novfl parent) 0))
          (let* ((pd (mp-data parent))
                 (off (find-cell parent (- (+ i nx-div) (mp-novfl parent)))))
            (setf (aref apdiv i) (cons pd off)
                  pgno (get-u32 pd off)
                  (aref sz-new i) (cell-size-at parent pd off))
            (when (bt-fast-secure)
              (when (<= (+ off (aref sz-new i)) usable)
                (replace ovfl-space pd :start1 off :start2 off :end2 (+ off (aref sz-new i)))
                (setf (aref apdiv i) (cons ovfl-space off))))
            (drop-cell parent (- (+ i nx-div) (mp-novfl parent)) (aref sz-new i)))))
    ;; gather every cell (and the dividers, unless intkey leaves) into B
    (setf nmax (logandc2 (+ nmax 3) 3))
    (let* ((ca (make-cell-array :ref (aref apold 0)
                                :cells (make-array nmax :initial-element nil)
                                :sizes (make-array nmax :initial-element 0)))
           (space1 (make-octets (db-page-size *bt*))) (ispace1 0)
           (leaf-correction (if (mp-leaf (aref apold 0)) 4 0))
           (leaf-data (mp-intkey-leaf (aref apold 0)))
           (usable-space (+ (- usable 12) leaf-correction))
           (k 0) (page-flags 0) (iovfl-space 0))
      (flet ((push-cell (buf off &optional (size 0))
               (setf (aref (ca-cells ca) (ca-n ca)) (cons buf off)
                     (aref (ca-sizes ca) (ca-n ca)) size)
               (incf (ca-n ca))))
        (dotimes (i nold)
          (let* ((old (aref apold i)) (d (mp-data old)) (limit (mp-ncell old))
                 (pic (mp-cell-offset old)))
            (unless (= (aref d 0) (aref (mp-data (aref apold 0)) 0))
              (corrupt "siblings of different kinds in balance"))
            (when (plusp (mp-novfl old))
              (setf limit (aref (mp-ovfl-idx old) 0))
              (dotimes (j limit) (push-cell d (get-u16 d pic)) (incf pic 2))
              (dotimes (kk (mp-novfl old))
                (let ((c (aref (mp-ovfl-cells old) kk))) (push-cell (car c) (cdr c)))))
            (loop with end = (+ (mp-cell-offset old) (* 2 (mp-ncell old)))
                  while (< pic end)
                  do (push-cell d (get-u16 d pic)) (incf pic 2))
            (setf (aref cnt-old i) (ca-n ca))
            (when (and (< i (1- nold)) (not leaf-data))
              (let* ((sz (aref sz-new i)) (tmp ispace1) (div (aref apdiv i)))
                (incf ispace1 sz)
                (replace space1 (car div) :start1 tmp :start2 (cdr div) :end2 (+ (cdr div) sz))
                (let ((cell-off (+ tmp leaf-correction)) (csz (- sz leaf-correction)))
                  (if (not (mp-leaf old))
                      (replace space1 d :start1 cell-off :start2 8 :end2 12)
                      (loop while (< csz 4) do (setf (aref space1 ispace1) 0) (incf ispace1) (incf csz)))
                  (push-cell space1 cell-off csz)))))))
      ;; sizes of the new pages
      (dotimes (i nold)
        (let ((p (aref apold i)))
          (setf (aref sz-new i) (- usable-space (mp-nfree p)))
          (dotimes (j (mp-novfl p))
            (let ((c (aref (mp-ovfl-cells p) j)))
              (incf (aref sz-new i) (+ 2 (cell-size-at p (car c) (cdr c))))))
          (setf (aref cnt-new i) (aref cnt-old i))))
      (setf k nold)
      (let ((i 0))
        (loop while (< i k)
              do (loop while (> (aref sz-new i) usable-space)
                       do (when (>= (1+ i) k)
                            (setf k (+ i 2))
                            (when (> k (+ nb 2)) (corrupt "balance needs too many pages"))
                            (setf (aref sz-new (1- k)) 0 (aref cnt-new (1- k)) (ca-n ca)))
                          (let ((sz (+ 2 (ca-size ca (1- (aref cnt-new i))))))
                            (decf (aref sz-new i) sz)
                            (unless leaf-data
                              (setf sz (if (< (aref cnt-new i) (ca-n ca)) (+ 2 (ca-size ca (aref cnt-new i))) 0)))
                            (incf (aref sz-new (1+ i)) sz)
                            (decf (aref cnt-new i))))
                 (loop while (< (aref cnt-new i) (ca-n ca))
                       do (let ((sz (+ 2 (ca-size ca (aref cnt-new i)))))
                            (when (> (+ (aref sz-new i) sz) usable-space) (return))
                            (incf (aref sz-new i) sz)
                            (incf (aref cnt-new i))
                            (unless leaf-data
                              (setf sz (if (< (aref cnt-new i) (ca-n ca)) (+ 2 (ca-size ca (aref cnt-new i))) 0)))
                            (decf (aref sz-new (1+ i)) sz)))
                 (cond ((>= (aref cnt-new i) (ca-n ca)) (setf k (1+ i)))
                       ((<= (aref cnt-new i) (if (plusp i) (aref cnt-new (1- i)) 0))
                        (corrupt "balance produced an empty page")))
                 (incf i)))
      ;; even out the right end
      (loop for i from (1- k) above 0
            do (let* ((sz-right (aref sz-new i)) (sz-left (aref sz-new (1- i)))
                      (r (1- (aref cnt-new (1- i))))
                      (d (- (1+ r) (if leaf-data 1 0))))
                 (ca-size ca d)
                 (loop
                   (ca-size ca r)
                   (when (and (/= sz-right 0)
                              (or (= bulk 1)
                                  (> (+ sz-right (aref (ca-sizes ca) d) 2)
                                     (- sz-left (+ (aref (ca-sizes ca) r) (if (= i (1- k)) 0 2))))))
                     (return))
                   (incf sz-right (+ (aref (ca-sizes ca) d) 2))
                   (decf sz-left (+ (aref (ca-sizes ca) r) 2))
                   (setf (aref cnt-new (1- i)) r)
                   (decf r) (decf d)
                   (when (< r 0) (return)))
                 (setf (aref sz-new i) sz-right (aref sz-new (1- i)) sz-left)
                 (when (<= (aref cnt-new (1- i)) (if (> i 1) (aref cnt-new (- i 2)) 0))
                   (corrupt "balance produced an empty page"))))
      ;; the new pages: the old ones reused first, then fresh ones
      (setf page-flags (aref (mp-data (aref apold 0)) 0))
      (dotimes (i k)
        (if (< i nold)
            (progn (setf (aref apnew i) (aref apold i) (aref apold i) nil)
                   (touch (aref apnew i))
                   (incf nnew))
            (let* ((pg (allocate-btree-page (if (= bulk 1) 1 pgno)))
                   (new (new-mp pg)))
              (setf pgno pg)
              (zero-page new page-flags)
              (setf (aref apnew i) new (aref cnt-old i) (ca-n ca))
              (incf nnew)
              (when (autovacuum-p *bt*)
                (ptrmap-put *bt* pg +ptrmap-btree+ (mp-pgno parent))))))
      (dotimes (i nnew) (setf (aref apgno i) (mp-pgno (aref apnew i))))
      ;; page numbers in ascending order
      (dotimes (i (1- nnew))
        (let ((ib i))
          (loop for j from (1+ i) below nnew
                do (when (< (mp-pgno (aref apnew j)) (mp-pgno (aref apnew ib))) (setf ib j)))
          (when (/= ib i)
            (swap-page-numbers (aref apnew i) (aref apnew ib)))))
      (put-u32 right-buf right-off (mp-pgno (aref apnew (1- nnew))))
      (when (and (not (logbitp 3 page-flags)) (/= nold nnew))
        (let ((old (if (> nnew nold) (aref apnew (1- nold)) (aref apold (1- nold)))))
          (replace (mp-data (aref apnew (1- nnew))) (mp-data old) :start1 8 :start2 8 :end2 12)))
      ;; pointer maps for cells that changed page
      (when (autovacuum-p *bt*)
        (let* ((pold (aref apnew 0)) (pnew pold)
               (cnt-old-next (+ (mp-ncell pnew) (mp-novfl pnew)))
               (inew 0) (iold 0))
          (dotimes (i (ca-n ca))
            (let ((c (aref (ca-cells ca) i)))
              (loop while (= i cnt-old-next)
                    do (incf iold)
                       (setf pold (if (< iold nnew) (aref apnew iold) (aref apold iold)))
                       (incf cnt-old-next (+ (mp-ncell pold) (mp-novfl pold) (if leaf-data 0 1))))
              (block this-cell
                (when (= i (aref cnt-new inew))
                  (setf pnew (aref apnew (incf inew)))
                  (unless leaf-data (return-from this-cell)))
                (when (or (>= iold nnew)
                          (/= (mp-pgno pnew) (aref apgno iold))
                          (not (and (eq (car c) (mp-data pold)) (< (cdr c) (db-page-size *bt*)))))
                  (when (zerop leaf-correction)
                    (ptrmap-put *bt* (get-u32 (car c) (cdr c)) +ptrmap-btree+ (mp-pgno pnew)))
                  (when (> (ca-size ca i) (mp-min-local pnew))
                    (ptrmap-put-ovfl-ptr pnew pold (car c) (cdr c)))))))))
      ;; dividers into the parent
      (dotimes (i (1- nnew))
        (let* ((new (aref apnew i)) (j (aref cnt-new i))
               (c (aref (ca-cells ca) j)) (cb (car c)) (co (cdr c))
               (sz (+ (aref (ca-sizes ca) j) leaf-correction))
               (temp-off iovfl-space))
          (cond ((not (mp-leaf new))
                 (replace (mp-data new) cb :start1 8 :start2 co :end2 (+ co 4)))
                (leaf-data
                 (let* ((prev (aref (ca-cells ca) (1- j))))
                   (multiple-value-bind (nkey) (parse-cell new (car prev) (cdr prev))
                     (setf cb ovfl-space co temp-off
                           sz (+ 4 (put-varint ovfl-space (+ temp-off 4) (ldb (byte 64 0) nkey)))))))
                (t (decf co 4)
                   (when (= (aref (ca-sizes ca) j) 4)
                     (setf sz (cell-size-at parent cb co)))))
          (incf iovfl-space sz)
          (insert-cell parent (+ nx-div i) cb co sz (mp-pgno new))))
      ;; fill the new pages, in an order that never overwrites a cell
      ;; still to be copied
      (loop for i from (- 1 nnew) below nnew
            do (let ((ipg (abs i)))
                 (when (and (zerop (aref ab-done ipg))
                            (or (>= i 0) (>= (aref cnt-old (1- ipg)) (aref cnt-new (1- ipg)))))
                   (multiple-value-bind (inew iold nnew-cell)
                       (if (zerop ipg)
                           (values 0 0 (aref cnt-new 0))
                           (let ((inew (+ (aref cnt-new (1- ipg)) (if leaf-data 0 1))))
                             (values inew
                                     (if (< ipg nold) (+ (aref cnt-old (1- ipg)) (if leaf-data 0 1)) (ca-n ca))
                                     (- (aref cnt-new ipg) inew))))
                     (edit-page (aref apnew ipg) iold inew nnew-cell ca))
                   (incf (aref ab-done ipg))
                   (setf (mp-nfree (aref apnew ipg)) (- usable-space (aref sz-new ipg))))))
      (cond ((and is-root (zerop (mp-ncell parent)) (<= (mp-hdr parent) (mp-nfree (aref apnew 0))))
             (defragment-page (aref apnew 0) -1)
             (copy-node-content (aref apnew 0) parent)
             (free-btree-page (mp-pgno (aref apnew 0))))
            ((and (autovacuum-p *bt*) (zerop leaf-correction))
             (dotimes (i nnew)
               (ptrmap-put *bt* (get-u32 (mp-data (aref apnew i)) 8) +ptrmap-btree+ (mp-pgno (aref apnew i))))))
      (loop for i from nnew below nold
            do (free-btree-page (mp-pgno (aref apold i)))))))

(defun balance-deeper (root)
  "balance_deeper: ROOT's content moves to a new child; returns the child."
  (let* ((pgno-child (allocate-btree-page (mp-pgno root)))
         (child (new-mp pgno-child)))
    (copy-node-content root child)
    (when (autovacuum-p *bt*)
      (ptrmap-put *bt* pgno-child +ptrmap-btree+ (mp-pgno root)))
    (replace (mp-ovfl-idx child) (mp-ovfl-idx root))
    (replace (mp-ovfl-cells child) (mp-ovfl-cells root))
    (setf (mp-novfl child) (mp-novfl root))
    (zero-page root (logandc2 (aref (mp-data child) 0) +ptf-leaf+))
    (put-u32 (mp-data root) (+ (mp-hdr root) 8) pgno-child)
    child))

;;; ------------------------------------------------------------------
;;; Cursors: the path from the root to a cell

(defstruct (bcursor (:conc-name cur-))
  (pages (make-array 21 :initial-element nil))
  (idx (make-array 21 :initial-element 0))
  (ipage 0) (ix 0) (bulk nil))

(defun cur-page (c) (aref (cur-pages c) (cur-ipage c)))

(defun balance (c)
  "balance: fix every page on the cursor's path that overflowed or fell
below a third full."
  (loop
    (let ((page (cur-page c)))
      (mp-ensure-free page)
      (cond ((and (zerop (mp-novfl page)) (<= (* 3 (mp-nfree page)) (* 2 (bt-usable))))
             (return))
            ((zerop (cur-ipage c))
             (if (plusp (mp-novfl page))
                 (let ((child (balance-deeper page)))
                   (setf (aref (cur-pages c) 1) child (aref (cur-pages c) 0) page
                         (aref (cur-idx c) 0) 0 (cur-ipage c) 1 (cur-ix c) 0))
                 (return)))
            (t
             (let* ((ip (cur-ipage c))
                    (parent (aref (cur-pages c) (1- ip)))
                    (iidx (aref (cur-idx c) (1- ip))))
               (mp-ensure-free parent)
               (if (and (mp-intkey-leaf page) (= (mp-novfl page) 1)
                        (= (aref (mp-ovfl-idx page) 0) (mp-ncell page))
                        (/= (mp-pgno parent) 1) (= (mp-ncell parent) iidx))
                   (balance-quick parent page)
                   (balance-nonroot parent iidx (make-octets (db-page-size *bt*)) (= ip 1) (cur-bulk c)))
               (setf (mp-novfl page) 0)
               (decf (cur-ipage c))))))))

;;; Seeking.  The position is where SQLite's binary search leaves it.

(defun cursor-descend (root pick)
  "Walk from ROOT: at each page PICK returns (values index found-p); stop at
a leaf or at a found cell.  Returns the cursor, positioned."
  (let ((c (make-bcursor)) (pgno root) (depth 0))
    (loop
      (when (> depth 19) (corrupt "b-tree too deep"))
      (let ((p (get-mp pgno)))
        (setf (aref (cur-pages c) depth) p (cur-ipage c) depth)
        (multiple-value-bind (i found) (funcall pick p)
          (setf (cur-ix c) i)
          (when (or found (mp-leaf p))
            (return (values c found)))
          (setf (aref (cur-idx c) depth) i)
          (setf pgno (if (< i (mp-ncell p))
                         (get-u32 (mp-data p) (find-cell p i))
                         (get-u32 (mp-data p) (+ (mp-hdr p) 8))))
          (incf depth))))))

(defun table-cursor (root rowid)
  "sqlite3BtreeTableMoveto: (values cursor found-p)."
  (cursor-descend
   root
   (lambda (p)
     (let* ((d (mp-data p)) (n (mp-ncell p))
            (i (lower-bound n (lambda (i) (>= (nth-value 0 (parse-cell p d (find-cell p i))) rowid)))))
       (values i (and (mp-leaf p) (< i n) (= (nth-value 0 (parse-cell p d (find-cell p i))) rowid)))))))

(defun index-cell-values (p i)
  (let ((d (mp-data p)) (o (find-cell p i)))
    (multiple-value-bind (nkey npayload nlocal nsize at) (parse-cell p d o)
      (declare (ignore nkey nsize))
      (decode-record (read-payload *bt* d at npayload nlocal)))))

(defun index-cursor (root vals)
  "sqlite3BtreeIndexMoveto for a full key: (values cursor found-p); a found
key may be on an interior page."
  (cursor-descend
   root
   (lambda (p)
     (let* ((n (mp-ncell p)) (cmp (make-hash-table))
            (i (lower-bound n (lambda (i) (>= (setf (gethash i cmp) (funcall *index-cmp* (index-cell-values p i) vals)) 0)))))
       (values i (and (< i n) (eql 0 (or (gethash i cmp) (funcall *index-cmp* (index-cell-values p i) vals)))))))))

;;; ------------------------------------------------------------------
;;; Insert and delete (sqlite3BtreeInsert / sqlite3BtreeDelete)

(defun btree-insert-at (c key payload found &key overwrite)
  "Insert the entry KEY / PAYLOAD at the cursor (replacing the entry there
if FOUND).  With OVERWRITE an existing entry of the same payload size is
rewritten in place, overflow pages included (btreeOverwriteCell)."
  (let* ((p (cur-page c)) (d (mp-data p)) (idx (cur-ix c)))
    (when (and found overwrite (mp-intkey p))
      (multiple-value-bind (nkey npayload nlocal nsize at) (parse-cell p d (find-cell p idx))
        (declare (ignore nkey))
        (when (= npayload (length payload))
          (btree-overwrite-cell p d at nlocal npayload nsize payload)
          (return-from btree-insert-at nil))))
    (mp-ensure-free p)
    (let* ((cell (fill-in-cell p key payload)) (sz (length cell)))
      (when found
        (let ((old (find-cell p idx)))
          (unless (mp-leaf p) (replace cell d :start1 0 :start2 old :end2 (+ old 4)))
          (multiple-value-bind (nsize npayload nlocal) (clear-cell-overflow p d old)
            (when (and (= nsize sz) (= nlocal npayload)
                       (or (not (autovacuum-p *bt*)) (< sz (mp-min-local p))))
              (touch p)
              (replace d cell :start1 old)
              (return-from btree-insert-at nil))
            (drop-cell p idx nsize))))
      (insert-cell p idx cell 0 sz)
      (when (plusp (mp-novfl p))
        (balance c)))))

(defun btree-overwrite-cell (p d at nlocal npayload nsize payload)
  "btreeOverwriteCell: rewrite the payload in place, touching only the pages
whose bytes change."
  (declare (ignore nsize))
  (flet ((overwrite (pgno buf off from n)
           (unless (loop for i below n always (= (aref buf (+ off i)) (aref payload (+ from i))))
             (if p (touch p) (page-for-write *bt* pgno))
             (replace buf payload :start1 off :start2 from :end2 (+ from n)))))
    (overwrite (mp-pgno p) d at 0 nlocal)
    (setf p nil)
    (unless (= nlocal npayload)
      (let ((ioff nlocal) (ovfl (get-u32 d (+ at nlocal))) (size (- (bt-usable) 4)))
        (loop while (< ioff npayload)
              do (let* ((pg ovfl) (b (read-page *bt* ovfl)) (n size) (next ovfl))
                   (if (< (+ ioff size) npayload)
                       (setf next (get-u32 b 0))
                       (setf n (- npayload ioff)))
                   (overwrite pg b 4 ioff n)
                   (incf ioff n)
                   (setf ovfl next)))))))

(defun btree-previous-to-leaf (c)
  "From an interior cell, move to the in-order predecessor (the rightmost
entry of its left subtree)."
  (let* ((p (cur-page c)) (ip (cur-ipage c)))
    (setf (aref (cur-idx c) ip) (cur-ix c))
    (let ((pgno (get-u32 (mp-data p) (find-cell p (cur-ix c)))))
      (loop
        (incf ip)
        (let ((q (get-mp pgno)))
          (setf (aref (cur-pages c) ip) q (cur-ipage c) ip)
          (if (mp-leaf q)
              (progn (setf (cur-ix c) (1- (mp-ncell q))) (return))
              (progn (setf (aref (cur-idx c) ip) (mp-ncell q))
                     (setf pgno (get-u32 (mp-data q) (+ (mp-hdr q) 8))))))))))

(defun btree-delete-at (c)
  "sqlite3BtreeDelete of the cell under the cursor."
  (let* ((cell-depth (cur-ipage c)) (cell-idx (cur-ix c))
         (p (cur-page c)) (d (mp-data p)))
    (when (<= (mp-ncell p) cell-idx) (corrupt "delete past the last cell"))
    (let ((o (find-cell p cell-idx)))
      (mp-ensure-free p)
      (unless (mp-leaf p) (btree-previous-to-leaf c))
      (let ((nsize (clear-cell-overflow p d o)))
        (drop-cell p cell-idx nsize))
      (unless (mp-leaf p)
        (let* ((leaf (cur-page c))
               (n (if (< cell-depth (1- (cur-ipage c)))
                      (mp-pgno (aref (cur-pages c) (1+ cell-depth)))
                      (mp-pgno leaf))))
          (mp-ensure-free leaf)
          (let* ((lo (find-cell leaf (1- (mp-ncell leaf))))
                 (ncell (cell-size-at leaf (mp-data leaf) lo)))
            (when (< lo 4) (corrupt "bad cell on page ~d" (mp-pgno leaf)))
            (insert-cell p cell-idx (subseq (mp-data leaf) (- lo 4) (+ lo ncell)) 0 (+ ncell 4) n)
            (drop-cell leaf (1- (mp-ncell leaf)) ncell))))
      (unless (<= (* 3 (mp-ensure-free (cur-page c))) (* 2 (bt-usable)))
        (balance c))
      (when (> (cur-ipage c) cell-depth)
        (setf (cur-ipage c) cell-depth)
        (balance c)))))

;;; ------------------------------------------------------------------
;;; The b-tree API used by the rest of the library

(defun table-insert (db root rowid payload &key overwrite)
  "Insert or replace the row ROWID."
  (with-bt (db)
    (multiple-value-bind (c found) (table-cursor root rowid)
      (btree-insert-at c rowid payload found :overwrite overwrite))))

(defun table-delete (db root rowid)
  "Delete ROWID; return true if it existed."
  (with-bt (db)
    (multiple-value-bind (c found) (table-cursor root rowid)
      (when found (btree-delete-at c) t))))

(defun index-insert-payload (db root payload &key bulk)
  (with-bt (db)
    (multiple-value-bind (c found) (index-cursor root (decode-record payload))
      (setf (cur-bulk c) bulk)
      ;; an equal key of the same size is overwritten in place
      ;; (sqlite3BtreeInsert's btreeOverwriteCell for index cursors)
      (when found
        (let* ((p (cur-page c)) (d (mp-data p)))
          (multiple-value-bind (nkey npayload nlocal nsize at) (parse-cell p d (find-cell p (cur-ix c)))
            (declare (ignore nkey))
            (when (= npayload (length payload))
              (btree-overwrite-cell p d at nlocal npayload nsize payload)
              (return-from index-insert-payload nil)))))
      (btree-insert-at c payload payload found))))

(defun index-insert (db root vals &key bulk)
  (index-insert-payload db root (encode-record vals) :bulk bulk))

(defun index-delete (db root vals)
  "Delete the entry equal to VALS; return true if found."
  (with-bt (db)
    (multiple-value-bind (c found) (index-cursor root vals)
      (when found (btree-delete-at c) t))))

(defun create-btree (db type)
  "btreeCreateTable: a new empty tree of TYPE (a leaf page type)."
  (ensure-write-txn db)                  ; page 1 (and its auto_vacuum flag) first
  (with-bt (db)
    (let ((pg (if (autovacuum-p db) (allocate-root db) (allocate-btree-page 1))))
      (zero-page (new-mp pg) type)
      pg)))

(defun clear-page (pgno free-p)
  "clearDatabasePage."
  (let* ((p (get-mp pgno)) (d (mp-data p)))
    (dotimes (i (mp-ncell p))
      (let ((o (find-cell p i)))
        (unless (mp-leaf p) (clear-page (get-u32 d o) t))
        (clear-cell-overflow p d o)))
    (unless (mp-leaf p) (clear-page (get-u32 d (+ (mp-hdr p) 8)) t))
    (if free-p
        (free-btree-page pgno)
        (zero-page p (logior (aref d (mp-hdr p)) +ptf-leaf+)))))

(defun clear-btree (db root &key keep-root)
  "Free every page of the tree; with KEEP-ROOT leave an empty root."
  (with-bt (db)
    (clear-page root nil)
    (unless keep-root (free-btree-page root))))

(defun allocate-page (db &optional (nearby 0) (mode :any))
  (with-bt (db) (allocate-btree-page nearby mode)))

(defun free-page (db pgno)
  (with-bt (db) (free-btree-page pgno)))
