;;;; datetime.lisp — date(), time(), datetime(), julianday(), unixepoch(),
;;;; strftime(), following SQLite's date.c: times are kept as a Julian day
;;;; number in milliseconds, with SQLite's own calendar arithmetic.

(in-package #:sqlite-pure)

(defstruct (dt (:conc-name dt-))
  (jd 0) (y 2000) (m 1) (d 1) (h 0) (mi 0) (s 0d0)
  valid-jd valid-ymd valid-hms (tz 0) valid-tz raw-s raw-value)

(defun ctrunc (x) (truncate x))          ; C's cast / integer division

(defun dt-compute-jd (p)
  (unless (dt-valid-jd p)
    (let ((y 2000) (m 1) (d 1))
      (when (dt-valid-ymd p) (setf y (dt-y p) m (dt-m p) d (dt-d p)))
      (when (<= m 2) (decf y) (incf m 12))
      (let* ((a (ctrunc (/ y 100)))
             (b (+ (- 2 a) (ctrunc (/ a 4))))
             (x1 (ctrunc (/ (* 36525 (+ y 4716)) 100)))
             (x2 (ctrunc (/ (* 306001 (+ m 1)) 10000))))
        (setf (dt-jd p) (ctrunc (* (- (+ x1 x2 d b) 1524.5d0) 86400000)))
        (setf (dt-valid-jd p) t)
        (when (dt-valid-hms p)
          (incf (dt-jd p) (+ (* (dt-h p) 3600000) (* (dt-mi p) 60000)
                             (ctrunc (+ (* (dt-s p) 1000) 0.5d0))))
          (when (dt-valid-tz p)
            (decf (dt-jd p) (* (dt-tz p) 60000))
            (setf (dt-valid-ymd p) nil (dt-valid-hms p) nil (dt-valid-tz p) nil)))))))

(defun valid-julian-day-p (ijd) (<= 0 ijd 464269060799999))

(defun dt-compute-ymd (p)
  (unless (dt-valid-ymd p)
    (cond ((not (dt-valid-jd p)) (setf (dt-y p) 2000 (dt-m p) 1 (dt-d p) 1))
          ((not (valid-julian-day-p (dt-jd p))) (throw :dt-error nil))
          (t
           (let* ((z (ctrunc (/ (+ (dt-jd p) 43200000) 86400000)))
                  (a (ctrunc (/ (- z 1867216.25d0) 36524.25d0)))
                  (a (- (+ z 1 a) (ctrunc (/ a 4))))
                  (b (+ a 1524))
                  (c (ctrunc (/ (- b 122.1d0) 365.25d0)))
                  (d (ctrunc (/ (* 36525 (logand c 32767)) 100)))
                  (e (ctrunc (/ (- b d) 30.6001d0)))
                  (x1 (ctrunc (* 30.6001d0 e))))
             (setf (dt-d p) (- b d x1)
                   (dt-m p) (if (< e 14) (1- e) (- e 13)))
             (setf (dt-y p) (if (> (dt-m p) 2) (- c 4716) (- c 4715))))))
    (setf (dt-valid-ymd p) t)))

(defun dt-compute-hms (p)
  (unless (dt-valid-hms p)
    (dt-compute-jd p)
    (let* ((day-ms (mod (+ (dt-jd p) 43200000) 86400000))
           (day-min (floor day-ms 60000)))
      (setf (dt-s p) (/ (mod day-ms 60000) 1000d0)
            (dt-mi p) (mod day-min 60)
            (dt-h p) (floor day-min 60)
            (dt-valid-hms p) t))))

(defun dt-compute-ymd-hms (p) (dt-compute-ymd p) (dt-compute-hms p))

(defun dt-clear-ymd-hms-tz (p)
  (setf (dt-valid-ymd p) nil (dt-valid-hms p) nil (dt-valid-tz p) nil))

;;; ------------------------------------------------------------------
;;; Parsing

(defun digits-at (s i n)
  "N decimal digits at I, or NIL."
  (when (and (<= (+ i n) (length s))
             (loop for k from i below (+ i n) always (digit-char-p (char s k))))
    (parse-integer s :start i :end (+ i n))))

(defun skip-spaces (s i)
  (loop while (and (< i (length s)) (whitespace-char-p (char s i))) do (incf i))
  i)

(defun parse-timezone (s i p)
  "Parse an optional [+-]HH:MM or Z at I; return the index after it or NIL."
  (let ((i (skip-spaces s i)))
    (setf (dt-tz p) 0)
    (cond ((>= i (length s)) i)
          ((char-equal (char s i) #\z)
           (setf (dt-valid-tz p) t)
           (skip-spaces s (1+ i)))
          ((member (char s i) '(#\+ #\-))
           (let ((sgn (if (char= (char s i) #\-) -1 1))
                 (hh (digits-at s (1+ i) 2))
                 (mm (and (< (+ i 3) (length s)) (char= (char s (+ i 3)) #\:) (digits-at s (+ i 4) 2))))
             (when (and hh mm (<= hh 14) (<= mm 59))
               (setf (dt-tz p) (* sgn (+ (* hh 60) mm)) (dt-valid-tz p) t)
               (skip-spaces s (+ i 6)))))
          (t i))))

(defun parse-hh-mm-ss (s i p)
  "Parse HH:MM[:SS[.fff]] (+ timezone) at I to the end of S."
  (let ((h (digits-at s i 2)))
    (when (and h (<= h 24) (< (+ i 2) (length s)) (char= (char s (+ i 2)) #\:))
      (let ((m (digits-at s (+ i 3) 2)) (sec 0d0) (j (+ i 5)))
        (when (and m (<= m 59))
          (when (and (< j (length s)) (char= (char s j) #\:))
            (let ((ss (digits-at s (1+ j) 2)))
              (unless (and ss (<= ss 59)) (return-from parse-hh-mm-ss nil))
              (setf sec (float ss 1d0) j (+ j 3))
              (when (and (< (1+ j) (length s)) (char= (char s j) #\.) (digit-char-p (char s (1+ j))))
                (let ((scale 0.1d0))
                  (incf j)
                  (loop while (and (< j (length s)) (digit-char-p (char s j)))
                        do (incf sec (* scale (digit-char-p (char s j))))
                           (setf scale (/ scale 10))
                           (incf j))))))
          (let ((end (parse-timezone s j p)))
            (when (and end (= end (length s)))
              (setf (dt-h p) h (dt-mi p) m (dt-s p) sec
                    (dt-valid-jd p) nil (dt-valid-hms p) t)
              t)))))))

(defun parse-yyyy-mm-dd (s p)
  (let* ((i (skip-spaces s 0))
         (neg (and (< i (length s)) (char= (char s i) #\-))))
    (when neg (incf i))
    (let ((y (digits-at s i 4)))
      (when (and y (< (+ i 4) (length s)) (char= (char s (+ i 4)) #\-))
        (let ((m (digits-at s (+ i 5) 2)))
          (when (and m (<= 1 m 12) (< (+ i 7) (length s)) (char= (char s (+ i 7)) #\-))
            (let ((d (digits-at s (+ i 8) 2)))
              (when (and d (<= 1 d 31))
                (let ((j (+ i 10)))
                  (loop while (and (< j (length s))
                                   (or (whitespace-char-p (char s j)) (char-equal (char s j) #\t)))
                        do (incf j))
                  (setf (dt-y p) (if neg (- y) y) (dt-m p) m (dt-d p) d
                        (dt-valid-ymd p) t (dt-valid-jd p) nil)
                  (cond ((>= j (length s)) (setf (dt-valid-hms p) nil) t)
                        ((parse-hh-mm-ss s j p) t)
                        (t nil)))))))))))

(defun current-ijd ()
  (let ((unix (- (get-universal-time) 2208988800)))
    (+ (* unix 1000) 210866760000000)))

(defun set-raw-number (p r)
  (setf (dt-raw-s p) t (dt-raw-value p) r)
  (when (<= 0 r 5373484.4999999d0)
    (setf (dt-jd p) (ctrunc (+ (* r 86400000) 0.5d0)) (dt-valid-jd p) t)))

(defun parse-date-or-time (v p)
  (cond ((or (integerp v) (floatp v)) (set-raw-number p (float v 1d0)) t)
        ((stringp v)
         (let ((s (string-trim " " v)))
           (cond ((parse-yyyy-mm-dd s p) t)
                 ((parse-hh-mm-ss s 0 p) t)
                 ((string-equal s "now")
                  (setf (dt-jd p) (current-ijd) (dt-valid-jd p) t) t)
                 ((text-numeric-value s)
                  (set-raw-number p (float (text-numeric-value s) 1d0)) t)
                 (t nil))))
        (t nil)))

;;; ------------------------------------------------------------------
;;; Modifiers

(defparameter +xform-units+
  ;; name  limit  seconds-per-unit
  '(("second" 4.6427d14 1) ("minute" 7.7379d12 60) ("hour" 1.2897d11 3600)
    ("day" 5373485d0 86400) ("month" 176546d0 2592000) ("year" 14713d0 31536000)))

(defun local-offset-minutes (ijd)
  "Local time zone offset east of UTC, in minutes, at IJD."
  (let* ((unix (floor (- ijd 210866760000000) 1000))
         (ut (+ unix 2208988800)))
    (if (or (< ut 0) (> ut (* 400 365 86400 10)))
        0
        (multiple-value-bind (sec min hour date month year dow dst tz)
            (decode-universal-time ut)
          (declare (ignore sec min hour date month year dow))
          (round (* -60 (- tz (if dst 1 0))))))))

(defun apply-modifier (p mod idx)
  (let* ((z (string-downcase-ascii (string-trim " " mod)))
         (n (length z)))
    (flet ((fail () (throw :dt-error nil)))
      (cond
        ((string= z "localtime")
         (dt-compute-jd p)
         (incf (dt-jd p) (* 60000 (local-offset-minutes (dt-jd p))))
         (dt-clear-ymd-hms-tz p))
        ((string= z "utc")
         (dt-compute-jd p)
         (decf (dt-jd p) (* 60000 (local-offset-minutes (dt-jd p))))
         (dt-clear-ymd-hms-tz p))
        ((string= z "unixepoch")
         (unless (and (= idx 0) (dt-raw-s p)) (fail))
         (let ((r (+ (* (dt-raw-value p) 1000) 210866760000000d0)))
           (unless (and (>= r 0) (< r 464269060800000d0)) (fail))
           (setf (dt-jd p) (ctrunc (+ r 0.5d0)) (dt-valid-jd p) t)
           (dt-clear-ymd-hms-tz p)))
        ((string= z "julianday")
         (unless (and (= idx 0) (dt-raw-s p)) (fail)))
        ((string= z "auto")
         (unless (= idx 0) (fail))
         (when (dt-raw-s p)
           (let ((r (dt-raw-value p)))
             (if (<= 0 r 5373484.4999999d0)
                 nil
                 (let ((jr (+ (* r 1000) 210866760000000d0)))
                   (unless (and (>= jr 0) (< jr 464269060800000d0)) (fail))
                   (setf (dt-jd p) (ctrunc (+ jr 0.5d0)) (dt-valid-jd p) t)
                   (dt-clear-ymd-hms-tz p))))))
        ((and (> n 8) (string= (subseq z 0 8) "weekday "))
         (let ((r (text-numeric-value (subseq z 8))))
           (unless (and r (= r (ftruncate r)) (<= 0 r) (< r 7)) (fail))
           (let ((wd (truncate r)))
             (dt-compute-ymd-hms p)
             (setf (dt-valid-tz p) nil (dt-valid-jd p) nil)
             (dt-compute-jd p)
             (let ((zz (mod (floor (+ (dt-jd p) 129600000) 86400000) 7)))
               (when (> zz wd) (decf zz 7))
               (incf (dt-jd p) (* (- wd zz) 86400000))
               (dt-clear-ymd-hms-tz p)))))
        ((and (> n 9) (string= (subseq z 0 9) "start of "))
         (let ((what (subseq z 9)))
           (dt-compute-ymd p)
           (setf (dt-valid-hms p) t (dt-h p) 0 (dt-mi p) 0 (dt-s p) 0d0
                 (dt-valid-tz p) nil (dt-valid-jd p) nil)
           (cond ((string= what "month") (setf (dt-d p) 1))
                 ((string= what "year") (setf (dt-m p) 1 (dt-d p) 1))
                 ((string= what "day"))
                 (t (fail)))))
        ((and (plusp n) (or (digit-char-p (char z 0)) (member (char z 0) '(#\+ #\- #\.))))
         ;; "+HH:MM[:SS]" or "NNN units"
         (let ((colon (position #\: z)))
           (if colon
               (let ((q (make-dt))
                     (sgn 1) (i 0))
                 (when (member (char z 0) '(#\+ #\-))
                   (when (char= (char z 0) #\-) (setf sgn -1))
                   (setf i 1))
                 (unless (parse-hh-mm-ss z i q) (fail))
                 (dt-compute-jd q)
                 (let ((delta (- (dt-jd q) 43200000)))
                   (setf delta (- delta (* 86400000 (floor delta 86400000))))
                   (dt-compute-jd p)
                   (dt-clear-ymd-hms-tz p)
                   (incf (dt-jd p) (* sgn delta))))
               (multiple-value-bind (r end) (scan-number z)
                 (unless r (fail))
                 (let* ((r (float r 1d0))
                        (unit (string-trim " " (subseq z end)))
                        (unit (if (and (plusp (length unit)) (char= (char unit (1- (length unit))) #\s))
                                  (subseq unit 0 (1- (length unit)))
                                  unit))
                        (entry (assoc unit +xform-units+ :test #'string=)))
                   (unless (and entry (> r (- (second entry))) (< r (second entry))) (fail))
                   (cond ((string= unit "month")
                          (dt-compute-ymd-hms p)
                          (incf (dt-m p) (ctrunc r))
                          (let ((x (if (> (dt-m p) 0)
                                       (ctrunc (/ (1- (dt-m p)) 12))
                                       (ctrunc (/ (- (dt-m p) 12) 12)))))
                            (incf (dt-y p) x)
                            (decf (dt-m p) (* x 12)))
                          (setf (dt-valid-jd p) nil)
                          (decf r (ctrunc r)))
                         ((string= unit "year")
                          (dt-compute-ymd-hms p)
                          (incf (dt-y p) (ctrunc r))
                          (setf (dt-valid-jd p) nil)
                          (decf r (ctrunc r))))
                   (dt-compute-jd p)
                   (incf (dt-jd p) (ctrunc (+ (* r 1000d0 (third entry)) (if (minusp r) -0.5d0 0.5d0))))
                   (dt-clear-ymd-hms-tz p))))))
        (t (fail))))))

(defun make-date-time (args)
  "Parse ARGS (time value then modifiers) into a DT, or NIL."
  (catch :dt-error
    (let ((p (make-dt)))
      (if (null args)
          (setf (dt-jd p) (current-ijd) (dt-valid-jd p) t)
          (progn
            (when (eq (first args) :null) (throw :dt-error nil))
            (unless (parse-date-or-time (first args) p) (throw :dt-error nil))))
      (loop for m in (rest args)
            for i from 0
            do (when (eq m :null) (throw :dt-error nil))
               (apply-modifier p (value-to-text m) i))
      (dt-compute-jd p)
      (unless (valid-julian-day-p (dt-jd p)) (throw :dt-error nil))
      p)))

;;; ------------------------------------------------------------------
;;; Output

(defun fmt-date (p)
  (dt-compute-ymd p)
  (let ((y (dt-y p)))
    (format nil "~:[~;-~]~4,'0d-~2,'0d-~2,'0d" (minusp y) (abs y) (dt-m p) (dt-d p))))

(defun fmt-time (p)
  (dt-compute-hms p)
  (format nil "~2,'0d:~2,'0d:~2,'0d" (dt-h p) (dt-mi p) (truncate (dt-s p))))

(defsqlfun "date" (0 nil) (args)
  (let ((p (make-date-time args))) (if p (fmt-date p) :null)))

(defsqlfun "time" (0 nil) (args)
  (let ((p (make-date-time args))) (if p (fmt-time p) :null)))

(defsqlfun "datetime" (0 nil) (args)
  (let ((p (make-date-time args)))
    (if p (concatenate 'string (fmt-date p) " " (fmt-time p)) :null)))

(defsqlfun "julianday" (0 nil) (args)
  (let ((p (make-date-time args))) (if p (/ (dt-jd p) 86400000d0) :null)))

(defsqlfun "unixepoch" (0 nil) (args)
  (let ((p (make-date-time args)))
    (if p (- (floor (dt-jd p) 1000) 210866760000) :null)))

(defsqlfun "strftime" (1 nil) (args)
  (let ((fmt (first args)))
    (if (eq fmt :null)
        :null
        (let ((p (make-date-time (rest args)))
              (fmt (value-to-text fmt)))
          (if (null p)
              :null
              (block strf
                (dt-compute-ymd-hms p)
                (with-output-to-string (out)
                  (loop with i = 0
                        while (< i (length fmt))
                        do (let ((c (char fmt i)))
                             (if (char/= c #\%)
                                 (write-char c out)
                                 (progn
                                   (incf i)
                                   (when (>= i (length fmt)) (return-from strf :null))
                                   (case (char fmt i)
                                     (#\d (format out "~2,'0d" (dt-d p)))
                                     (#\f (let ((s (dt-s p)))
                                            (when (> s 59.999d0) (setf s 59.999d0))
                                            (format out "~6,3,,,'0f" s)))
                                     (#\H (format out "~2,'0d" (dt-h p)))
                                     ((#\W #\j)
                                      (let* ((y (let ((c (copy-dt p)))
                                                  (setf (dt-valid-jd c) nil (dt-m c) 1 (dt-d c) 1
                                                        (dt-valid-tz c) nil)
                                                  c))
                                             (_ (dt-compute-jd y))
                                             (nday (floor (+ (- (dt-jd p) (dt-jd y)) 43200000) 86400000)))
                                        (declare (ignore _))
                                        (if (char= (char fmt i) #\W)
                                            (let ((wd (mod (floor (+ (dt-jd p) 43200000) 86400000) 7)))
                                              (format out "~2,'0d" (floor (+ nday 7 (- wd)) 7)))
                                            (format out "~3,'0d" (1+ nday)))))
                                     (#\J (write-string (sql-printf "%.16g" (list (/ (dt-jd p) 86400000d0))) out))
                                     (#\m (format out "~2,'0d" (dt-m p)))
                                     (#\M (format out "~2,'0d" (dt-mi p)))
                                     (#\s (format out "~d" (- (floor (dt-jd p) 1000) 210866760000)))
                                     (#\S (format out "~2,'0d" (truncate (dt-s p))))
                                     (#\w (format out "~d" (mod (floor (+ (dt-jd p) 129600000) 86400000) 7)))
                                     (#\Y (format out "~4,'0d" (dt-y p)))
                                     (#\% (write-char #\% out))
                                     (t (return-from strf :null))))))
                           (incf i)))))))))
