;;;; fts3-token.lisp — FTS3/4 tokenizers: simple, porter and unicode61
;;;; (fts3_tokenizer1.c, fts3_porter.c, fts3_unicode.c), and the argument
;;;; parsing of "tokenize=NAME ARG ...".
;;;;
;;;; FTS3 works on UTF-8 bytes throughout: a tokenizer reads an octet vector
;;;; and yields tokens as byte strings (Lisp strings of characters 0..255,
;;;; so they hash with EQUAL and compare like memcmp) with byte offsets.

(in-package #:sqlite-pure)

(defstruct (fts3-tokenizer (:conc-name f3tok-))
  kind            ; :simple :porter :unicode61
  delim           ; simple: 128-element vector of booleans
  (diacritics 1)  ; unicode61: remove_diacritics 0/1/2
  (exceptions #()); unicode61: sorted codepoints whose alnum-ness is inverted
  spec)           ; the tokenizer name and arguments, as given

(defun bytes-to-bstring (b &optional (start 0) (end (length b)))
  (let ((s (make-string (- end start))))
    (loop for i from start below end
          for j from 0
          do (setf (char s j) (code-char (aref b i))))
    s))

(defun bstring-to-bytes (s)
  (let ((b (make-octets (length s))))
    (dotimes (i (length s) b) (setf (aref b i) (char-code (char s i))))))

(defun text-to-bstring (text)
  (bytes-to-bstring (utf8-encode text)))

;;; ------------------------------------------------------------------
;;; Argument parsing (sqlite3Fts3NextToken, sqlite3Fts3Dequote)

(defun fts3-id-char-p (code)
  (or (>= code #x80)
      (and (< code 128)
           (or (char= (code-char code) #\$) (char= (code-char code) #\_)
               (alphanumericp (code-char code))))))

(defun fts3-dequote (s)
  (if (and (plusp (length s)) (member (char s 0) '(#\[ #\' #\" #\`)))
      (let ((q (if (char= (char s 0) #\[) #\] (char s 0)))
            (out (make-string-output-stream))
            (i 1))
        (loop while (< i (length s))
              do (let ((c (char s i)))
                   (cond ((char= c q)
                          (if (and (< (1+ i) (length s)) (char= (char s (1+ i)) q))
                              (progn (write-char q out) (incf i 2))
                              (return)))
                         (t (write-char c out) (incf i)))))
        (get-output-stream-string out))
      s))

(defun fts3-next-token (s start)
  "sqlite3Fts3NextToken: (values token-start token-end) or NIL."
  (let ((n (length s)) (i start))
    (loop
      (when (>= i n) (return nil))
      (let ((c (char s i)))
        (case c
          ((#\' #\" #\`)
           (let ((j i))
             (loop (incf j)
                   (when (>= j n) (return))
                   (when (char= (char s j) c)
                     (incf j)
                     (unless (and (< j n) (char= (char s j) c)) (return))))
             (return (values i (min j n)))))
          (#\[
           (let ((j (1+ i)))
             (loop while (and (< j n) (char/= (char s j) #\])) do (incf j))
             (when (< j n) (incf j))
             (return (values i j))))
          (t (if (fts3-id-char-p (char-code c))
                 (let ((j (1+ i)))
                   (loop while (and (< j n) (fts3-id-char-p (char-code (char s j)))) do (incf j))
                   (return (values i j)))
                 (incf i))))))))

(defun fts3-split-args (s)
  "The dequoted words of S, as sqlite3Fts3InitTokenizer splits them."
  (let ((out '()) (pos 0))
    (loop (multiple-value-bind (a b) (fts3-next-token s pos)
            (unless a (return))
            (push (fts3-dequote (subseq s a b)) out)
            (setf pos (1+ b))))
    (nreverse out)))

(defun make-fts3-tokenizer-from (spec)
  "SPEC is the text after 'tokenize' (or NIL for the default)."
  (let* ((words (if spec (fts3-split-args spec) '()))
         (name (if spec (or (first words) "") "simple"))
         (args (rest words)))
    (flet ((bad () (sql-error "unknown tokenizer")))
      (cond
        ((string= name "simple")
         (let ((d (make-array 128 :initial-element nil)))
           (if (> (length args) 1)
               (loop for c across (utf8-encode (second args))
                     do (if (>= c #x80) (bad) (setf (aref d c) t)))
               (loop for i from 1 below 128
                     do (setf (aref d i) (not (alphanumericp (code-char i))))))
           (make-fts3-tokenizer :kind :simple :delim d :spec spec)))
        ((string= name "porter") (make-fts3-tokenizer :kind :porter :spec spec))
        ((string= name "unicode61")
         (let ((tk (make-fts3-tokenizer :kind :unicode61 :spec spec)))
           (dolist (a args)
             (cond ((string= a "remove_diacritics=1") (setf (f3tok-diacritics tk) 1))
                   ((string= a "remove_diacritics=0") (setf (f3tok-diacritics tk) 0))
                   ((string= a "remove_diacritics=2") (setf (f3tok-diacritics tk) 2))
                   ((and (>= (length a) 11) (string= "tokenchars=" a :end2 11))
                    (u61-add-exceptions tk t (subseq a 11)))
                   ((and (>= (length a) 11) (string= "separators=" a :end2 11))
                    (u61-add-exceptions tk nil (subseq a 11)))
                   (t (bad))))
           tk))
        (t (sql-error "unknown tokenizer: ~a" name))))))

;;; ------------------------------------------------------------------
;;; Tokenizing.  A token is (term start end position).

(defun fts3-tokenize (tk bytes &optional (end (length bytes)))
  (ecase (f3tok-kind tk)
    (:simple (fts3-simple-tokenize tk bytes end))
    (:porter (fts3-porter-tokenize bytes end))
    (:unicode61 (fts3-u61-tokenize tk bytes end))))

(defun fts3-text-bytes (v)
  "The UTF-8 bytes a column value is tokenized as, cut at the first NUL
(the tokenizers are called with nBytes<0), or NIL for NULL."
  (cond ((eq v :null) nil)
        (t (let* ((b (if (blobp v) v (utf8-encode (value-to-text v))))
                  (z (position 0 b)))
             (if z (subseq b 0 z) b)))))

(defun fts3-simple-tokenize (tk p n)
  (let ((d (f3tok-delim tk)) (off 0) (pos 0) (out '()))
    (flet ((delim-p (c) (and (< c #x80) (aref d c))))
      (loop while (< off n)
            do (loop while (and (< off n) (delim-p (aref p off))) do (incf off))
               (let ((start off))
                 (loop while (and (< off n) (not (delim-p (aref p off)))) do (incf off))
                 (when (> off start)
                   (let ((s (make-string (- off start))))
                     (loop for i from start below off
                           for j from 0
                           do (let ((c (aref p i)))
                                (setf (char s j) (code-char (if (<= 65 c 90) (+ c 32) c)))))
                     (push (list s start off pos) out)
                     (incf pos))))))
    (coerce (nreverse out) 'vector)))

;;; Porter (fts3_porter.c).  The stemmer works on the word reversed in a
;;; zero-padded buffer, reading past the word's end as C does.

(defparameter +porter-ctype+ #(0 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 2 1))

(defun porter-stem-bytes (w n)
  "Stem the N bytes of W; returns a byte string."
  (labels ((copy-stemmer ()
             (let ((out (make-array n :element-type 'character :fill-pointer 0 :adjustable t))
                   (has-digit nil))
               (dotimes (i n)
                 (let ((c (aref w i)))
                   (when (<= 48 c 57) (setf has-digit t))
                   (vector-push-extend (code-char (if (<= 65 c 90) (+ c 32) c)) out)))
               (let ((mx (if has-digit 3 10)))
                 (if (> n (* mx 2))
                     (concatenate 'string (subseq out 0 mx) (subseq out (- n mx)))
                     (coerce out 'simple-string))))))
    (when (or (< n 3) (>= n 21)) (return-from porter-stem-bytes (copy-stemmer)))
    (let ((z (make-array 40 :element-type '(unsigned-byte 8) :initial-element 0))
          (p 10))
      ;; the word reversed at z[p..p+n-1], zeros after
      (dotimes (i n)
        (let ((c (aref w i)))
          (cond ((<= 65 c 90) (setf (aref z (+ p (- n 1 i))) (+ c 32)))
                ((<= 97 c 122) (setf (aref z (+ p (- n 1 i))) c))
                (t (return-from porter-stem-bytes (copy-stemmer))))))
      (labels ((at (i) (aref z i))
               (is-cons (i)
                 (let ((x (at i)))
                   (if (zerop x) nil
                       (let ((j (aref +porter-ctype+ (- x 97))))
                         (if (< j 2) (= j 1) (or (zerop (at (1+ i))) (is-vowel (1+ i))))))))
               (is-vowel (i)
                 (let ((x (at i)))
                   (if (zerop x) nil
                       (let ((j (aref +porter-ctype+ (- x 97))))
                         (if (< j 2) (= j 0) (is-cons (1+ i)))))))
               (m-gt-0 (i)
                 (loop while (is-vowel i) do (incf i))
                 (when (zerop (at i)) (return-from m-gt-0 nil))
                 (loop while (is-cons i) do (incf i))
                 (/= 0 (at i)))
               (m-eq-1 (i)
                 (loop while (is-vowel i) do (incf i))
                 (when (zerop (at i)) (return-from m-eq-1 nil))
                 (loop while (is-cons i) do (incf i))
                 (when (zerop (at i)) (return-from m-eq-1 nil))
                 (loop while (is-vowel i) do (incf i))
                 (when (zerop (at i)) (return-from m-eq-1 t))
                 (loop while (is-cons i) do (incf i))
                 (zerop (at i)))
               (m-gt-1 (i)
                 (loop while (is-vowel i) do (incf i))
                 (when (zerop (at i)) (return-from m-gt-1 nil))
                 (loop while (is-cons i) do (incf i))
                 (when (zerop (at i)) (return-from m-gt-1 nil))
                 (loop while (is-vowel i) do (incf i))
                 (when (zerop (at i)) (return-from m-gt-1 nil))
                 (loop while (is-cons i) do (incf i))
                 (/= 0 (at i)))
               (has-vowel (i)
                 (loop while (is-cons i) do (incf i))
                 (/= 0 (at i)))
               (double-cons (i) (and (is-cons i) (= (at i) (at (1+ i)))))
               (star-oh (i)
                 (and (is-cons i) (not (member (at i) '(119 120 121)))
                      (is-vowel (1+ i)) (is-cons (+ i 2))))
               (stem (from to cond)
                 ;; FROM reversed, TO forward
                 (let ((i p) (k 0))
                   (loop while (and (< k (length from)) (= (char-code (char from k)) (at i)))
                         do (incf i) (incf k))
                   (when (< k (length from)) (return-from stem nil))
                   (when (and cond (not (funcall cond i))) (return-from stem t))
                   (loop for c across to do (decf i) (setf (aref z i) (char-code c)))
                   (setf p i)
                   t))
               (ch (i) (code-char (at i))))
        ;; Step 1a
        (when (char= (ch p) #\s)
          (unless (or (stem "sess" "ss" nil) (stem "sei" "i" nil) (stem "ss" "ss" nil))
            (incf p)))
        ;; Step 1b
        (let ((z2 p))
          (cond ((stem "dee" "ee" #'m-gt-0))
                ((and (or (stem "gni" "" #'has-vowel) (stem "de" "" #'has-vowel)) (/= p z2))
                 (cond ((or (stem "ta" "ate" nil) (stem "lb" "ble" nil) (stem "zi" "ize" nil)))
                       ((and (double-cons p) (not (member (ch p) '(#\l #\s #\z))))
                        (incf p))
                       ((and (m-eq-1 p) (star-oh p))
                        (decf p) (setf (aref z p) (char-code #\e)))))))
        ;; Step 1c
        (when (and (char= (ch p) #\y) (has-vowel (1+ p)))
          (setf (aref z p) (char-code #\i)))
        ;; Step 2
        (case (ch (1+ p))
          (#\a (or (stem "lanoita" "ate" #'m-gt-0) (stem "lanoit" "tion" #'m-gt-0)))
          (#\c (or (stem "icne" "ence" #'m-gt-0) (stem "icna" "ance" #'m-gt-0)))
          (#\e (stem "rezi" "ize" #'m-gt-0))
          (#\g (stem "igol" "log" #'m-gt-0))
          (#\l (or (stem "ilb" "ble" #'m-gt-0) (stem "illa" "al" #'m-gt-0)
                   (stem "iltne" "ent" #'m-gt-0) (stem "ile" "e" #'m-gt-0)
                   (stem "ilsuo" "ous" #'m-gt-0)))
          (#\o (or (stem "noitazi" "ize" #'m-gt-0) (stem "noita" "ate" #'m-gt-0)
                   (stem "rota" "ate" #'m-gt-0)))
          (#\s (or (stem "msila" "al" #'m-gt-0) (stem "ssenevi" "ive" #'m-gt-0)
                   (stem "ssenluf" "ful" #'m-gt-0) (stem "ssensuo" "ous" #'m-gt-0)))
          (#\t (or (stem "itila" "al" #'m-gt-0) (stem "itivi" "ive" #'m-gt-0)
                   (stem "itilib" "ble" #'m-gt-0))))
        ;; Step 3
        (case (ch p)
          (#\e (or (stem "etaci" "ic" #'m-gt-0) (stem "evita" "" #'m-gt-0) (stem "ezila" "al" #'m-gt-0)))
          (#\i (stem "itici" "ic" #'m-gt-0))
          (#\l (or (stem "laci" "ic" #'m-gt-0) (stem "luf" "" #'m-gt-0)))
          (#\s (stem "ssen" "" #'m-gt-0)))
        ;; Step 4
        (case (ch (1+ p))
          (#\a (when (and (char= (ch p) #\l) (m-gt-1 (+ p 2))) (incf p 2)))
          (#\c (when (and (char= (ch p) #\e) (char= (ch (+ p 2)) #\n)
                          (member (ch (+ p 3)) '(#\a #\e)) (m-gt-1 (+ p 4)))
                 (incf p 4)))
          (#\e (when (and (char= (ch p) #\r) (m-gt-1 (+ p 2))) (incf p 2)))
          (#\i (when (and (char= (ch p) #\c) (m-gt-1 (+ p 2))) (incf p 2)))
          (#\l (when (and (char= (ch p) #\e) (char= (ch (+ p 2)) #\b)
                          (member (ch (+ p 3)) '(#\a #\i)) (m-gt-1 (+ p 4)))
                 (incf p 4)))
          (#\n (when (char= (ch p) #\t)
                 (cond ((char= (ch (+ p 2)) #\a) (when (m-gt-1 (+ p 3)) (incf p 3)))
                       ((char= (ch (+ p 2)) #\e)
                        (or (stem "tneme" "" #'m-gt-1) (stem "tnem" "" #'m-gt-1) (stem "tne" "" #'m-gt-1))))))
          (#\o (cond ((char= (ch p) #\u) (when (m-gt-1 (+ p 2)) (incf p 2)))
                     ((member (ch (+ p 3)) '(#\s #\t)) (stem "noi" "" #'m-gt-1))))
          (#\s (when (and (char= (ch p) #\m) (char= (ch (+ p 2)) #\i) (m-gt-1 (+ p 3))) (incf p 3)))
          (#\t (or (stem "eta" "" #'m-gt-1) (stem "iti" "" #'m-gt-1)))
          (#\u (when (and (char= (ch p) #\s) (char= (ch (+ p 2)) #\o) (m-gt-1 (+ p 3))) (incf p 3)))
          ((#\v #\z) (when (and (char= (ch p) #\e) (char= (ch (+ p 2)) #\i) (m-gt-1 (+ p 3))) (incf p 3))))
        ;; Step 5a
        (when (char= (ch p) #\e)
          (cond ((m-gt-1 (1+ p)) (incf p))
                ((and (m-eq-1 (1+ p)) (not (star-oh (1+ p)))) (incf p))))
        ;; Step 5b
        (when (and (m-gt-1 p) (char= (ch p) #\l) (char= (ch (1+ p)) #\l))
          (incf p))
        (let ((len (or (position 0 z :start p) (length z))))
          (let ((s (make-string (- len p))))
            (loop for i from p below len
                  for j downfrom (- len p 1)
                  do (setf (char s j) (code-char (aref z i))))
            s))))))

(defun porter-delim-p (c)
  (and (< c #x80)
       (or (< c #x30)
           (let ((ch (code-char c)))
             (not (or (digit-char-p ch) (alpha-char-p ch) (char= ch #\_)))))))

(defun fts3-porter-tokenize (p n)
  (let ((off 0) (pos 0) (out '()))
    (loop while (< off n)
          do (loop while (and (< off n) (porter-delim-p (aref p off))) do (incf off))
             (let ((start off))
               (loop while (and (< off n) (not (porter-delim-p (aref p off)))) do (incf off))
               (when (> off start)
                 (push (list (porter-stem-bytes (subseq p start off) (- off start)) start off pos) out)
                 (incf pos))))
    (coerce (nreverse out) 'vector)))

;;; unicode61 (fts3_unicode.c, fts3_unicode2.c)

(defun fts3-unicode-isalnum (c)
  (cond ((< c 128)
         (zerop (logand (aref +fts3-isalnum-ascii+ (ash c -5)) (ash 1 (logand c 31)))))
        ((< c (ash 1 22))
         (let* ((key (logior (ash c 10) #x3ff))
                (e +fts3-isalnum-entries+)
                (lo 0) (hi (1- (length e))) (res 0))
           (loop while (>= hi lo)
                 do (let ((mid (floor (+ hi lo) 2)))
                      (if (>= key (aref e mid))
                          (setf res mid lo (1+ mid))
                          (setf hi (1- mid)))))
           (>= c (+ (ash (aref e res) -10) (logand (aref e res) #x3ff)))))
        (t t)))

(defun fts3-unicode-isdiacritic (c)
  (and (<= 768 c 817)
       (if (< c 800)
           (logbitp (- c 768) #x08029FDF)
           (logbitp (- c 800) #x000361F8))))

(defun fts3-remove-diacritic (c complex)
  (let* ((key (logior (ash c 3) 7))
         (d +fts3-dia-keys+)
         (lo 0) (hi (1- (length d))) (res 0))
    (loop while (>= hi lo)
          do (let ((mid (floor (+ hi lo) 2)))
               (if (>= key (aref d mid))
                   (setf res mid lo (1+ mid))
                   (setf hi (1- mid)))))
    (let ((ch (aref +fts3-dia-chars+ res)))
      (cond ((and (not complex) (logtest ch #x80)) c)
            ((> c (+ (ash (aref d res) -3) (logand (aref d res) 7))) c)
            (t (logand ch #x7f))))))

(defun fts3-unicode-fold (c remove-diacritic)
  (let ((ret c))
    (cond ((< c 128) (when (<= 65 c 90) (setf ret (+ c 32))))
          ((< c 65536)
           (let* ((e +fts3-fold-entries+)
                  (n (floor (length e) 3))
                  (lo 0) (hi (1- n)) (res -1))
             (loop while (>= hi lo)
                   do (let ((mid (floor (+ hi lo) 2)))
                        (if (>= (- c (aref e (* 3 mid))) 0)
                            (setf res mid lo (1+ mid))
                            (setf hi (1- mid)))))
             (let ((code (aref e (* 3 res))) (flags (aref e (+ 1 (* 3 res)))) (range (aref e (+ 2 (* 3 res)))))
               (when (and (< c (+ code range)) (zerop (logand 1 flags (logxor code c))))
                 (setf ret (logand (+ c (aref +fts3-fold-offsets+ (ash flags -1))) #xffff))))
             (when (plusp remove-diacritic)
               (setf ret (fts3-remove-diacritic ret (= remove-diacritic 2))))))
          ((and (>= c 66560) (< c 66600)) (setf ret (+ c 40))))
    ret))

(defun fts3-read-utf8 (b i end)
  "READ_UTF8: (values codepoint next-index)."
  (let ((c (aref b i)))
    (incf i)
    (when (>= c #xc0)
      (setf c (aref #(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31
                      0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 0 1 2 3 4 5 6 7 0 1 2 3 0 1 0 0)
                    (- c #xc0)))
      (loop while (and (< i end) (= (logand (aref b i) #xc0) #x80))
            do (setf c (+ (ash c 6) (logand #x3f (aref b i))))
               (incf i))
      (setf c (logand c #xffffffff))
      (when (or (< c #x80) (= (logand c #xFFFFF800) #xD800) (= (logand c #xFFFFFFFE) #xFFFE))
        (setf c #xfffd)))
    (values c i)))

(defun write-utf8-code (c out)
  (cond ((< c #x80) (vector-push-extend c out))
        ((< c #x800) (vector-push-extend (+ #xc0 (logand (ash c -6) #x1f)) out)
         (vector-push-extend (+ #x80 (logand c #x3f)) out))
        ((< c #x10000) (vector-push-extend (+ #xe0 (logand (ash c -12) #x0f)) out)
         (vector-push-extend (+ #x80 (logand (ash c -6) #x3f)) out)
         (vector-push-extend (+ #x80 (logand c #x3f)) out))
        (t (vector-push-extend (+ #xf0 (logand (ash c -18) #x07)) out)
           (vector-push-extend (+ #x80 (logand (ash c -12) #x3f)) out)
           (vector-push-extend (+ #x80 (logand (ash c -6) #x3f)) out)
           (vector-push-extend (+ #x80 (logand c #x3f)) out))))

(defun u61-add-exceptions (tk alnum text)
  (let* ((b (utf8-encode text)) (i 0) (ex (coerce (f3tok-exceptions tk) 'list)))
    (loop while (< i (length b))
          do (multiple-value-bind (c ni) (fts3-read-utf8 b i (length b))
               (setf i ni)
               (when (and (not (eq (fts3-unicode-isalnum c) alnum))
                          (not (fts3-unicode-isdiacritic c)))
                 (setf ex (merge 'list (list c) ex #'<)))))
    (setf (f3tok-exceptions tk) (coerce ex 'vector))))

(defun u61-alnum-p (tk c)
  (let ((a (fts3-unicode-isalnum c))
        (ex (and (plusp (length (f3tok-exceptions tk)))
                 (find c (f3tok-exceptions tk)))))
    (if ex (not a) a)))

(defun fts3-u61-tokenize (tk b n)
  (let ((off 0) (pos 0) (out '()) (rd (f3tok-diacritics tk)))
    (loop
      (let ((z off) (zstart off) (code 0))
        (loop while (< z n)
              do (multiple-value-bind (c nz) (fts3-read-utf8 b z n)
                   (setf code c z nz)
                   (when (u61-alnum-p tk c) (return))
                   (setf zstart z)))
        (when (>= zstart n) (return))
        (let ((tok (make-array 16 :element-type '(unsigned-byte 8) :fill-pointer 0 :adjustable t))
              (zend z))
          (loop
            (setf zend z)
            (let ((o (fts3-unicode-fold code rd)))
              (unless (zerop o) (write-utf8-code o tok)))
            (when (>= z n) (return))
            (multiple-value-bind (c nz) (fts3-read-utf8 b z n)
              (setf code c z nz))
            (unless (or (u61-alnum-p tk code) (fts3-unicode-isdiacritic code))
              (return)))
          (setf off z)
          (push (list (bytes-to-bstring tok) zstart zend pos) out)
          (incf pos))))
    (coerce (nreverse out) 'vector)))
