;;;; fts3-snippet.lisp — snippet(), offsets() and matchinfo() for FTS3/4
;;;; tables (fts3_snippet.c).

(in-package #:sqlite-pure)

(defun f3-get-delta-position (buf p pos)
  "fts3GetDeltaPosition: (values p pos)."
  (multiple-value-bind (v o) (f3-get-varint32 buf p) (values o (+ pos (- v 2)))))

(defun f3-column-bytes (cs col)
  "The UTF-8 bytes of column COL of the current row (full length), or NIL."
  (let ((v (nth col (second (f3-cursor-load-row cs)))))
    (cond ((or (null v) (eq v :null)) nil)
          ((blobp v) v)
          (t (utf8-encode (value-to-text v))))))

(defun f3-cstring-bytes (b start)
  "Bytes of B from START up to its first NUL (as appending a C string does)."
  (let ((z (position 0 b :start start)))
    (subseq b start (or z (length b)))))

;;; ------------------------------------------------------------------
;;; snippet()

(defstruct (f3sp) (ntoken 0) head-buf (head 0) (ihead 0) tail-buf (tail 0) (itail 0))

(defun f3-snippet-advance (buf p pos next)
  "fts3SnippetAdvance: (values buf p pos); BUF NIL once exhausted."
  (when buf
    (loop while (< pos next)
          do (when (zerop (logand (aref buf p) #xfe))
               (return-from f3-snippet-advance (values nil 0 -1)))
             (multiple-value-setq (p pos) (f3-get-delta-position buf p pos))))
  (values buf p pos))

(defun f3-best-snippet (cs nsnippet col covered)
  "fts3BestSnippet: (values fragment score seen-mask); a fragment is
(col pos covered hlmask)."
  (let* ((phrases (f3-expr-phrases (cs-expr cs)))
         (sps (map 'vector (lambda (x)
                             (let ((sp (make-f3sp :ntoken (length (ph-tokens (fx-phrase x))))))
                               (multiple-value-bind (buf p) (f3-eval-phrase-poslist cs x col)
                                 (when buf
                                   (multiple-value-bind (p2 first) (f3-get-delta-position buf p 0)
                                     (when (< first 0) (corrupt "database disk image is malformed"))
                                     (setf (f3sp-head-buf sp) buf (f3sp-head sp) p2 (f3sp-ihead sp) first
                                           (f3sp-tail-buf sp) buf (f3sp-tail sp) p2 (f3sp-itail sp) first))))
                               sp))
                   phrases))
         (seen 0) (best -1) (frag (list col 0 0 0)) (current -1))
    (loop for sp across sps for i from 0
          do (when (f3sp-head-buf sp) (setf seen (logior seen (ash 1 (mod i 64))))))
    (flet ((next-candidate ()
             (if (< current 0)
                 (progn (setf current 0)
                        (loop for sp across sps
                              do (multiple-value-bind (b p pos)
                                     (f3-snippet-advance (f3sp-head-buf sp) (f3sp-head sp) (f3sp-ihead sp) nsnippet)
                                   (setf (f3sp-head-buf sp) b (f3sp-head sp) p (f3sp-ihead sp) pos)))
                        nil)
                 (let ((iend #x7fffffff))
                   (loop for sp across sps
                         do (when (and (f3sp-head-buf sp) (< (f3sp-ihead sp) iend)) (setf iend (f3sp-ihead sp))))
                   (if (= iend #x7fffffff)
                       t
                       (let ((istart (+ (- iend nsnippet) 1)))
                         (setf current istart)
                         (loop for sp across sps
                               do (multiple-value-bind (b p pos)
                                      (f3-snippet-advance (f3sp-head-buf sp) (f3sp-head sp) (f3sp-ihead sp) (1+ iend))
                                    (setf (f3sp-head-buf sp) b (f3sp-head sp) p (f3sp-ihead sp) pos))
                                  (multiple-value-bind (b p pos)
                                      (f3-snippet-advance (f3sp-tail-buf sp) (f3sp-tail sp) (f3sp-itail sp) istart)
                                    (setf (f3sp-tail-buf sp) b (f3sp-tail sp) p (f3sp-itail sp) pos)))
                         nil))))))
      (loop until (next-candidate)
            do (let ((istart current) (score 0) (mcover 0) (mhl 0))
                 (loop for sp across sps for i from 0
                       do (when (f3sp-tail-buf sp)
                            (let ((buf (f3sp-tail-buf sp)) (p (f3sp-tail sp)) (pos (f3sp-itail sp)))
                              (loop while (and (< pos (+ istart nsnippet)) (>= pos istart))
                                    do (let ((mphrase (ash 1 (mod i 64)))
                                             (mpos (ash 1 (- pos istart))))
                                         (incf score (if (logtest (logior mcover covered) mphrase) 1 1000))
                                         (setf mcover (logior mcover mphrase))
                                         (loop for j from 0 below (min (f3sp-ntoken sp) nsnippet)
                                               do (setf mhl (logior mhl (ash mpos (- j))))))
                                       (when (zerop (logand (aref buf p) #xfe)) (return))
                                       (multiple-value-setq (p pos) (f3-get-delta-position buf p pos))))))
                 (when (> score best)
                   (setf best score frag (list col istart mcover (ldb (byte 64 0) mhl)))))))
    (values frag best seen)))

(defun f3-snippet-shift (f nsnippet bytes start pos hlmask)
  "fts3SnippetShift: (values pos hlmask)."
  (if (zerop hlmask)
      (values pos hlmask)
      (let ((nleft 0) (nright 0))
        (loop until (logbitp nleft hlmask) do (incf nleft))
        (loop until (logbitp (- nsnippet 1 nright) hlmask) do (incf nright))
        (let ((desired (truncate (- nleft nright) 2)))
          (if (<= desired 0)
              (values pos hlmask)
              (let* ((toks (fts3-tokenize (f3-tokenizer f) (subseq bytes start)))
                     (current 0) (done nil) (k 0))
                (loop while (< current (+ nsnippet desired))
                      do (if (< k (length toks))
                             (progn (setf current (fourth (aref toks k))) (incf k))
                             (progn (setf done t) (return))))
                (let ((shift (+ (if done 1 0) current (- nsnippet))))
                  (if (> shift 0)
                      (values (+ pos shift) (ash hlmask (- shift)))
                      (values pos hlmask)))))))))

(defvar *f3-snippet-appended* nil)

(defun f3-snippet-text (cs frag ifrag last-p nsnippet open close ellipsis out)
  "fts3SnippetText: append the fragment's text to OUT (a byte buffer)."
  (destructuring-bind (col ipos covered hlmask) frag
    (declare (ignore covered))
    (let ((doc (f3-column-bytes cs col)) (f (cs-fts cs)))
      (when doc
        (let ((toks (fts3-tokenize (f3-tokenizer f) doc))
              (iend 0) (shift-done nil) (k 0))
          (flet ((app (b &optional (s 0) (e (length b)))
                   ;; (any append, even of nothing, makes the result non-NULL)
                   (setf *f3-snippet-appended* t)
                   (f3-buf-append out b s e)))
            (loop
              (when (>= k (length toks))
                (app (f3-cstring-bytes doc iend))
                (return))
              (destructuring-bind (term ibegin ifin icurrent) (aref toks k)
                (declare (ignore term))
                (incf k)
                (block this
                  (when (< icurrent ipos) (return-from this))
                  (unless shift-done
                    (multiple-value-setq (ipos hlmask) (f3-snippet-shift f nsnippet doc ibegin ipos hlmask))
                    (setf shift-done t)
                    (cond ((or (> ipos 0) (> ifrag 0)) (app ellipsis))
                          ((/= ibegin 0) (app doc 0 ibegin)))
                    (when (< icurrent ipos) (return-from this)))
                  (when (>= icurrent (+ ipos nsnippet))
                    (when last-p (app ellipsis))
                    (return))
                  (let ((hl (logbitp (- icurrent ipos) hlmask)))
                    (when (> icurrent ipos)
                      (if (< ibegin iend)       ; (a negative length appends to the end, as in C)
                          (app (f3-cstring-bytes doc iend))
                          (app doc iend ibegin)))
                    (when hl (app open))
                    (app doc ibegin ifin)
                    (when hl (app close))
                    (setf iend ifin)))))))))))

(defun f3-snippet (cs open close ellipsis icol ntoken)
  (let ((f (cs-fts cs)))
    (if (null (cs-expr cs))
        ""
        (let ((ntoken (max -64 (min 64 ntoken)))
              (frags nil) (nfragtok -1) (nsnippet 1)
              (open (utf8-encode open)) (close (utf8-encode close)) (ellipsis (utf8-encode ellipsis)))
          (loop
            (let ((covered 0) (seen 0) (fs '()))
              (setf nfragtok (if (>= ntoken 0) (floor (+ ntoken nsnippet -1) nsnippet) (- ntoken)))
              (dotimes (isnip nsnippet)
                (let ((best -1) (frag (list 0 0 0 0)))
                  (dotimes (iread (f3-ncol f))
                    (unless (and (>= icol 0) (/= iread icol))
                      (multiple-value-bind (sf score sn) (f3-best-snippet cs nfragtok iread covered)
                        (setf seen (logior seen sn))
                        (when (> score best) (setf frag sf best score)))))
                  (push frag fs)
                  (setf covered (logior covered (third frag)))))
              (setf frags (nreverse fs))
              (when (or (= seen covered) (= nsnippet 4)) (return))
              (incf nsnippet)))
          (let ((out (f3-buf 128)) (*f3-snippet-appended* nil))
            (loop for frag in frags
                  for i from 0
                  do (f3-snippet-text cs frag i (= i (1- (length frags))) nfragtok open close ellipsis out))
            (if (not *f3-snippet-appended*)
                :null                   ; (an empty StrBuffer is a NULL result)
                (utf8-decode-lenient (coerce out 'octets))))))))

;;; ------------------------------------------------------------------
;;; offsets()

(defun f3-offsets (cs)
  (let* ((f (cs-fts cs)) (x (cs-expr cs)))
    (if (null x)
        ""
        (let* ((phrases (f3-expr-phrases x))
               (ntoken (reduce #'+ phrases :key (lambda (p) (length (ph-tokens (fx-phrase p))))))
               (terms (make-array ntoken))
               (out (make-string-output-stream)) (any nil))
          (dotimes (col (f3-ncol f))
            (let ((k 0))
              (dolist (px phrases)
                (let ((nterm (length (ph-tokens (fx-phrase px)))) (pos 0))
                  (multiple-value-bind (buf p) (f3-eval-phrase-poslist cs px col)
                    (when buf (multiple-value-setq (p pos) (f3-get-delta-position buf p 0)))
                    (dotimes (it nterm)
                      (setf (aref terms k) (list buf p pos (- nterm it 1)))
                      (incf k))))))
            (let ((doc (f3-column-bytes cs col)))
              (when doc
                (let ((toks (fts3-tokenize (f3-tokenizer f) doc)) (ti 0))
                  (when (plusp (length toks))
                    (let ((cur (aref toks 0)))
                      (setf ti 1)
                      (loop
                        (let ((minpos #x7fffffff) (best nil))
                          (loop for tm across terms
                                for i from 0
                                do (when (and (first tm) (< (- (third tm) (fourth tm)) minpos))
                                     (setf minpos (- (third tm) (fourth tm)) best i)))
                          (unless best (return))
                          (let ((tm (aref terms best)))
                            (if (zerop (logand #xfe (aref (first tm) (second tm))))
                                (setf (first tm) nil)
                                (multiple-value-bind (p pos) (f3-get-delta-position (first tm) (second tm) (third tm))
                                  (setf (second tm) p (third tm) pos))))
                          (loop while (and cur (< (fourth cur) minpos))
                                do (setf cur (if (< ti (length toks)) (prog1 (aref toks ti) (incf ti)) nil)))
                          (cond (cur
                                 (format out "~d ~d ~d ~d " col best (second cur) (- (third cur) (second cur)))
                                 (setf any t))
                                ((null (f3-content f)) (corrupt "database disk image is malformed"))
                                (t (return)))))))))))
          (let ((s (get-output-stream-string out)))
            (if any (subseq s 0 (1- (length s))) :null))))))

;;; ------------------------------------------------------------------
;;; matchinfo()

(defun f3-matchinfo-size (c ncol nphrase)
  (case c
    ((#\n #\p #\c) 1)
    ((#\a #\l #\s) ncol)
    (#\y (* ncol nphrase))
    (#\b (* nphrase (floor (+ ncol 31) 32)))
    (t (* ncol nphrase 3))))

(defun f3-doctotal (f)
  "(values ndoc blob offset-after-ndoc)"
  (let* ((r (f3-stat-get f 0)) (a (and r (first r))))
    (unless (and a (blobp a)) (corrupt "database disk image is malformed"))
    (let ((p (f3-padded a)))
      (multiple-value-bind (ndoc o) (f3-get-varint-bounded p 0 (length a))
        (when (or (<= ndoc 0) (> o (length a))) (corrupt "database disk image is malformed"))
        (values ndoc p o (length a))))))

(defun f3-columnlist-count (buf p)
  (let ((c 0) (n 0))
    (loop while (/= 0 (logand #xfe (logior (aref buf p) c)))
          do (setf c (logand (aref buf p) #x80))
             (incf p)
             (when (zerop c) (incf n)))
    (values n p)))

(defun f3-matchinfo-lcs (cs phrases ncol out base)
  (let* ((n (length phrases))
         (offsets (let ((ntok 0))
                    (map 'vector (lambda (px) (decf ntok (length (ph-tokens (fx-phrase px)))) ntok) phrases))))
    (dotimes (col ncol)
      (let ((nlcs 0) (live 0)
            (its (make-array n)))
        (loop for px in phrases for i from 0
              do (multiple-value-bind (buf p) (f3-eval-phrase-poslist cs px col)
                   (if buf
                       (let ((it (list buf p (aref offsets i))))
                         ;; advance once
                         (multiple-value-bind (v o) (f3-get-varint buf p)
                           (if (or (= v 0) (= v 1))
                               (corrupt "database disk image is malformed")
                               (setf (second it) o (third it) (+ (third it) (- v 2)))))
                         (setf (aref its i) it)
                         (incf live))
                       (setf (aref its i) nil))))
        (loop while (> live 0)
              do (let ((adv nil) (this 0))
                   (dotimes (i n)
                     (let ((it (aref its i)))
                       (if (or (null it) (null (first it)))
                           (setf this 0)
                           (progn
                             (when (or (null adv) (< (third it) (third adv))) (setf adv it))
                             (if (or (zerop this)
                                     (and (> i 0) (aref its (1- i)) (= (third it) (third (aref its (1- i))))))
                                 (incf this)
                                 (setf this 1))
                             (when (> this nlcs) (setf nlcs this))))))
                   (multiple-value-bind (v o) (f3-get-varint (first adv) (second adv))
                     (if (or (= v 0) (= v 1))
                         (progn (setf (first adv) nil) (decf live))
                         (setf (second adv) o (third adv) (+ (third adv) (- v 2)))))))
        (setf (aref out (+ base col)) nlcs)))))

(defun f3-matchinfo (cs format)
  (let* ((f (cs-fts cs)) (x (cs-expr cs)))
    (when (null x) (return-from f3-matchinfo (make-octets 0)))
    (let* ((ncol (f3-ncol f))
           (phrases (f3-expr-phrases x))
           (nphrase (length phrases))
           (global (not (equal format (cs-mi-format cs)))))
      (loop for px in phrases for i from 0 do (setf (fx-iphrase px) i))
      (loop for c across format
            do (unless (or (member c '(#\p #\c #\s #\x #\y #\b))
                           (and (member c '(#\n #\a)) (f3-fts4-p f))
                           (and (char= c #\l) (f3-has-docsize f)))
                 (sql-error "unrecognized matchinfo request: ~c" c)))
      (let* ((nelem (loop for c across format sum (f3-matchinfo-size c ncol nphrase)))
             (out (if global (make-array nelem :initial-element 0) (copy-seq (cs-mi-global cs))))
             (base 0))
        (loop for c across format
              do (case c
                   (#\p (when global (setf (aref out base) nphrase)))
                   (#\c (when global (setf (aref out base) ncol)))
                   (#\n (when global (setf (aref out base) (logand (f3-doctotal f) #xffffffff))))
                   (#\a (when global
                          (multiple-value-bind (ndoc p o end) (f3-doctotal f)
                            (dotimes (col ncol)
                              (multiple-value-bind (ntok o2) (f3-get-varint p o)
                                (setf o o2)
                                (when (> o end) (corrupt "database disk image is malformed"))
                                (setf (aref out (+ base col))
                                      (logand (floor (+ (logand ntok #xffffffff) (floor ndoc 2)) ndoc) #xffffffff)))))))
                   (#\l (let* ((r (shadow-get (f3-shadow f "docsize") (cs-prev-id cs))) (a (and r (first r))))
                          (unless (blobp a) (corrupt "database disk image is malformed"))
                          (let ((p (f3-padded a)) (o 0))
                            (dotimes (col ncol)
                              (multiple-value-bind (ntok o2) (f3-get-varint-bounded p o (length a))
                                (setf o o2)
                                (when (> o (length a)) (corrupt "database disk image is malformed"))
                                (setf (aref out (+ base col)) (logand ntok #xffffffff)))))))
                   (#\s (f3-matchinfo-lcs cs phrases ncol out base))
                   ((#\y #\b)
                    (fill out 0 :start base :end (+ base (f3-matchinfo-size c ncol nphrase)))
                    (labels ((gather (e)
                               (when (and (not (fx-eof e)) (= (fx-docid e) (cs-prev-id cs)))
                                 (if (fx-left e)
                                     (progn (gather (fx-left e)) (gather (fx-right e)))
                                     (let* ((ph (fx-phrase e)) (buf (ph-list-buf ph)) (p (ph-list-off ph)) (col 0)
                                            (start (if (char= c #\y) (* (fx-iphrase e) ncol) (* (fx-iphrase e) (floor (+ ncol 31) 32)))))
                                       (when buf
                                         (loop
                                           (multiple-value-bind (nhit np) (f3-columnlist-count buf p)
                                             (setf p np)
                                             (when (or (>= (ph-column ph) ncol) (= (ph-column ph) col))
                                               (if (char= c #\y)
                                                   (setf (aref out (+ base start col)) nhit)
                                                   (when (plusp nhit)
                                                     (let ((k (+ base start (floor (1+ col) 32))))
                                                       (setf (aref out k) (logior (aref out k) (ash 1 (logand col 31)))))))))
                                           (unless (= (aref buf p) 1) (return))
                                           (incf p)
                                           (multiple-value-setq (col p) (f3-get-varint32 buf p))
                                           (when (>= col ncol) (corrupt "database disk image is malformed")))))))))
                      (gather x)))
                   (t ;; x
                    (when global
                      (when (cs-deferred cs) (setf (cs-ndoc cs) (f3-doctotal f)))
                      (dolist (px phrases)
                        (let ((st (f3-eval-phrase-stats cs px))
                              (s (+ base (* 3 (fx-iphrase px) ncol))))
                          (dotimes (col ncol)
                            (setf (aref out (+ s (* col 3) 1)) (aref st (* 2 col))
                                  (aref out (+ s (* col 3) 2)) (aref st (1+ (* 2 col)))))))
                      (f3-eval-test-deferred cs))
                    (dolist (px phrases)
                      (let ((s (+ base (* 3 (fx-iphrase px) ncol))))
                        (dotimes (col ncol)
                          (multiple-value-bind (buf p) (f3-eval-phrase-poslist cs px col)
                            (setf (aref out (+ s (* col 3)))
                                  (if buf (f3-columnlist-count buf p) 0))))))))
                 (incf base (f3-matchinfo-size c ncol nphrase)))
        (when global
          (setf (cs-mi-format cs) format (cs-mi-global cs) (copy-seq out)))
        (let ((b (make-octets (* 4 nelem))))
          (loop for v across out for i from 0
                do (let ((u (logand v #xffffffff)))
                     (setf (aref b (* 4 i)) (ldb (byte 8 0) u)
                           (aref b (+ 1 (* 4 i))) (ldb (byte 8 8) u)
                           (aref b (+ 2 (* 4 i))) (ldb (byte 8 16) u)
                           (aref b (+ 3 (* 4 i))) (ldb (byte 8 24) u))))
          b)))))
