;;;; integrity.lisp — PRAGMA integrity_check: every page accounted for
;;;; exactly once, b-tree keys in order, index entries matching table rows.

(in-package #:sqlite-pure)

(defun integrity-check (db)
  (let* ((*db* db) (*encoding* (db-encoding db))
         (problems '())
         (npages (db-page-count db))
         (owner (make-array (1+ npages) :initial-element nil))
         (current-root nil)
         (leaf-depth nil))
    (when (zerop npages) (return-from integrity-check nil))
    (labels ((problem (fmt &rest args)
               (push (apply #'format nil fmt args) problems))
             (claim (pg what)
               (cond ((or (< pg 1) (> pg npages))
                      (problem "~a: page ~d out of range" what pg) nil)
                     ((aref owner pg)
                      (problem "~a: page ~d already used by ~a" what pg (aref owner pg)) nil)
                     (t (setf (aref owner pg) what) t)))
             (check-overflow (first psize local what)
               (let ((need (- psize local)) (pg first) (cap (- (db-usable-size db) 4)))
                 (loop while (plusp need)
                       do (unless (claim pg what) (return))
                          (decf need (min need cap))
                          (setf pg (get-u32 (read-page db pg) 0)))
                 (when (plusp pg) (problem "~a: overflow chain too long" what))))
             (walk (pgno what lo hi depth index-cmp count)
               ;; Table b-trees: every rowid must be in (lo, hi].  Index
               ;; b-trees: entries in order via INDEX-CMP.  Returns the last
               ;; key seen.
               (when (> depth 40) (problem "~a: tree too deep" what) (return-from walk nil))
               (unless (claim pgno what) (return-from walk nil))
               (let* ((b (read-page db pgno))
                      (off (hdr-off pgno))
                      (type (aref b off))
                      (n (page-ncells b off))
                      (last lo))
                 (unless (member type '(2 5 10 13))
                   (problem "~a: page ~d has bad type ~d" what pgno type)
                   (return-from walk nil))
                 (when (and (zerop n) (/= pgno current-root) (leaf-type-p type))
                   (problem "~a: page ~d is an empty non-root leaf" what pgno))
                 (when (leaf-type-p type)
                   (cond ((null leaf-depth) (setf leaf-depth depth))
                         ((/= leaf-depth depth)
                          (problem "~a: child page depth differs at page ~d" what pgno))))
                 (dotimes (i n)
                   (let ((p (cell-ptr b off type i)))
                     (when (>= (+ p 4) (+ (db-usable-size db) 1))
                       (problem "~a: page ~d cell ~d out of bounds" what pgno i))
                     (ecase type
                       (#.+leaf-table+
                        (multiple-value-bind (psize n1) (get-varint b p)
                          (multiple-value-bind (rowid n2) (get-varint-signed b (+ p n1))
                            (let ((local (local-size db psize t)))
                              (when (< local psize)
                                (check-overflow (get-u32 b (+ p n1 n2 local)) psize local what)))
                            (when (and last (<= rowid last))
                              (problem "~a: rowid ~d out of order on page ~d" what rowid pgno))
                            (when (and hi (> rowid hi))
                              (problem "~a: rowid ~d above parent bound on page ~d" what rowid pgno))
                            (incf (car count))
                            (setf last rowid))))
                       (#.+interior-table+
                        (let ((child (get-u32 b p))
                              (key (get-varint-signed b (+ p 4))))
                          (when (and last (< key last))
                            (problem "~a: key ~d out of order on page ~d" what key pgno))
                          (walk child what last key (1+ depth) index-cmp count)
                          (setf last key)))
                       ((#.+leaf-index+ #.+interior-index+)
                        (let* ((q (if (= type +interior-index+) (+ p 4) p)))
                          (multiple-value-bind (psize n1) (get-varint b q)
                            (let ((local (local-size db psize nil)))
                              (when (< local psize)
                                (check-overflow (get-u32 b (+ q n1 local)) psize local what))
                              (let ((vals (ignore-errors
                                           (decode-record (read-payload db b (+ q n1) psize local)))))
                                (when (= type +interior-index+)
                                  (setf last (walk (get-u32 b p) what last vals (1+ depth) index-cmp count)))
                                (when (and index-cmp last vals (>= (funcall index-cmp last vals) 0))
                                  (problem "~a: entries out of order on page ~d" what pgno))
                                (when (and index-cmp hi vals (> (funcall index-cmp vals hi) 0))
                                  (problem "~a: entry above parent bound on page ~d" what pgno))
                                (incf (car count))
                                (setf last vals)))))))))
                 (unless (leaf-type-p type)
                   (setf last (walk (get-u32 b (+ off 8)) what last hi (1+ depth) index-cmp count)))
                 last)))
      (progn
        (flet ((tree (root what &optional cmp)
                 (setf current-root root leaf-depth nil)
                 (let ((count (list 0)))
                   (handler-case (walk root what nil nil 0 cmp count)
                     (error (e) (problem "~a: ~a" what e)))
                   (car count))))
          ;; freelist
          (let ((trunk (header-u32 db +hdr-freelist-trunk+))
                (expected (header-u32 db +hdr-freelist-count+))
                (seen 0))
            (loop while (plusp trunk)
                  do (unless (claim trunk "freelist") (return))
                     (incf seen)
                     (let* ((tb (read-page db trunk))
                            (nl (get-u32 tb 4)))
                       (if (> nl (- (floor (db-usable-size db) 4) 2))
                           (progn (problem "freelist trunk ~d: bad leaf count ~d" trunk nl) (return))
                           (dotimes (i nl)
                             (when (claim (get-u32 tb (+ 8 (* 4 i))) "freelist") (incf seen))))
                       (setf trunk (get-u32 tb 0))))
            (unless (= seen expected)
              (problem "freelist count is ~d but ~d pages are on the freelist" expected seen)))
          (tree 1 "sqlite_schema")
          (let ((schema (handler-case (load-schema db)
                          (error (e) (problem "schema: ~a" e) nil))))
            (when schema
              (maphash
               (lambda (k tb)
                 (unless (or (string= k "sqlite_master") (string= k "sqlite_schema")
                             (table-view-select tb))
                   (let* ((pk (find-if #'index-pk-index (table-indexes tb)))
                          (nrows (tree (table-root tb) (table-name tb)
                                       (and pk (index-full-cmp tb pk))))
                          (rows (handler-case (let ((out '()))
                                                (map-table-rows tb (lambda (r) (push r out)))
                                                out)
                                  (error (e) (problem "~a: ~a" (table-name tb) e) nil))))
                     (dolist (idx (table-indexes tb))
                       (unless (index-pk-index idx)
                         (let* ((cmp (index-full-cmp tb idx))
                                (nentries (tree (index-root idx) (index-name idx) cmp))
                                (expected (count-if (lambda (r) (index-applies-p tb idx r)) rows)))
                           (unless (= nentries expected)
                             (problem "wrong # of entries in index ~a (~d, expected ~d)"
                                      (index-name idx) nentries expected))
                           (let ((*index-cmp* cmp))
                             (dolist (r rows)
                               (when (index-applies-p tb idx r)
                                 (let ((key (index-key tb idx r)) (found nil))
                                   (catch :found
                                     (map-index db (index-root idx)
                                                (lambda (v) (setf found (zerop (funcall cmp v key)))
                                                  (throw :found nil))
                                                :probe key :cmp cmp))
                                   (unless found
                                     (problem "row ~a missing from index ~a"
                                              (svref r (1- (length r))) (index-name idx))
                                     (return)))))))))
                     nrows)))
               (schema-tables schema))))
          ;; auto-vacuum: pointer-map pages are used, and must be right
          (when (autovacuum-p db)
            (loop for pg from 2 to npages
                  do (when (ptrmap-page-p db pg) (claim pg "pointer map")))
            (dolist (p (ptrmap-problems db)) (problem "~a" p)))
          ;; every page used exactly once
          (loop for pg from 1 to npages
                do (unless (or (aref owner pg) (= pg (pending-byte-page db)))
                     (problem "page ~d is never used" pg))))))
    (nreverse problems)))
