;;;; parser.lisp — recursive-descent SQL parser producing list ASTs.
;;;;
;;;; Expressions:
;;;;   (:lit v) (:param key) (:col table name) (:star table)
;;;;   (:unary op e)            op in :neg :pos :bitnot :not
;;;;   (:binary op a b)         :or :and :eq :ne :lt :le :gt :ge :is :isnot
;;;;                            :concat :add :sub :mul :div :mod
;;;;                            :bitand :bitor :shl :shr
;;;;   (:like kind e pat esc negated)   kind :like | :glob
;;;;   (:between e lo hi negated) (:in e rhs negated) (:isnull e negated)
;;;;   (:case base ((when then) ...) else) (:cast e type) (:collate e name)
;;;;   (:fn name args distinct star filter) (:subquery sel) (:exists sel)
;;;;   (:rowvalue e...)

(in-package #:sqlite-pure)

(defstruct (parser (:conc-name ps-))
  sql toks (pos 0) (nparam 0) (names '()))

(defstruct select-core
  distinct cols from where group having windows)

(defstruct sel
  with       ; list of (name columns select) ; recursive flag in RECURSIVE
  recursive
  cores      ; list of select-core (or (:values rows))
  ops        ; compound operators between cores: :union :union-all :intersect :except
  order      ; list of (expr desc collate nulls)
  limit offset)

(defun peek-tok (p &optional (k 0))
  (let ((toks (ps-toks p)))
    (aref toks (min (+ (ps-pos p) k) (1- (length toks))))))

(defun next-tok (p)
  (prog1 (peek-tok p) (incf (ps-pos p))))

(defun perr (p fmt &rest args)
  (if (eq (tok-kind (peek-tok p)) :eof)
      (error 'sqlite-parse-error :message "incomplete input")
      (apply #'parse-error-at (ps-sql p) (tok-pos (peek-tok p)) fmt args)))

(defun kw-tok-p (tok kw)
  (and (eq (tok-kind tok) :id) (not (tok-quoted tok)) (name= (tok-value tok) kw)))

(defun kw-p (p kw &optional (k 0)) (kw-tok-p (peek-tok p k) kw))

(defun accept-kw (p &rest kws)
  "If the next tokens are the keywords KWS, consume them and return T."
  (when (loop for kw in kws for k from 0 always (kw-p p kw k))
    (incf (ps-pos p) (length kws))
    t))

(defun expect-kw (p &rest kws)
  (unless (apply #'accept-kw p kws) (perr p "expected ~{~a~^ ~}" kws)))

(defun op-p (p op &optional (k 0))
  (let ((tok (peek-tok p k)))
    (and (eq (tok-kind tok) :op) (string= (tok-value tok) op))))

(defun accept-op (p op) (when (op-p p op) (incf (ps-pos p)) t))
(defun expect-op (p op) (unless (accept-op p op) (perr p "expected ~s" op)))

(defparameter +reserved+
  '("ADD" "ALL" "ALTER" "AND" "AS" "AUTOINCREMENT" "BETWEEN" "CASE" "CHECK" "COLLATE"
    "COMMIT" "CONSTRAINT" "CREATE" "DEFAULT" "DEFERRABLE" "DELETE" "DISTINCT" "DROP"
    "ELSE" "END" "ESCAPE" "EXCEPT" "EXISTS" "FOREIGN" "FROM" "GLOB" "GROUP" "HAVING" "IN"
    "INDEX" "INSERT" "INTERSECT" "INTO" "IS" "ISNULL" "JOIN" "LIKE" "LIMIT" "NOT"
    "NOTNULL" "NULL" "ON" "OR" "ORDER" "PRIMARY" "REFERENCES" "SELECT" "SET" "TABLE"
    "THEN" "TO" "TRANSACTION" "UNION" "UNIQUE" "UPDATE" "USING" "VALUES" "WHEN" "WHERE"
    "LEFT" "INNER" "CROSS" "NATURAL" "OUTER" "RIGHT" "FULL" "OFFSET" "RETURNING"
    "WINDOW" "FILTER" "OVER" "REGEXP" "MATCH"))

(defun reserved-p (name)
  (member name +reserved+ :test #'name=))

(defun name-token-p (tok &optional allow-reserved)
  (and (eq (tok-kind tok) :id)
       (or (tok-quoted tok) allow-reserved (not (reserved-p (tok-value tok))))))

(defun parse-name (p &optional allow-reserved)
  (let ((tok (peek-tok p)))
    (cond ((name-token-p tok allow-reserved) (next-tok p) (tok-value tok))
          ((eq (tok-kind tok) :string) (next-tok p) (tok-value tok))
          (t (perr p "expected a name")))))

(defun parse-qualified-name (p)
  "[schema.]name -> (values name schema)"
  (let ((a (parse-name p t)))
    (if (op-p p ".")
        (progn (next-tok p) (values (parse-name p t) a))
        (values a nil))))

;;; ------------------------------------------------------------------
;;; Expressions

(defun parse-expr (p) (parse-or p))

(defun parse-or (p)
  (let ((e (parse-and p)))
    (loop while (accept-kw p "OR") do (setf e (list :binary :or e (parse-and p))))
    e))

(defun parse-and (p)
  (let ((e (parse-not p)))
    (loop while (accept-kw p "AND") do (setf e (list :binary :and e (parse-not p))))
    e))

(defun parse-not (p)
  (if (and (kw-p p "NOT") (not (kw-p p "EXISTS" 1)))
      (progn (next-tok p) (list :unary :not (parse-not p)))
      (parse-equality p)))

(defun parse-equality (p)
  (let ((e (parse-comparison p)))
    (loop
      (let ((negated nil))
        (cond ((or (accept-op p "=") (accept-op p "=="))
               (setf e (list :binary :eq e (parse-comparison p))))
              ((or (accept-op p "!=") (accept-op p "<>"))
               (setf e (list :binary :ne e (parse-comparison p))))
              ((accept-kw p "IS")
               (let ((neg (accept-kw p "NOT")))
                 (when (accept-kw p "DISTINCT") (expect-kw p "FROM") (setf neg (not neg)))
                 (setf e (list :binary (if neg :isnot :is) e (parse-comparison p)))))
              ((accept-kw p "ISNULL") (setf e (list :isnull e nil)))
              ((accept-kw p "NOTNULL") (setf e (list :isnull e t)))
              ((and (kw-p p "NOT") (kw-p p "NULL" 1))
               (incf (ps-pos p) 2) (setf e (list :isnull e t)))
              ((progn (setf negated (and (kw-p p "NOT")
                                         (or (kw-p p "IN" 1) (kw-p p "LIKE" 1) (kw-p p "GLOB" 1)
                                             (kw-p p "BETWEEN" 1) (kw-p p "REGEXP" 1)
                                             (kw-p p "MATCH" 1))))
                      (when negated (next-tok p))
                      (accept-kw p "IN"))
               (setf e (list :in e (parse-in-rhs p) negated)))
              ((or (kw-p p "LIKE") (kw-p p "GLOB"))
               (let* ((kind (if (kw-p p "GLOB") :glob :like))
                      (pat (progn (next-tok p) (parse-comparison p)))
                      (esc (when (accept-kw p "ESCAPE") (parse-comparison p))))
                 (setf e (list :like kind e pat esc negated))))
              ((or (kw-p p "REGEXP") (kw-p p "MATCH"))
               (let* ((fname (string-downcase-ascii (tok-value (next-tok p))))
                      (pat (parse-comparison p)))
                 (setf e (list :fn fname (list pat e) nil nil nil))
                 (when negated (setf e (list :unary :not e)))))
              ((accept-kw p "BETWEEN")
               (let ((lo (parse-comparison p)))
                 (expect-kw p "AND")
                 (setf e (list :between e lo (parse-comparison p) negated))))
              (t (when negated (perr p "syntax error")) (return e)))))))

(defun parse-in-rhs (p)
  (cond ((accept-op p "(")
         (cond ((accept-op p ")") (list :list '()))
               ((or (kw-p p "SELECT") (kw-p p "WITH") (kw-p p "VALUES"))
                (prog1 (list :select (parse-select p)) (expect-op p ")")))
               (t (let ((items (list (parse-expr p))))
                    (loop while (accept-op p ",") do (push (parse-expr p) items))
                    (expect-op p ")")
                    (list :list (nreverse items))))))
        (t (multiple-value-bind (name schema) (parse-qualified-name p)
             (declare (ignore schema))
             (list :table name)))))

(defun parse-comparison (p)
  (let ((e (parse-bitwise p)))
    (loop (let ((op (cond ((accept-op p "<") :lt) ((accept-op p "<=") :le)
                          ((accept-op p ">") :gt) ((accept-op p ">=") :ge))))
            (if op (setf e (list :binary op e (parse-bitwise p))) (return e))))))

(defun parse-bitwise (p)
  (let ((e (parse-additive p)))
    (loop (let ((op (cond ((accept-op p "&") :bitand) ((accept-op p "|") :bitor)
                          ((accept-op p "<<") :shl) ((accept-op p ">>") :shr))))
            (if op (setf e (list :binary op e (parse-additive p))) (return e))))))

(defun parse-additive (p)
  (let ((e (parse-multiplicative p)))
    (loop (let ((op (cond ((accept-op p "+") :add) ((accept-op p "-") :sub))))
            (if op (setf e (list :binary op e (parse-multiplicative p))) (return e))))))

(defun parse-multiplicative (p)
  (let ((e (parse-concat p)))
    (loop (let ((op (cond ((accept-op p "*") :mul) ((accept-op p "/") :div)
                          ((accept-op p "%") :mod))))
            (if op (setf e (list :binary op e (parse-concat p))) (return e))))))

(defun parse-concat (p)
  (let ((e (parse-unary p)))
    (loop (cond ((accept-op p "||") (setf e (list :binary :concat e (parse-unary p))))
                ((accept-op p "->") (setf e (list :fn "json_extract_arrow" (list e (parse-unary p)) nil nil nil)))
                ((accept-op p "->>") (setf e (list :fn "json_extract_arrow2" (list e (parse-unary p)) nil nil nil)))
                (t (return e))))))

(defun parse-unary (p)
  (cond ((accept-op p "-")
         (let ((tok (peek-tok p)))
           (if (and (eq (tok-kind tok) :bigint) (= (car (tok-value tok)) (expt 2 63)))
               (progn (next-tok p) (parse-postfix p (list :lit +i64-min+)))
               (list :unary :neg (parse-unary p)))))
        ((accept-op p "+") (list :unary :pos (parse-unary p)))
        ((accept-op p "~") (list :unary :bitnot (parse-unary p)))
        (t (parse-postfix p (parse-primary p)))))

(defun parse-postfix (p e)
  (loop while (accept-kw p "COLLATE")
        do (setf e (list :collate e (parse-name p t))))
  e)

(defun parse-type-name (p)
  "A declared type: one or more names, optionally (n) or (n,m)."
  (let ((words '()))
    (loop while (and (eq (tok-kind (peek-tok p)) :id)
                     (not (tok-quoted (peek-tok p)))
                     (not (member (tok-value (peek-tok p))
                                  '("PRIMARY" "NOT" "NULL" "UNIQUE" "DEFAULT" "CHECK"
                                    "COLLATE" "REFERENCES" "CONSTRAINT" "AS" "GENERATED")
                                  :test #'name=)))
          do (push (tok-value (next-tok p)) words))
    (let ((base (format nil "~{~a~^ ~}" (nreverse words))))
      (if (accept-op p "(")
          (let ((start (tok-pos (peek-tok p))))
            (loop until (op-p p ")") do (next-tok p))
            (let ((end (tok-pos (peek-tok p))))
              (next-tok p)
              (format nil "~a(~a)" base (remove #\Space (subseq (ps-sql p) start end)))))
          base))))

(defun parse-primary (p)
  (let ((tok (peek-tok p)))
    (case (tok-kind tok)
      ((:integer :float :string :blob) (next-tok p) (list :lit (tok-value tok)))
      (:bigint (next-tok p) (list :lit (cdr (tok-value tok))))
      (:param
       (next-tok p)
       (let ((v (tok-value tok)))
         (cond ((null v) (list :param (incf (ps-nparam p))))
               ((integerp v) (setf (ps-nparam p) (max (ps-nparam p) v)) (list :param v))
               (t (let ((hit (assoc v (ps-names p) :test #'string=)))
                    (list :param
                          (if hit
                              (cdr hit)
                              (let ((k (incf (ps-nparam p))))
                                (push (cons v k) (ps-names p))
                                k))))))))
      (:op
       (cond ((accept-op p "(")
              (if (or (kw-p p "SELECT") (kw-p p "WITH") (kw-p p "VALUES"))
                  (prog1 (list :subquery (parse-select p)) (expect-op p ")"))
                  (let ((items (list (parse-expr p))))
                    (loop while (accept-op p ",") do (push (parse-expr p) items))
                    (expect-op p ")")
                    (if (cdr items) (cons :rowvalue (nreverse items)) (car items)))))
             (t (perr p "syntax error"))))
      (:id
       (cond
         ((tok-quoted tok) (parse-column-ref p))
         ((accept-kw p "NULL") (list :lit :null))
         ((accept-kw p "TRUE") (list :lit 1))
         ((accept-kw p "FALSE") (list :lit 0))
         ((accept-kw p "CURRENT_TIMESTAMP") (list :fn "datetime" (list (list :lit "now")) nil nil nil))
         ((accept-kw p "CURRENT_DATE") (list :fn "date" (list (list :lit "now")) nil nil nil))
         ((accept-kw p "CURRENT_TIME") (list :fn "time" (list (list :lit "now")) nil nil nil))
         ((accept-kw p "CASE")
          (let ((base (unless (kw-p p "WHEN") (parse-expr p)))
                (whens '()) (else nil))
            (loop while (accept-kw p "WHEN")
                  do (let ((w (parse-expr p)))
                       (expect-kw p "THEN")
                       (push (list w (parse-expr p)) whens)))
            (when (null whens) (perr p "CASE without WHEN"))
            (when (accept-kw p "ELSE") (setf else (parse-expr p)))
            (expect-kw p "END")
            (list :case base (nreverse whens) else)))
         ((accept-kw p "CAST")
          (expect-op p "(")
          (let ((e (parse-expr p)))
            (expect-kw p "AS")
            (let ((ty (parse-type-name p)))
              (expect-op p ")")
              (list :cast e ty))))
         ((and (kw-p p "NOT") (kw-p p "EXISTS" 1))
          (incf (ps-pos p) 2)
          (expect-op p "(")
          (prog1 (list :unary :not (list :exists (parse-select p))) (expect-op p ")")))
         ((accept-kw p "EXISTS")
          (expect-op p "(")
          (prog1 (list :exists (parse-select p)) (expect-op p ")")))
         ((accept-kw p "RAISE")
          (expect-op p "(")
          (let ((kind (parse-name p t)) (msg nil))
            (when (accept-op p ",") (setf msg (parse-expr p)))
            (expect-op p ")")
            (list :raise kind msg)))
         ((op-p p "(" 1) (parse-function-call p))
         ((reserved-p (tok-value tok)) (perr p "syntax error"))
         (t (parse-column-ref p))))
      (t (perr p "syntax error")))))

(defun parse-column-ref (p)
  (let ((a (tok-value (next-tok p))))
    (if (accept-op p ".")
        (if (accept-op p "*")
            (list :star a)
            (let ((b (parse-name p t)))
              (if (accept-op p ".")
                  (if (accept-op p "*")
                      (list :star b)
                      (list :col b (parse-name p t)))
                  (list :col a b))))
        (if (eql (tok-quoted (aref (ps-toks p) (1- (ps-pos p)))) #\")
            (list :col nil a :quoted)
            (list :col nil a)))))

(defun parse-function-call (p)
  (let ((name (tok-value (next-tok p))))
    (expect-op p "(")
    (let ((distinct nil) (star nil) (args '()))
      (cond ((accept-op p "*") (setf star t))
            ((op-p p ")"))
            (t (when (accept-kw p "DISTINCT") (setf distinct t))
               (accept-kw p "ALL")
               (push (parse-expr p) args)
               (loop while (accept-op p ",") do (push (parse-expr p) args))))
      ;; ORDER BY inside aggregate calls (group_concat(x ORDER BY y)) — parse and keep
      (let ((order (when (accept-kw p "ORDER" "BY") (parse-order-list p))))
        (expect-op p ")")
        (let ((filter (when (accept-kw p "FILTER")
                        (expect-op p "(") (expect-kw p "WHERE")
                        (prog1 (parse-expr p) (expect-op p ")")))))
          (if (accept-kw p "OVER")
              (list :winfn name (nreverse args) distinct star filter
                    (if (op-p p "(")
                        (progn (next-tok p) (prog1 (parse-window-spec p) (expect-op p ")")))
                        (list :ref (parse-name p t))))
              (let ((f (list :fn name (nreverse args) distinct star filter)))
                (if order (append f (list order)) f))))))))

(defun parse-frame-bound (p)
  (cond ((accept-kw p "UNBOUNDED" "PRECEDING") '(:unbounded-preceding))
        ((accept-kw p "UNBOUNDED" "FOLLOWING") '(:unbounded-following))
        ((accept-kw p "CURRENT" "ROW") '(:current-row))
        (t (let ((e (parse-additive p)))
             (cond ((accept-kw p "PRECEDING") (list :preceding e))
                   ((accept-kw p "FOLLOWING") (list :following e))
                   (t (perr p "expected PRECEDING or FOLLOWING")))))))

(defun parse-window-spec (p)
  "Inside the parentheses of OVER (...) or WINDOW name AS (...)."
  (let ((base nil) (partition nil) (order nil) (frame nil))
    (when (and (name-token-p (peek-tok p))
               (not (kw-p p "PARTITION")) (not (kw-p p "ORDER"))
               (not (kw-p p "ROWS")) (not (kw-p p "RANGE")) (not (kw-p p "GROUPS")))
      (setf base (parse-name p)))
    (when (accept-kw p "PARTITION" "BY")
      (setf partition (list (parse-expr p)))
      (loop while (accept-op p ",") do (push (parse-expr p) partition))
      (setf partition (nreverse partition)))
    (when (accept-kw p "ORDER" "BY")
      (setf order (parse-order-list p)))
    (let ((unit (cond ((accept-kw p "ROWS") :rows) ((accept-kw p "RANGE") :range)
                      ((accept-kw p "GROUPS") :groups))))
      (when unit
        (let (start end)
          (if (accept-kw p "BETWEEN")
              (progn (setf start (parse-frame-bound p))
                     (expect-kw p "AND")
                     (setf end (parse-frame-bound p)))
              (setf start (parse-frame-bound p) end '(:current-row)))
          (when (accept-kw p "EXCLUDE")
            (cond ((accept-kw p "NO" "OTHERS"))
                  (t (perr p "EXCLUDE is not supported"))))
          (setf frame (list unit start end)))))
    (list :spec :base base :partition partition :order order :frame frame)))

;;; ------------------------------------------------------------------
;;; SELECT

(defun parse-order-list (p)
  (let ((items '()))
    (loop
      (let* ((e (parse-expr p))
             (collate nil))
        (when (eq (car e) :collate) (setf collate (third e) e (second e)))
        (let ((desc (cond ((accept-kw p "DESC") t) ((accept-kw p "ASC") nil)))
              (nulls (cond ((accept-kw p "NULLS" "FIRST") :first)
                           ((accept-kw p "NULLS" "LAST") :last))))
          (push (list e desc collate nulls) items)))
      (unless (accept-op p ",") (return)))
    (nreverse items)))

(defun parse-with (p)
  "WITH clause -> (values ctes recursive)."
  (let ((recursive (accept-kw p "RECURSIVE")) (ctes '()))
    (loop
      (let ((name (parse-name p t)) (cols nil))
        (when (accept-op p "(")
          (setf cols (list (parse-name p t)))
          (loop while (accept-op p ",") do (push (parse-name p t) cols))
          (setf cols (nreverse cols))
          (expect-op p ")"))
        (expect-kw p "AS")
        (accept-kw p "NOT")
        (accept-kw p "MATERIALIZED")
        (expect-op p "(")
        (push (list name cols (parse-select p)) ctes)
        (expect-op p ")"))
      (unless (accept-op p ",") (return)))
    (values (nreverse ctes) recursive)))

(defun parse-select (p)
  (let ((s (make-sel)))
    (when (accept-kw p "WITH")
      (multiple-value-bind (ctes rec) (parse-with p)
        (setf (sel-with s) ctes (sel-recursive s) rec)))
    (let ((cores (list (parse-select-core p))) (ops '()))
      (loop
        (let ((op (cond ((accept-kw p "UNION" "ALL") :union-all)
                        ((accept-kw p "UNION") :union)
                        ((accept-kw p "INTERSECT") :intersect)
                        ((accept-kw p "EXCEPT") :except))))
          (unless op (return))
          (push op ops)
          (push (parse-select-core p) cores)))
      (setf (sel-cores s) (nreverse cores) (sel-ops s) (nreverse ops)))
    (when (accept-kw p "ORDER" "BY")
      (setf (sel-order s) (parse-order-list p)))
    (when (accept-kw p "LIMIT")
      (let ((a (parse-expr p)))
        (cond ((accept-kw p "OFFSET") (setf (sel-limit s) a (sel-offset s) (parse-expr p)))
              ((accept-op p ",") (setf (sel-offset s) a (sel-limit s) (parse-expr p)))
              (t (setf (sel-limit s) a)))))
    s))

(defun parse-values-rows (p)
  (let ((rows '()))
    (loop
      (expect-op p "(")
      (let ((row (list (parse-expr p))))
        (loop while (accept-op p ",") do (push (parse-expr p) row))
        (expect-op p ")")
        (push (nreverse row) rows))
      (unless (accept-op p ",") (return)))
    (nreverse rows)))

(defun parse-select-core (p)
  (when (accept-kw p "VALUES")
    (return-from parse-select-core (list :values (parse-values-rows p))))
  (expect-kw p "SELECT")
  (let ((c (make-select-core)))
    (cond ((accept-kw p "DISTINCT") (setf (select-core-distinct c) t))
          ((accept-kw p "ALL")))
    (let ((cols '()))
      (loop
        (cond ((accept-op p "*") (push (list :star nil) cols))
              ((and (eq (tok-kind (peek-tok p)) :id) (op-p p "." 1) (op-p p "*" 2))
               (push (list :star (tok-value (next-tok p))) cols)
               (incf (ps-pos p) 2))
              (t (let* ((start (ps-pos p))
                        (e (parse-expr p))
                        (text (source-text p start))
                        (alias nil))
                   (cond ((accept-kw p "AS") (setf alias (parse-name p t)))
                         ((or (name-token-p (peek-tok p)) (eq (tok-kind (peek-tok p)) :string))
                          (setf alias (parse-name p))))
                   (push (list :expr e alias text) cols))))
        (unless (accept-op p ",") (return)))
      (setf (select-core-cols c) (nreverse cols)))
    (when (accept-kw p "FROM") (setf (select-core-from c) (parse-from p)))
    (when (accept-kw p "WHERE") (setf (select-core-where c) (parse-expr p)))
    (when (accept-kw p "GROUP" "BY")
      (let ((g (list (parse-expr p))))
        (loop while (accept-op p ",") do (push (parse-expr p) g))
        (setf (select-core-group c) (nreverse g))))
    (when (accept-kw p "HAVING") (setf (select-core-having c) (parse-expr p)))
    (when (accept-kw p "WINDOW")
      (let ((defs '()))
        (loop
          (let ((name (parse-name p t)))
            (expect-kw p "AS")
            (expect-op p "(")
            (push (cons name (parse-window-spec p)) defs)
            (expect-op p ")"))
          (unless (accept-op p ",") (return)))
        (setf (select-core-windows c) (nreverse defs))))
    c))

(defun source-text (p start-idx)
  "SQL text of the tokens from index START-IDX up to the current position."
  (let ((toks (ps-toks p)))
    (subseq (ps-sql p) (tok-pos (aref toks start-idx))
            (tok-end (aref toks (1- (ps-pos p)))))))

(defun parse-table-source (p)
  (cond ((accept-op p "(")
         (if (or (kw-p p "SELECT") (kw-p p "WITH") (kw-p p "VALUES"))
             (let ((s (parse-select p)))
               (expect-op p ")")
               (list :subquery s (parse-alias p)))
             ;; parenthesised join
             (let ((from (parse-from p)))
               (expect-op p ")")
               (list :join-group from (parse-alias p)))))
        (t (multiple-value-bind (name schema) (parse-qualified-name p)
             (if (accept-op p "(")
                 ;; table-valued function
                 (let ((args '()))
                   (unless (op-p p ")")
                     (push (parse-expr p) args)
                     (loop while (accept-op p ",") do (push (parse-expr p) args)))
                   (expect-op p ")")
                   (list :tvf name (nreverse args) (parse-alias p)))
                 (let ((alias (parse-alias p)))
                   (cond ((accept-kw p "INDEXED" "BY") (parse-name p t))
                         ((accept-kw p "NOT" "INDEXED")))
                   (list :table name alias schema)))))))

(defun parse-alias (p)
  (cond ((accept-kw p "AS") (parse-name p t))
        ((and (name-token-p (peek-tok p))
              (not (member (tok-value (peek-tok p)) '("INDEXED" "NOT") :test #'name=)))
         (parse-name p))
        ((eq (tok-kind (peek-tok p)) :string) (tok-value (next-tok p)))))

(defun parse-join-op (p)
  "Return the join type keyword or NIL."
  (cond ((accept-op p ",") :comma)
        ((accept-kw p "JOIN") :inner)
        ((accept-kw p "CROSS" "JOIN") :cross)
        ((accept-kw p "INNER" "JOIN") :inner)
        ((accept-kw p "LEFT" "OUTER" "JOIN") :left)
        ((accept-kw p "LEFT" "JOIN") :left)
        ((accept-kw p "RIGHT" "OUTER" "JOIN") :right)
        ((accept-kw p "RIGHT" "JOIN") :right)
        ((accept-kw p "FULL" "OUTER" "JOIN") :full)
        ((accept-kw p "FULL" "JOIN") :full)
        ((accept-kw p "NATURAL")
         (let ((j (parse-join-op p)))
           (unless j (perr p "expected JOIN"))
           (list :natural j)))))

(defun parse-from (p)
  (let ((items (list (list :source (parse-table-source p) :join :first))))
    (loop
      (let ((j (parse-join-op p)))
        (unless j (return))
        (let ((natural nil))
          (when (and (consp j) (eq (car j) :natural)) (setf natural t j (second j)))
          (let ((src (parse-table-source p)) (on nil) (using nil))
            (cond ((accept-kw p "ON") (setf on (parse-expr p)))
                  ((accept-kw p "USING")
                   (expect-op p "(")
                   (setf using (list (parse-name p t)))
                   (loop while (accept-op p ",") do (push (parse-name p t) using))
                   (expect-op p ")")
                   (setf using (nreverse using))))
            (push (list :source src :join j :on on :using using :natural natural) items)))))
    (nreverse items)))

;;; ------------------------------------------------------------------
;;; DML

(defun parse-conflict-clause (p)
  (when (accept-kw p "OR")
    (cond ((accept-kw p "ROLLBACK") :rollback) ((accept-kw p "ABORT") :abort)
          ((accept-kw p "FAIL") :fail) ((accept-kw p "IGNORE") :ignore)
          ((accept-kw p "REPLACE") :replace) (t (perr p "bad conflict clause")))))

(defun parse-returning (p)
  (when (accept-kw p "RETURNING")
    (let ((cols '()))
      (loop
        (if (accept-op p "*")
            (push (list :star nil) cols)
            (let ((e (parse-expr p)) (alias nil))
              (cond ((accept-kw p "AS") (setf alias (parse-name p t)))
                    ((name-token-p (peek-tok p)) (setf alias (parse-name p))))
              (push (list :expr e alias nil) cols)))
        (unless (accept-op p ",") (return)))
      (nreverse cols))))

(defun parse-insert (p with)
  (let ((conflict (if (accept-kw p "REPLACE")
                      :replace
                      (progn (expect-kw p "INSERT") (parse-conflict-clause p)))))
    (expect-kw p "INTO")
    (multiple-value-bind (table schema) (parse-qualified-name p)
      (let ((alias (when (accept-kw p "AS") (parse-name p t)))
            (cols nil) (source nil) (upsert nil))
        (when (accept-op p "(")
          (setf cols (list (parse-name p t)))
          (loop while (accept-op p ",") do (push (parse-name p t) cols))
          (setf cols (nreverse cols))
          (expect-op p ")"))
        (cond ((accept-kw p "DEFAULT" "VALUES") (setf source :default))
              (t (setf source (parse-select p))))
        (loop while (kw-p p "ON")
              do (expect-kw p "ON")
                 (expect-kw p "CONFLICT")
                 (let ((target nil) (target-where nil))
                   (when (accept-op p "(")
                     (setf target (list (parse-expr p)))
                     (loop while (accept-op p ",") do (push (parse-expr p) target))
                     (setf target (nreverse target))
                     (expect-op p ")")
                     (when (accept-kw p "WHERE") (setf target-where (parse-expr p))))
                   (expect-kw p "DO")
                   (if (accept-kw p "NOTHING")
                       (push (list :target target :where target-where :action :nothing) upsert)
                       (progn
                         (expect-kw p "UPDATE") (expect-kw p "SET")
                         (let ((sets (parse-set-list p))
                               (w (when (accept-kw p "WHERE") (parse-expr p))))
                           (push (list :target target :where target-where :action :update
                                       :sets sets :update-where w)
                                 upsert))))))
        (list :insert :with with :conflict conflict :table table :schema schema :alias alias
                      :columns cols :source source :upsert (nreverse upsert)
                      :returning (parse-returning p))))))

(defun parse-set-list (p)
  (let ((sets '()))
    (loop
      (let ((cols (if (accept-op p "(")
                      (let ((cs (list (parse-name p t))))
                        (loop while (accept-op p ",") do (push (parse-name p t) cs))
                        (expect-op p ")")
                        (nreverse cs))
                      (list (parse-name p t)))))
        (expect-op p "=")
        (push (list cols (parse-expr p)) sets))
      (unless (accept-op p ",") (return)))
    (nreverse sets)))

(defun parse-update (p with)
  (expect-kw p "UPDATE")
  (let ((conflict (parse-conflict-clause p)))
    (multiple-value-bind (table schema) (parse-qualified-name p)
      (let ((alias (parse-alias-before p "SET")))
        (expect-kw p "SET")
        (let* ((sets (parse-set-list p))
               (from (when (accept-kw p "FROM") (parse-from p)))
               (where (when (accept-kw p "WHERE") (parse-expr p))))
          (list :update :with with :conflict conflict :table table :schema schema :alias alias
                        :sets sets :from from :where where
                        :returning (parse-returning p)))))))

(defun parse-alias-before (p kw)
  (cond ((accept-kw p "AS") (parse-name p t))
        ((and (name-token-p (peek-tok p)) (not (kw-p p kw))
              (not (kw-p p "INDEXED")) (not (kw-p p "NOT")))
         (parse-name p))))

(defun parse-delete (p with)
  (expect-kw p "DELETE")
  (expect-kw p "FROM")
  (multiple-value-bind (table schema) (parse-qualified-name p)
    (let ((alias (parse-alias-before p "WHERE")))
      (let ((where (when (accept-kw p "WHERE") (parse-expr p))))
        (list :delete :with with :table table :schema schema :alias alias :where where
                      :returning (parse-returning p))))))

;;; ------------------------------------------------------------------
;;; DDL

(defun parse-signed-literal (p)
  (cond ((accept-op p "-")
         (let ((e (parse-primary p)))
           (list :unary :neg e)))
        ((accept-op p "+") (parse-primary p))
        (t (parse-primary p))))

(defun skip-parens (p)
  "Skip a balanced parenthesised group (the opening paren is next)."
  (expect-op p "(")
  (let ((depth 1))
    (loop while (plusp depth)
          do (let ((tok (next-tok p)))
               (when (eq (tok-kind tok) :eof) (perr p "unbalanced parentheses"))
               (cond ((and (eq (tok-kind tok) :op) (string= (tok-value tok) "(")) (incf depth))
                     ((and (eq (tok-kind tok) :op) (string= (tok-value tok) ")")) (decf depth)))))))

(defun parse-fk-action (p)
  (cond ((accept-kw p "SET" "NULL") :set-null)
        ((accept-kw p "SET" "DEFAULT") :set-default)
        ((accept-kw p "CASCADE") :cascade)
        ((accept-kw p "RESTRICT") :restrict)
        ((accept-kw p "NO" "ACTION") :no-action)
        (t (perr p "syntax error"))))

(defun parse-foreign-key-clause (p)
  "After REFERENCES: return (:table name :columns cols :on-delete a :on-update a :deferred b)."
  (let ((table (parse-name p t)) (cols nil) (on-delete :no-action) (on-update :no-action)
        (deferred nil))
    (when (accept-op p "(")
      (setf cols (list (parse-name p t)))
      (loop while (accept-op p ",") do (push (parse-name p t) cols))
      (setf cols (nreverse cols))
      (expect-op p ")"))
    (loop
      (cond ((accept-kw p "ON")
             (cond ((accept-kw p "DELETE") (setf on-delete (parse-fk-action p)))
                   ((accept-kw p "UPDATE") (setf on-update (parse-fk-action p)))
                   (t (parse-name p t) (parse-fk-action p))))
            ((accept-kw p "MATCH") (parse-name p t))
            ((accept-kw p "NOT" "DEFERRABLE")
             (when (accept-kw p "INITIALLY") (parse-name p t)))
            ((accept-kw p "DEFERRABLE")
             (when (accept-kw p "INITIALLY")
               (when (name= (parse-name p t) "DEFERRED") (setf deferred t))))
            (t (return))))
    (list :table table :columns cols :on-delete on-delete :on-update on-update
          :deferred deferred)))

(defun parse-column-def (p)
  (let* ((name (parse-name p t))
         (type (parse-type-name p))
         (col (list :name name :type type)))
    (loop
      (let ((cname (when (accept-kw p "CONSTRAINT") (parse-name p t))))
      (cond ((accept-kw p "PRIMARY" "KEY")
             (let ((order (cond ((accept-kw p "DESC") :desc) ((accept-kw p "ASC") :asc))))
               (setf (getf col :primary-key) (or order t))
               (when (accept-kw p "ON" "CONFLICT") (setf (getf col :pk-conflict) (parse-conflict-name p)))
               (when (accept-kw p "AUTOINCREMENT") (setf (getf col :autoincrement) t))))
            ((accept-kw p "NOT" "NULL")
             (setf (getf col :not-null) t)
             (when (accept-kw p "ON" "CONFLICT") (setf (getf col :nn-conflict) (parse-conflict-name p))))
            ((accept-kw p "NULL"))
            ((accept-kw p "UNIQUE")
             (setf (getf col :unique) t)
             (when (accept-kw p "ON" "CONFLICT") (setf (getf col :unique-conflict) (parse-conflict-name p))))
            ((accept-kw p "CHECK")
             (expect-op p "(")
             (let* ((start (ps-pos p)) (e (parse-expr p)))
               (push (list e (or cname (source-text p start))) (getf col :checks)))
             (expect-op p ")"))
            ((accept-kw p "DEFAULT")
             (setf (getf col :default)
                   (if (accept-op p "(")
                       (prog1 (parse-expr p) (expect-op p ")"))
                       (parse-signed-literal p))))
            ((accept-kw p "COLLATE") (setf (getf col :collate) (parse-name p t)))
            ((accept-kw p "REFERENCES")
             (setf (getf col :references) (parse-foreign-key-clause p)))
            ((or (accept-kw p "GENERATED" "ALWAYS" "AS") (accept-kw p "AS"))
             (expect-op p "(")
             (setf (getf col :generated) (parse-expr p))
             (expect-op p ")")
             (cond ((accept-kw p "STORED") (setf (getf col :stored) t))
                   ((accept-kw p "VIRTUAL"))))
            (t (return)))))
    col))

(defun parse-conflict-name (p)
  (let ((n (string-upcase-ascii (parse-name p t))))
    (intern n :keyword)))

(defun parse-indexed-columns (p)
  (expect-op p "(")
  (let ((cols '()))
    (loop
      (let* ((e (parse-expr p)) (collate nil))
        (when (eq (car e) :collate) (setf collate (third e) e (second e)))
        (let ((desc (cond ((accept-kw p "DESC") t) ((accept-kw p "ASC") nil))))
          (push (list e collate desc) cols)))
      (unless (accept-op p ",") (return)))
    (expect-op p ")")
    (nreverse cols)))

(defun parse-table-constraint (p)
  (let ((cname (when (accept-kw p "CONSTRAINT") (parse-name p t))))
  (cond ((accept-kw p "PRIMARY" "KEY")
         (let ((cols (parse-indexed-columns p)) (conflict nil) (autoinc nil))
           (when (accept-kw p "AUTOINCREMENT") (setf autoinc t))
           (when (accept-kw p "ON" "CONFLICT") (setf conflict (parse-conflict-name p)))
           (list :primary-key cols conflict autoinc)))
        ((accept-kw p "UNIQUE")
         (let ((cols (parse-indexed-columns p)) (conflict nil))
           (when (accept-kw p "ON" "CONFLICT") (setf conflict (parse-conflict-name p)))
           (list :unique cols conflict)))
        ((accept-kw p "CHECK")
         (expect-op p "(")
         (let* ((start (ps-pos p)) (e (parse-expr p)))
           (prog1 (list :check e (or cname (source-text p start))) (expect-op p ")"))))
        ((accept-kw p "FOREIGN" "KEY")
         (expect-op p "(")
         (let ((cols (list (parse-name p t))))
           (loop while (accept-op p ",") do (push (parse-name p t) cols))
           (expect-op p ")")
           (expect-kw p "REFERENCES")
           (list :foreign-key (nreverse cols) (parse-foreign-key-clause p))))
        (t (perr p "bad table constraint")))))

(defun parse-create (p)
  (expect-kw p "CREATE")
  (let ((temp (or (accept-kw p "TEMP") (accept-kw p "TEMPORARY")))
        (unique (accept-kw p "UNIQUE")))
    (cond
      ((accept-kw p "TABLE")
       (let ((ine (accept-kw p "IF" "NOT" "EXISTS")))
         (multiple-value-bind (name schema) (parse-qualified-name p)
           (if (accept-kw p "AS")
               (list :create-table :name name :schema schema :temp temp :if-not-exists ine
                                   :as-select (parse-select p))
               (let ((cols '()) (constraints '()))
                 (expect-op p "(")
                 (loop
                   (if (or (kw-p p "CONSTRAINT") (kw-p p "PRIMARY") (kw-p p "UNIQUE")
                           (kw-p p "CHECK") (kw-p p "FOREIGN"))
                       (push (parse-table-constraint p) constraints)
                       (push (parse-column-def p) cols))
                   (unless (accept-op p ",") (return)))
                 (expect-op p ")")
                 (let ((without-rowid nil) (strict nil))
                   (loop
                     (cond ((accept-kw p "WITHOUT")
                            (let ((w (parse-name p t)))
                              (unless (name= w "ROWID") (perr p "expected ROWID"))
                              (setf without-rowid t)))
                           ((accept-kw p "STRICT") (setf strict t))
                           (t (return)))
                     (unless (accept-op p ",") (return)))
                   (list :create-table :name name :schema schema :temp temp :if-not-exists ine
                                       :columns (nreverse cols)
                                       :constraints (nreverse constraints)
                                       :without-rowid without-rowid :strict strict)))))))
      ((accept-kw p "INDEX")
       (let ((ine (accept-kw p "IF" "NOT" "EXISTS")))
         (multiple-value-bind (name schema) (parse-qualified-name p)
           (expect-kw p "ON")
           (let* ((table (parse-name p t))
                  (cols (parse-indexed-columns p))
                  (where (when (accept-kw p "WHERE") (parse-expr p))))
             (list :create-index :name name :schema schema :table table :unique unique
                                 :if-not-exists ine :columns cols :where where)))))
      ((accept-kw p "VIEW")
       (let ((ine (accept-kw p "IF" "NOT" "EXISTS")))
         (multiple-value-bind (name schema) (parse-qualified-name p)
           (let ((cols nil))
             (when (accept-op p "(")
               (setf cols (list (parse-name p t)))
               (loop while (accept-op p ",") do (push (parse-name p t) cols))
               (setf cols (nreverse cols))
               (expect-op p ")"))
             (expect-kw p "AS")
             (list :create-view :name name :schema schema :temp temp :if-not-exists ine :columns cols
                                :select (parse-select p))))))
      ((accept-kw p "TRIGGER")
       (let ((ine (accept-kw p "IF" "NOT" "EXISTS")))
         (multiple-value-bind (name schema) (parse-qualified-name p)
           (append (parse-trigger-rest p name ine) (list :schema schema :temp temp)))))
      ((accept-kw p "VIRTUAL" "TABLE")
       (perr p "virtual tables are not supported"))
      (t (perr p "syntax error")))))

(defun parse-trigger-rest (p name ine)
  (let ((timing (cond ((accept-kw p "BEFORE") :before) ((accept-kw p "AFTER") :after)
                      ((accept-kw p "INSTEAD" "OF") :instead-of) (t :before)))
        (event nil) (columns nil))
    (cond ((accept-kw p "DELETE") (setf event :delete))
          ((accept-kw p "INSERT") (setf event :insert))
          ((accept-kw p "UPDATE")
           (setf event :update)
           (when (accept-kw p "OF")
             (setf columns (list (parse-name p t)))
             (loop while (accept-op p ",") do (push (parse-name p t) columns))))
          (t (perr p "expected DELETE, INSERT or UPDATE")))
    (expect-kw p "ON")
    (let ((table (parse-name p t)) (when-expr nil) (body '()))
      (accept-kw p "FOR" "EACH" "ROW")
      (when (accept-kw p "WHEN") (setf when-expr (parse-expr p)))
      (expect-kw p "BEGIN")
      (loop until (accept-kw p "END")
            do (push (parse-statement p) body)
               (expect-op p ";"))
      (list :create-trigger :name name :if-not-exists ine :timing timing :event event
                            :columns (nreverse columns) :table table :when when-expr
                            :body (nreverse body)))))

(defun parse-drop (p)
  (expect-kw p "DROP")
  (let ((kind (cond ((accept-kw p "TABLE") :table) ((accept-kw p "INDEX") :index)
                    ((accept-kw p "VIEW") :view) ((accept-kw p "TRIGGER") :trigger)
                    (t (perr p "syntax error")))))
    (let ((ie (accept-kw p "IF" "EXISTS")))
      (multiple-value-bind (name schema) (parse-qualified-name p)
        (list :drop :kind kind :name name :schema schema :if-exists ie)))))

(defun parse-alter (p)
  (expect-kw p "ALTER") (expect-kw p "TABLE")
  (multiple-value-bind (name schema) (parse-qualified-name p)
    (cond ((accept-kw p "RENAME" "TO") (list :alter :table name :schema schema :rename-to (parse-name p t)))
          ((accept-kw p "RENAME")
           (accept-kw p "COLUMN")
           (let ((old (parse-name p t)))
             (expect-kw p "TO")
             (list :alter :table name :schema schema :rename-column old :to (parse-name p t))))
          ((accept-kw p "ADD")
           (accept-kw p "COLUMN")
           (let ((start (tok-pos (peek-tok p))))
             (let ((def (parse-column-def p)))
               (list :alter :table name :schema schema :add-column def
                            :sql (string-trim " " (subseq (ps-sql p) start
                                                          (tok-pos (peek-tok p))))))))
          ((accept-kw p "DROP")
           (accept-kw p "COLUMN")
           (list :alter :table name :schema schema :drop-column (parse-name p t)))
          (t (perr p "syntax error")))))

(defun parse-pragma (p)
  (expect-kw p "PRAGMA")
  (multiple-value-bind (name schema) (parse-qualified-name p)
    (declare (ignore schema))
    (let ((value nil))
      (cond ((accept-op p "=") (setf value (parse-pragma-value p)))
            ((accept-op p "(") (setf value (parse-pragma-value p)) (expect-op p ")")))
      (list :pragma :name name :value value))))

(defun parse-pragma-value (p)
  (let ((tok (next-tok p)))
    (case (tok-kind tok)
      ((:integer :float :string) (tok-value tok))
      (:id (tok-value tok))
      (:op (cond ((string= (tok-value tok) "-") (- (tok-value (next-tok p))))
                 ((string= (tok-value tok) "+") (tok-value (next-tok p)))
                 (t (perr p "bad pragma value"))))
      (t (perr p "bad pragma value")))))

(defun parse-statement (p)
  (cond
    ((or (kw-p p "SELECT") (kw-p p "VALUES")) (list :select (parse-select p)))
    ((accept-kw p "WITH")
     (multiple-value-bind (ctes rec) (parse-with p)
       (let ((with (list ctes rec)))
         (cond ((or (kw-p p "SELECT") (kw-p p "VALUES"))
                (let ((s (parse-select p)))
                  (setf (sel-with s) ctes (sel-recursive s) rec)
                  (list :select s)))
               ((or (kw-p p "INSERT") (kw-p p "REPLACE")) (parse-insert p with))
               ((kw-p p "UPDATE") (parse-update p with))
               ((kw-p p "DELETE") (parse-delete p with))
               (t (perr p "syntax error"))))))
    ((or (kw-p p "INSERT") (kw-p p "REPLACE")) (parse-insert p nil))
    ((kw-p p "UPDATE") (parse-update p nil))
    ((kw-p p "DELETE") (parse-delete p nil))
    ((kw-p p "CREATE") (parse-create p))
    ((kw-p p "DROP") (parse-drop p))
    ((kw-p p "ALTER") (parse-alter p))
    ((kw-p p "PRAGMA") (parse-pragma p))
    ((accept-kw p "BEGIN")
     (or (accept-kw p "DEFERRED") (accept-kw p "IMMEDIATE") (accept-kw p "EXCLUSIVE"))
     (accept-kw p "TRANSACTION")
     (list :begin))
    ((or (accept-kw p "COMMIT") (accept-kw p "END"))
     (accept-kw p "TRANSACTION")
     (list :commit))
    ((accept-kw p "ROLLBACK")
     (accept-kw p "TRANSACTION")
     (if (accept-kw p "TO")
         (progn (accept-kw p "SAVEPOINT") (list :rollback-to (parse-name p t)))
         (list :rollback)))
    ((accept-kw p "SAVEPOINT") (list :savepoint (parse-name p t)))
    ((accept-kw p "RELEASE") (accept-kw p "SAVEPOINT") (list :release (parse-name p t)))
    ((accept-kw p "ATTACH")
     (accept-kw p "DATABASE")
     (let ((file (parse-expr p)))
       (expect-kw p "AS")
       (list :attach file (parse-name p t))))
    ((accept-kw p "DETACH")
     (accept-kw p "DATABASE")
     (list :detach (parse-name p t)))
    ((accept-kw p "VACUUM")
     (let ((schema (when (and (name-token-p (peek-tok p) t) (not (kw-p p "INTO")))
                     (parse-name p t))))
       (list :vacuum schema (when (accept-kw p "INTO") (parse-expr p)))))
    ((accept-kw p "ANALYZE") (unless (op-p p ";") (when (name-token-p (peek-tok p) t) (parse-qualified-name p))) (list :noop))
    ((accept-kw p "REINDEX") (when (name-token-p (peek-tok p) t) (parse-qualified-name p)) (list :noop))
    ((accept-kw p "EXPLAIN") (perr p "EXPLAIN is not supported"))
    (t (perr p "syntax error"))))

(defun parse-sql (sql)
  "Parse SQL into a list of (statement . source-text), plus the number of
positional parameters."
  (let ((p (make-parser :sql sql :toks (tokenize sql)))
        (stmts '()))
    (loop
      (loop while (accept-op p ";"))
      (when (eq (tok-kind (peek-tok p)) :eof) (return))
      (let* ((start (tok-pos (peek-tok p)))
             (st (parse-statement p))
             (end (tok-pos (peek-tok p))))
        (unless (or (op-p p ";") (eq (tok-kind (peek-tok p)) :eof))
          (perr p "syntax error"))
        (push (cons st (string-right-trim '(#\Space #\Tab #\Newline #\Return)
                                          (subseq sql start end)))
              stmts)))
    (values (nreverse stmts) (ps-nparam p) (ps-names p))))

(defun parse-one-expr (sql)
  (let* ((p (make-parser :sql sql :toks (tokenize sql)))
         (e (parse-expr p)))
    (unless (eq (tok-kind (peek-tok p)) :eof) (perr p "trailing text in expression"))
    e))
