;;;; printf.lisp — SQLite's printf(), including its own floating-point
;;;; digit generation (sqlite3_str_vappendf in SQLite 3.40): a decimal
;;;; "rounder" is added before digits are extracted, %f adds a 3e-16
;;;; relative fudge, and at most 16 significant digits are produced
;;;; (26 with the ! flag).  The arithmetic here is exact, where SQLite's
;;;; is long double; the two agree except at the last representable digit.

(in-package #:sqlite-pure)

(defun sql-float-text (x xtype precision &key alt alt2 (plus nil) (space nil))
  "Format finite or infinite double X as SQLite does for conversion
XTYPE (:float :exp :generic).  Returns the string without width padding."
  (let ((prefix (cond ((minusp (float-sign x)) (if (zerop x) "" "-"))
                      (plus "+") (space " ") (t ""))))
    (when (and (zerop x) (minusp (float-sign x))) (setf prefix (cond (plus "+") (space " ") (t ""))))
    (when (float-infinity-p x)
      (return-from sql-float-text (concatenate 'string prefix "Inf")))
    (let* ((r (abs (rational x)))
           (precision (if (and (eq xtype :generic) (plusp precision)) (1- precision) precision))
           (rounder (* 1/2 (expt 1/10 precision)))
           (exp 0)
           (flag-rtz nil)
           (generic (eq xtype :generic))
           (nsd (if alt2 26 16))
           (out (make-string-output-stream)))
      (when (eq xtype :float)
        (let ((ex (if (zerop x) -1023 (- (nth-value 1 (decode-float x)) 1))))
          (when (< (+ precision (truncate ex 3)) 15)
            (incf rounder (* r 3/10000000000000000))))
        (incf r rounder))
      ;; normalise R into [1,10)
      (when (plusp r)
        (loop while (>= r (expt 10 (1+ exp))) do (incf exp))
        (loop while (< r (expt 10 exp)) do (decf exp))
        (setf r (/ r (expt 10 exp))))
      (unless (eq xtype :float)
        (incf r rounder)
        (when (>= r 10) (setf r (/ r 10)) (incf exp)))
      (when (eq xtype :generic)
        (setf flag-rtz (not alt))
        (if (or (< exp -4) (> exp precision))
            (setf xtype :exp)
            (setf precision (- precision exp) xtype :float)))
      (unless generic (setf flag-rtz alt2))
      (let ((e2 (if (eq xtype :exp) 0 exp))
            (dp nil))
        (flet ((digit ()
                 (if (<= nsd 0)
                     #\0
                     (let ((d (min 9 (floor r))))
                       (decf nsd)
                       (setf r (* (- r d) 10))
                       (code-char (+ 48 d))))))
          (if (< e2 0)
              (write-char #\0 out)
              (loop while (>= e2 0) do (write-char (digit) out) (decf e2)))
          (when (or (plusp precision) alt alt2)
            (write-char #\. out) (setf dp t))
          (incf e2)
          (loop while (and (< e2 0) (plusp precision))
                do (write-char #\0 out) (decf precision) (incf e2))
          (loop while (plusp precision)
                do (write-char (digit) out) (decf precision)))
        (let ((s (get-output-stream-string out)))
          (when (and flag-rtz dp)
            (setf s (string-right-trim "0" s))
            (when (char= (char s (1- (length s))) #\.)
              (setf s (if alt2 (concatenate 'string s "0") (subseq s 0 (1- (length s)))))))
          (when (eq xtype :exp)
            (setf s (format nil "~ae~a~2,'0d" s (if (minusp exp) "-" "+") (abs exp))))
          (concatenate 'string prefix s))))))

(defun format-real (x)
  "REAL -> TEXT, as SQLite's \"%!.15g\"."
  (if (float-nan-p x) "NaN" (sql-float-text x :generic 15 :alt2 t)))

(defun sql-round (x n)
  (cond ((or (float-infinity-p x) (> (abs x) 4503599627370496d0)) x)
        ((zerop n)
         (let ((v (float (truncate (+ (rational x) (if (minusp x) -1/2 1/2))) 1d0)))
           (if (and (zerop v) (minusp x)) -0d0 v)))
        (t (let ((v (value-to-real (sql-float-text x :float n))))
             v))))

(defun add-thousands (digits)
  (let ((n (length digits)))
    (with-output-to-string (s)
      (loop for c across digits
            for i from 0
            do (when (and (plusp i) (zerop (mod (- n i) 3))) (write-char #\, s))
               (write-char c s)))))

(defun sql-printf (fmt args)
  (let ((out (make-string-output-stream))
        (i 0) (n (length fmt)))
    (flet ((next-arg () (if args (pop args) :null)))
      (loop while (< i n)
            do (let ((c (char fmt i)))
                 (if (char/= c #\%)
                     (progn (write-char c out) (incf i))
                     (let ((minus nil) (plus nil) (space nil) (zero nil) (alt nil) (alt2 nil)
                           (comma nil) (width nil) (precision nil))
                       (incf i)
                       (when (>= i n) (return))
                       ;; flags
                       (loop while (< i n)
                             do (case (char fmt i)
                                  (#\- (setf minus t)) (#\+ (setf plus t)) (#\Space (setf space t))
                                  (#\0 (setf zero t)) (#\# (setf alt t)) (#\! (setf alt2 t))
                                  (#\, (setf comma t))
                                  (t (return)))
                                (incf i))
                       ;; width
                       (cond ((and (< i n) (char= (char fmt i) #\*))
                              (let ((w (value-to-integer (next-arg))))
                                (setf w (if (integerp w) w 0))
                                (when (minusp w) (setf minus t w (- w)))
                                (setf width w))
                              (incf i))
                             (t (let ((start i))
                                  (loop while (and (< i n) (digit-char-p (char fmt i))) do (incf i))
                                  (when (> i start) (setf width (parse-integer fmt :start start :end i))))))
                       ;; precision
                       (when (and (< i n) (char= (char fmt i) #\.))
                         (incf i)
                         (cond ((and (< i n) (char= (char fmt i) #\*))
                                (let ((p (value-to-integer (next-arg))))
                                  (setf precision (if (integerp p) (abs p) 0)))
                                (incf i))
                               (t (let ((start i))
                                    (loop while (and (< i n) (digit-char-p (char fmt i))) do (incf i))
                                    (setf precision (if (> i start) (parse-integer fmt :start start :end i) 0))))))
                       ;; length modifiers
                       (loop while (and (< i n) (member (char fmt i) '(#\l #\h #\L #\q #\j #\z #\t)))
                             do (if (and (char= (char fmt i) #\q) (or (>= (1+ i) n)
                                                                      (not (member (char fmt (1+ i)) '(#\d #\i #\u #\x)))))
                                    (return)
                                    (incf i)))
                       (when (>= i n) (return))
                       (let* ((type (char fmt i))
                              (numeric nil)
                              (body
                                (case type
                                  (#\% "%")
                                  ((#\d #\i)
                                   (setf numeric t)
                                   (let* ((v (value-to-integer (next-arg)))
                                          (v (if (integerp v) v 0))
                                          (digits (format nil "~d" (abs v))))
                                     (when (and precision (< (length digits) precision))
                                       (setf digits (concatenate 'string (make-string (- precision (length digits)) :initial-element #\0) digits)))
                                     (when comma (setf digits (add-thousands digits)))
                                     (concatenate 'string
                                                  (cond ((minusp v) "-") (plus "+") (space " ") (t ""))
                                                  digits)))
                                  ((#\u #\x #\X #\o)
                                   (setf numeric t)
                                   (let* ((v (value-to-integer (next-arg)))
                                          (u (ldb (byte 64 0) (if (integerp v) v 0)))
                                          (digits (ecase type
                                                    (#\u (format nil "~d" u))
                                                    (#\x (string-downcase (format nil "~x" u)))
                                                    (#\X (format nil "~:@(~x~)" u))
                                                    (#\o (format nil "~o" u)))))
                                     (when (and precision (< (length digits) precision))
                                       (setf digits (concatenate 'string (make-string (- precision (length digits)) :initial-element #\0) digits)))
                                     (when (and comma (char= type #\u)) (setf digits (add-thousands digits)))
                                     (concatenate 'string
                                                  (if (and alt (/= u 0))
                                                      (case type (#\x "0x") (#\X "0X") (#\o "0") (t ""))
                                                      "")
                                                  digits)))
                                  ((#\f #\F #\e #\E #\g #\G)
                                   (setf numeric t)
                                   (let* ((v (value-to-real (next-arg)))
                                          (v (if (floatp v) v 0d0))
                                          (s (sql-float-text v (case (char-downcase type)
                                                               (#\f :float) (#\e :exp) (t :generic))
                                                           (or precision 6)
                                                           :alt alt :alt2 alt2 :plus plus :space space)))
                                     (if (upper-case-p type) (string-upcase s) s)))
                                  ((#\s #\z)
                                   (let* ((v (next-arg))
                                          (s (if (eq v :null) "" (value-to-text v))))
                                     (if (and precision (< precision (length s))) (subseq s 0 precision) s)))
                                  (#\c
                                   (let* ((v (next-arg))
                                          (s (if (eq v :null) "" (value-to-text v)))
                                          (ch (if (plusp (length s)) (char s 0) nil)))
                                     (if ch (make-string (max 1 (or precision 1)) :initial-element ch) "")))
                                  (#\q (let ((v (next-arg)))
                                         (if (eq v :null) "(NULL)" (substitute-string "'" "''" (value-to-text v)))))
                                  (#\Q (let ((v (next-arg)))
                                         (if (eq v :null) "NULL"
                                             (format nil "'~a'" (substitute-string "'" "''" (value-to-text v))))))
                                  (#\w (let ((v (next-arg)))
                                         (if (eq v :null) "(NULL)" (substitute-string "\"" "\"\"" (value-to-text v)))))
                                  (t nil))))
                         (incf i)
                         (when body
                           (when (and width (< (length body) width))
                             (let ((pad (- width (length body))))
                               (setf body
                                     (cond (minus (concatenate 'string body (make-string pad :initial-element #\Space)))
                                           ((and zero numeric)
                                            (let ((sign-len (if (and (plusp (length body))
                                                                     (member (char body 0) '(#\- #\+ #\Space)))
                                                                1 0)))
                                              (concatenate 'string (subseq body 0 sign-len)
                                                           (make-string pad :initial-element #\0)
                                                           (subseq body sign-len))))
                                           (t (concatenate 'string (make-string pad :initial-element #\Space) body))))))
                           (write-string body out)))))))
      (get-output-stream-string out))))

(defsqlfun "printf" (0 nil) (args)
  (if (or (null args) (eq (first args) :null))
      :null
      (sql-printf (value-to-text (first args)) (rest args))))

(defsqlfun "format" (0 nil) (args)
  (if (or (null args) (eq (first args) :null))
      :null
      (sql-printf (value-to-text (first args)) (rest args))))
